/** This file was auto-generated by Fern from our API Definition. */
package resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentV1AgentAudioDone.Builder.class)
public final class AgentV1AgentAudioDone {
  private final Map<String, Object> additionalProperties;

  private AgentV1AgentAudioDone(Map<String, Object> additionalProperties) {
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Message type identifier indicating the agent has finished sending audio
   */
  @JsonProperty("type")
  public String getType() {
    return "AgentAudioDone";
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentV1AgentAudioDone;
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static final class Builder {
    @JsonAnySetter private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {}

    public Builder from(AgentV1AgentAudioDone other) {
      return this;
    }

    public AgentV1AgentAudioDone build() {
      return new AgentV1AgentAudioDone(additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
