/** This file was auto-generated by Fern from our API Definition. */
package resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentV1SettingsAgentContextContextMessagesItemFunctionCalls.Builder.class)
public final class AgentV1SettingsAgentContextContextMessagesItemFunctionCalls {
  private final List<AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem>
      functionCalls;

  private final Map<String, Object> additionalProperties;

  private AgentV1SettingsAgentContextContextMessagesItemFunctionCalls(
      List<AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem>
          functionCalls,
      Map<String, Object> additionalProperties) {
    this.functionCalls = functionCalls;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public String getType() {
    return "History";
  }

  /**
   * @return List of function call objects
   */
  @JsonProperty("function_calls")
  public List<AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem>
      getFunctionCalls() {
    return functionCalls;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentV1SettingsAgentContextContextMessagesItemFunctionCalls
        && equalTo((AgentV1SettingsAgentContextContextMessagesItemFunctionCalls) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentV1SettingsAgentContextContextMessagesItemFunctionCalls other) {
    return functionCalls.equals(other.functionCalls);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.functionCalls);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static final class Builder {
    private List<AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem>
        functionCalls = new ArrayList<>();

    @JsonAnySetter private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {}

    public Builder from(AgentV1SettingsAgentContextContextMessagesItemFunctionCalls other) {
      functionCalls(other.getFunctionCalls());
      return this;
    }

    /** List of function call objects */
    @JsonSetter(value = "function_calls", nulls = Nulls.SKIP)
    public Builder functionCalls(
        List<AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem>
            functionCalls) {
      this.functionCalls.clear();
      if (functionCalls != null) {
        this.functionCalls.addAll(functionCalls);
      }
      return this;
    }

    public Builder addFunctionCalls(
        AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem
            functionCalls) {
      this.functionCalls.add(functionCalls);
      return this;
    }

    public Builder addAllFunctionCalls(
        List<AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem>
            functionCalls) {
      if (functionCalls != null) {
        this.functionCalls.addAll(functionCalls);
      }
      return this;
    }

    public AgentV1SettingsAgentContextContextMessagesItemFunctionCalls build() {
      return new AgentV1SettingsAgentContextContextMessagesItemFunctionCalls(
          functionCalls, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
