/** This file was auto-generated by Fern from our API Definition. */
package resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder =
        AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem.Builder.class)
public final class AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem {
  private final String id;

  private final String name;

  private final boolean clientSide;

  private final String arguments;

  private final String response;

  private final Map<String, Object> additionalProperties;

  private AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem(
      String id,
      String name,
      boolean clientSide,
      String arguments,
      String response,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.clientSide = clientSide;
    this.arguments = arguments;
    this.response = response;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Unique identifier for the function call
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return Name of the function called
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return Indicates if the call was client-side or server-side
   */
  @JsonProperty("client_side")
  public boolean getClientSide() {
    return clientSide;
  }

  /**
   * @return Arguments passed to the function
   */
  @JsonProperty("arguments")
  public String getArguments() {
    return arguments;
  }

  /**
   * @return Response from the function call
   */
  @JsonProperty("response")
  public String getResponse() {
    return response;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other
            instanceof AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem
        && equalTo(
            (AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(
      AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem other) {
    return id.equals(other.id)
        && name.equals(other.name)
        && clientSide == other.clientSide
        && arguments.equals(other.arguments)
        && response.equals(other.response);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.clientSide, this.arguments, this.response);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /** Unique identifier for the function call */
    NameStage id(@NotNull String id);

    Builder from(
        AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem other);
  }

  public interface NameStage {
    /** Name of the function called */
    ClientSideStage name(@NotNull String name);
  }

  public interface ClientSideStage {
    /** Indicates if the call was client-side or server-side */
    ArgumentsStage clientSide(boolean clientSide);
  }

  public interface ArgumentsStage {
    /** Arguments passed to the function */
    ResponseStage arguments(@NotNull String arguments);
  }

  public interface ResponseStage {
    /** Response from the function call */
    _FinalStage response(@NotNull String response);
  }

  public interface _FinalStage {
    AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static final class Builder
      implements IdStage, NameStage, ClientSideStage, ArgumentsStage, ResponseStage, _FinalStage {
    private String id;

    private String name;

    private boolean clientSide;

    private String arguments;

    private String response;

    @JsonAnySetter private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {}

    @java.lang.Override
    public Builder from(
        AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem other) {
      id(other.getId());
      name(other.getName());
      clientSide(other.getClientSide());
      arguments(other.getArguments());
      response(other.getResponse());
      return this;
    }

    /**
     * Unique identifier for the function call
     *
     * <p>Unique identifier for the function call
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public NameStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * Name of the function called
     *
     * <p>Name of the function called
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public ClientSideStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * Indicates if the call was client-side or server-side
     *
     * <p>Indicates if the call was client-side or server-side
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("client_side")
    public ArgumentsStage clientSide(boolean clientSide) {
      this.clientSide = clientSide;
      return this;
    }

    /**
     * Arguments passed to the function
     *
     * <p>Arguments passed to the function
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("arguments")
    public ResponseStage arguments(@NotNull String arguments) {
      this.arguments = Objects.requireNonNull(arguments, "arguments must not be null");
      return this;
    }

    /**
     * Response from the function call
     *
     * <p>Response from the function call
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("response")
    public _FinalStage response(@NotNull String response) {
      this.response = Objects.requireNonNull(response, "response must not be null");
      return this;
    }

    @java.lang.Override
    public AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem build() {
      return new AgentV1SettingsAgentContextContextMessagesItemFunctionCallsFunctionCallsItem(
          id, name, clientSide, arguments, response, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
