/** This file was auto-generated by Fern from our API Definition. */
package resources.agent;

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.agent.v1.V1Client;

public class AgentClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<V1Client> v1Client;

  public AgentClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.v1Client = Suppliers.memoize(() -> new V1Client(clientOptions));
  }

  public V1Client v1() {
    return this.v1Client.get();
  }
}
