/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.listen.v2.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListenV2TurnInfoWordsItem.Builder.class)
public final class ListenV2TurnInfoWordsItem {
    private final String word;

    private final float confidence;

    private final double start;

    private final double end;

    private final Map<String, Object> additionalProperties;

    private ListenV2TurnInfoWordsItem(
            String word, float confidence, double start, double end, Map<String, Object> additionalProperties) {
        this.word = word;
        this.confidence = confidence;
        this.start = start;
        this.end = end;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The individual punctuated, properly-cased word from the transcript
     */
    @JsonProperty("word")
    public String getWord() {
        return word;
    }

    /**
     * @return Confidence that this word was transcribed correctly
     */
    @JsonProperty("confidence")
    public float getConfidence() {
        return confidence;
    }

    /**
     * @return The start time of the word
     */
    @JsonProperty("start")
    public double getStart() {
        return start;
    }

    /**
     * @return The end time of the word
     */
    @JsonProperty("end")
    public double getEnd() {
        return end;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListenV2TurnInfoWordsItem && equalTo((ListenV2TurnInfoWordsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListenV2TurnInfoWordsItem other) {
        return word.equals(other.word) && confidence == other.confidence && start == other.start && end == other.end;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.word, this.confidence, this.start, this.end);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static WordStage builder() {
        return new Builder();
    }

    public interface WordStage {
        /**
         * <p>The individual punctuated, properly-cased word from the transcript</p>
         */
        ConfidenceStage word(@NotNull String word);

        Builder from(ListenV2TurnInfoWordsItem other);
    }

    public interface ConfidenceStage {
        /**
         * <p>Confidence that this word was transcribed correctly</p>
         */
        StartStage confidence(float confidence);
    }

    public interface StartStage {
        /**
         * <p>The start time of the word</p>
         */
        EndStage start(double start);
    }

    public interface EndStage {
        /**
         * <p>The end time of the word</p>
         */
        _FinalStage end(double end);
    }

    public interface _FinalStage {
        ListenV2TurnInfoWordsItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements WordStage, ConfidenceStage, StartStage, EndStage, _FinalStage {
        private String word;

        private float confidence;

        private double start;

        private double end;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListenV2TurnInfoWordsItem other) {
            word(other.getWord());
            confidence(other.getConfidence());
            start(other.getStart());
            end(other.getEnd());
            return this;
        }

        /**
         * <p>The individual punctuated, properly-cased word from the transcript</p>
         * <p>The individual punctuated, properly-cased word from the transcript</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("word")
        public ConfidenceStage word(@NotNull String word) {
            this.word = Objects.requireNonNull(word, "word must not be null");
            return this;
        }

        /**
         * <p>Confidence that this word was transcribed correctly</p>
         * <p>Confidence that this word was transcribed correctly</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("confidence")
        public StartStage confidence(float confidence) {
            this.confidence = confidence;
            return this;
        }

        /**
         * <p>The start time of the word</p>
         * <p>The start time of the word</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("start")
        public EndStage start(double start) {
            this.start = start;
            return this;
        }

        /**
         * <p>The end time of the word</p>
         * <p>The end time of the word</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("end")
        public _FinalStage end(double end) {
            this.end = end;
            return this;
        }

        @java.lang.Override
        public ListenV2TurnInfoWordsItem build() {
            return new ListenV2TurnInfoWordsItem(word, confidence, start, end, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
