/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.manage.v1.models;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import resources.manage.v1.models.requests.ModelsListRequest;
import types.GetModelV1Response;
import types.ListModelsV1Response;

public class AsyncModelsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawModelsClient rawClient;

  public AsyncModelsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawModelsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawModelsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns metadata on all the latest public models. To retrieve custom models, use Get Project Models.
   */
  public CompletableFuture<ListModelsV1Response> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  /**
   * Returns metadata on all the latest public models. To retrieve custom models, use Get Project Models.
   */
  public CompletableFuture<ListModelsV1Response> list(ModelsListRequest request) {
    return this.rawClient.list(request).thenApply(response -> response.body());
  }

  /**
   * Returns metadata on all the latest public models. To retrieve custom models, use Get Project Models.
   */
  public CompletableFuture<ListModelsV1Response> list(ModelsListRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns metadata for a specific public model
   */
  public CompletableFuture<GetModelV1Response> get(String modelId) {
    return this.rawClient.get(modelId).thenApply(response -> response.body());
  }

  /**
   * Returns metadata for a specific public model
   */
  public CompletableFuture<GetModelV1Response> get(String modelId, RequestOptions requestOptions) {
    return this.rawClient.get(modelId, requestOptions).thenApply(response -> response.body());
  }
}
