/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.resources.manage.v1.projects.billing.purchases;

import com.deepgram.api.core.ClientOptions;
import com.deepgram.api.core.RequestOptions;
import com.deepgram.api.resources.manage.v1.projects.billing.purchases.requests.PurchasesListRequest;
import com.deepgram.api.types.ListProjectPurchasesV1Response;

public class PurchasesClient {
    protected final ClientOptions clientOptions;

    private final RawPurchasesClient rawClient;

    public PurchasesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawPurchasesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawPurchasesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns the original purchased amount on an order transaction
     */
    public ListProjectPurchasesV1Response list(String projectId) {
        return this.rawClient.list(projectId).body();
    }

    /**
     * Returns the original purchased amount on an order transaction
     */
    public ListProjectPurchasesV1Response list(String projectId, PurchasesListRequest request) {
        return this.rawClient.list(projectId, request).body();
    }

    /**
     * Returns the original purchased amount on an order transaction
     */
    public ListProjectPurchasesV1Response list(
            String projectId, PurchasesListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(projectId, request, requestOptions).body();
    }
}
