/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.selfhosted.v1.distributioncredentials;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import resources.selfhosted.v1.distributioncredentials.requests.CreateProjectDistributionCredentialsV1Request;
import types.CreateProjectDistributionCredentialsV1Response;
import types.GetProjectDistributionCredentialsV1Response;
import types.ListProjectDistributionCredentialsV1Response;

public class AsyncDistributionCredentialsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawDistributionCredentialsClient rawClient;

  public AsyncDistributionCredentialsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawDistributionCredentialsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawDistributionCredentialsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Lists sets of distribution credentials for the specified project
   */
  public CompletableFuture<ListProjectDistributionCredentialsV1Response> list(String projectId) {
    return this.rawClient.list(projectId).thenApply(response -> response.body());
  }

  /**
   * Lists sets of distribution credentials for the specified project
   */
  public CompletableFuture<ListProjectDistributionCredentialsV1Response> list(String projectId,
      RequestOptions requestOptions) {
    return this.rawClient.list(projectId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a set of distribution credentials for the specified project
   */
  public CompletableFuture<CreateProjectDistributionCredentialsV1Response> create(
      String projectId) {
    return this.rawClient.create(projectId).thenApply(response -> response.body());
  }

  /**
   * Creates a set of distribution credentials for the specified project
   */
  public CompletableFuture<CreateProjectDistributionCredentialsV1Response> create(String projectId,
      CreateProjectDistributionCredentialsV1Request request) {
    return this.rawClient.create(projectId, request).thenApply(response -> response.body());
  }

  /**
   * Creates a set of distribution credentials for the specified project
   */
  public CompletableFuture<CreateProjectDistributionCredentialsV1Response> create(String projectId,
      CreateProjectDistributionCredentialsV1Request request, RequestOptions requestOptions) {
    return this.rawClient.create(projectId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a set of distribution credentials for the specified project
   */
  public CompletableFuture<GetProjectDistributionCredentialsV1Response> get(String projectId,
      String distributionCredentialsId) {
    return this.rawClient.get(projectId, distributionCredentialsId).thenApply(response -> response.body());
  }

  /**
   * Returns a set of distribution credentials for the specified project
   */
  public CompletableFuture<GetProjectDistributionCredentialsV1Response> get(String projectId,
      String distributionCredentialsId, RequestOptions requestOptions) {
    return this.rawClient.get(projectId, distributionCredentialsId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Deletes a set of distribution credentials for the specified project
   */
  public CompletableFuture<GetProjectDistributionCredentialsV1Response> delete(String projectId,
      String distributionCredentialsId) {
    return this.rawClient.delete(projectId, distributionCredentialsId).thenApply(response -> response.body());
  }

  /**
   * Deletes a set of distribution credentials for the specified project
   */
  public CompletableFuture<GetProjectDistributionCredentialsV1Response> delete(String projectId,
      String distributionCredentialsId, RequestOptions requestOptions) {
    return this.rawClient.delete(projectId, distributionCredentialsId, requestOptions).thenApply(response -> response.body());
  }
}
