/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.selfhosted.v1.distributioncredentials;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.DeepgramApiApiException;
import core.DeepgramApiException;
import core.DeepgramApiHttpResponse;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.BadRequestError;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.selfhosted.v1.distributioncredentials.requests.CreateProjectDistributionCredentialsV1Request;
import types.CreateProjectDistributionCredentialsV1Response;
import types.GetProjectDistributionCredentialsV1Response;
import types.ListProjectDistributionCredentialsV1Response;

public class RawDistributionCredentialsClient {
  protected final ClientOptions clientOptions;

  public RawDistributionCredentialsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Lists sets of distribution credentials for the specified project
   */
  public DeepgramApiHttpResponse<ListProjectDistributionCredentialsV1Response> list(
      String projectId) {
    return list(projectId,null);
  }

  /**
   * Lists sets of distribution credentials for the specified project
   */
  public DeepgramApiHttpResponse<ListProjectDistributionCredentialsV1Response> list(
      String projectId, RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

      .addPathSegments("v1/projects")
      .addPathSegment(projectId)
      .addPathSegments("self-hosted/distribution/credentials")
      .build();
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("GET", null)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Accept", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      if (response.isSuccessful()) {
        return new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), ListProjectDistributionCredentialsV1Response.class), response);
      }
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      try {
        if (response.code() == 400) {
          throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
        }
      }
      catch (JsonProcessingException ignored) {
        // unable to map error response, throwing generic error
      }
      throw new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
    }
    catch (IOException e) {
      throw new DeepgramApiException("Network error executing HTTP request", e);
    }
  }

  /**
   * Creates a set of distribution credentials for the specified project
   */
  public DeepgramApiHttpResponse<CreateProjectDistributionCredentialsV1Response> create(
      String projectId) {
    return create(projectId,CreateProjectDistributionCredentialsV1Request.builder().build());
  }

  /**
   * Creates a set of distribution credentials for the specified project
   */
  public DeepgramApiHttpResponse<CreateProjectDistributionCredentialsV1Response> create(
      String projectId, CreateProjectDistributionCredentialsV1Request request) {
    return create(projectId,request,null);
  }

  /**
   * Creates a set of distribution credentials for the specified project
   */
  public DeepgramApiHttpResponse<CreateProjectDistributionCredentialsV1Response> create(
      String projectId, CreateProjectDistributionCredentialsV1Request request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

      .addPathSegments("v1/projects")
      .addPathSegment(projectId)
      .addPathSegments("self-hosted/distribution/credentials");if (request.getProvider().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "provider", request.getProvider().get(), false);
      }
      if (request.getScopes().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "scopes", request.getScopes().get(), true);
      }
      Map<String, Object> properties = new HashMap<>();
      if (request.getComment().isPresent()) {
        properties.put("comment", request.getComment());
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateProjectDistributionCredentialsV1Response.class), response);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 400) {
            throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
      }
      catch (IOException e) {
        throw new DeepgramApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Returns a set of distribution credentials for the specified project
     */
    public DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response> get(
        String projectId, String distributionCredentialsId) {
      return get(projectId,distributionCredentialsId,null);
    }

    /**
     * Returns a set of distribution credentials for the specified project
     */
    public DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response> get(
        String projectId, String distributionCredentialsId, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

        .addPathSegments("v1/projects")
        .addPathSegment(projectId)
        .addPathSegments("self-hosted/distribution/credentials")
        .addPathSegment(distributionCredentialsId)
        .build();
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl)
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetProjectDistributionCredentialsV1Response.class), response);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 400) {
            throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
      }
      catch (IOException e) {
        throw new DeepgramApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Deletes a set of distribution credentials for the specified project
     */
    public DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response> delete(
        String projectId, String distributionCredentialsId) {
      return delete(projectId,distributionCredentialsId,null);
    }

    /**
     * Deletes a set of distribution credentials for the specified project
     */
    public DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response> delete(
        String projectId, String distributionCredentialsId, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

        .addPathSegments("v1/projects")
        .addPathSegment(projectId)
        .addPathSegments("self-hosted/distribution/credentials")
        .addPathSegment(distributionCredentialsId)
        .build();
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl)
        .method("DELETE", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetProjectDistributionCredentialsV1Response.class), response);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 400) {
            throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
      }
      catch (IOException e) {
        throw new DeepgramApiException("Network error executing HTTP request", e);
      }
    }
  }
