/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.types;

import com.deepgram.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentThinkModelsV1ResponseModelsItemOne.Builder.class)
public final class AgentThinkModelsV1ResponseModelsItemOne {
    private final AgentThinkModelsV1ResponseModelsItemOneId id;

    private final String name;

    private final Map<String, Object> additionalProperties;

    private AgentThinkModelsV1ResponseModelsItemOne(
            AgentThinkModelsV1ResponseModelsItemOneId id, String name, Map<String, Object> additionalProperties) {
        this.id = id;
        this.name = name;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier of the Anthropic model
     */
    @JsonProperty("id")
    public AgentThinkModelsV1ResponseModelsItemOneId getId() {
        return id;
    }

    /**
     * @return The display name of the model
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return The provider of the model
     */
    @JsonProperty("provider")
    public String getProvider() {
        return "anthropic";
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentThinkModelsV1ResponseModelsItemOne
                && equalTo((AgentThinkModelsV1ResponseModelsItemOne) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentThinkModelsV1ResponseModelsItemOne other) {
        return id.equals(other.id) && name.equals(other.name);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.name);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique identifier of the Anthropic model</p>
         */
        NameStage id(@NotNull AgentThinkModelsV1ResponseModelsItemOneId id);

        Builder from(AgentThinkModelsV1ResponseModelsItemOne other);
    }

    public interface NameStage {
        /**
         * <p>The display name of the model</p>
         */
        _FinalStage name(@NotNull String name);
    }

    public interface _FinalStage {
        AgentThinkModelsV1ResponseModelsItemOne build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, NameStage, _FinalStage {
        private AgentThinkModelsV1ResponseModelsItemOneId id;

        private String name;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AgentThinkModelsV1ResponseModelsItemOne other) {
            id(other.getId());
            name(other.getName());
            return this;
        }

        /**
         * <p>The unique identifier of the Anthropic model</p>
         * <p>The unique identifier of the Anthropic model</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull AgentThinkModelsV1ResponseModelsItemOneId id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The display name of the model</p>
         * <p>The display name of the model</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        public AgentThinkModelsV1ResponseModelsItemOne build() {
            return new AgentThinkModelsV1ResponseModelsItemOne(id, name, additionalProperties);
        }
    }
}
