/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class AgentThinkModelsV1ResponseModelsItemOneId {
  public static final AgentThinkModelsV1ResponseModelsItemOneId CLAUDE_35_HAIKU_LATEST = new AgentThinkModelsV1ResponseModelsItemOneId(Value.CLAUDE_35_HAIKU_LATEST, "claude-3-5-haiku-latest");

  public static final AgentThinkModelsV1ResponseModelsItemOneId CLAUDE_SONNET_420250514 = new AgentThinkModelsV1ResponseModelsItemOneId(Value.CLAUDE_SONNET_420250514, "claude-sonnet-4-20250514");

  private final Value value;

  private final String string;

  AgentThinkModelsV1ResponseModelsItemOneId(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof AgentThinkModelsV1ResponseModelsItemOneId && this.string.equals(((AgentThinkModelsV1ResponseModelsItemOneId) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CLAUDE_35_HAIKU_LATEST:
        return visitor.visitClaude35HaikuLatest();
      case CLAUDE_SONNET_420250514:
        return visitor.visitClaudeSonnet420250514();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static AgentThinkModelsV1ResponseModelsItemOneId valueOf(String value) {
    switch (value) {
      case "claude-3-5-haiku-latest":
        return CLAUDE_35_HAIKU_LATEST;
      case "claude-sonnet-4-20250514":
        return CLAUDE_SONNET_420250514;
      default:
        return new AgentThinkModelsV1ResponseModelsItemOneId(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CLAUDE_35_HAIKU_LATEST,

    CLAUDE_SONNET_420250514,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitClaude35HaikuLatest();

    T visitClaudeSonnet420250514();

    T visitUnknown(String unknownType);
  }
}
