/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateProjectDistributionCredentialsV1Response.Builder.class
)
public final class CreateProjectDistributionCredentialsV1Response {
  private final CreateProjectDistributionCredentialsV1ResponseMember member;

  private final CreateProjectDistributionCredentialsV1ResponseDistributionCredentials distributionCredentials;

  private final Map<String, Object> additionalProperties;

  private CreateProjectDistributionCredentialsV1Response(
      CreateProjectDistributionCredentialsV1ResponseMember member,
      CreateProjectDistributionCredentialsV1ResponseDistributionCredentials distributionCredentials,
      Map<String, Object> additionalProperties) {
    this.member = member;
    this.distributionCredentials = distributionCredentials;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("member")
  public CreateProjectDistributionCredentialsV1ResponseMember getMember() {
    return member;
  }

  @JsonProperty("distribution_credentials")
  public CreateProjectDistributionCredentialsV1ResponseDistributionCredentials getDistributionCredentials(
      ) {
    return distributionCredentials;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateProjectDistributionCredentialsV1Response && equalTo((CreateProjectDistributionCredentialsV1Response) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateProjectDistributionCredentialsV1Response other) {
    return member.equals(other.member) && distributionCredentials.equals(other.distributionCredentials);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.member, this.distributionCredentials);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MemberStage builder() {
    return new Builder();
  }

  public interface MemberStage {
    DistributionCredentialsStage member(
        @NotNull CreateProjectDistributionCredentialsV1ResponseMember member);

    Builder from(CreateProjectDistributionCredentialsV1Response other);
  }

  public interface DistributionCredentialsStage {
    _FinalStage distributionCredentials(
        @NotNull CreateProjectDistributionCredentialsV1ResponseDistributionCredentials distributionCredentials);
  }

  public interface _FinalStage {
    CreateProjectDistributionCredentialsV1Response build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MemberStage, DistributionCredentialsStage, _FinalStage {
    private CreateProjectDistributionCredentialsV1ResponseMember member;

    private CreateProjectDistributionCredentialsV1ResponseDistributionCredentials distributionCredentials;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateProjectDistributionCredentialsV1Response other) {
      member(other.getMember());
      distributionCredentials(other.getDistributionCredentials());
      return this;
    }

    @java.lang.Override
    @JsonSetter("member")
    public DistributionCredentialsStage member(
        @NotNull CreateProjectDistributionCredentialsV1ResponseMember member) {
      this.member = Objects.requireNonNull(member, "member must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("distribution_credentials")
    public _FinalStage distributionCredentials(
        @NotNull CreateProjectDistributionCredentialsV1ResponseDistributionCredentials distributionCredentials) {
      this.distributionCredentials = Objects.requireNonNull(distributionCredentials, "distributionCredentials must not be null");
      return this;
    }

    @java.lang.Override
    public CreateProjectDistributionCredentialsV1Response build() {
      return new CreateProjectDistributionCredentialsV1Response(member, distributionCredentials, additionalProperties);
    }
  }
}
