/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SharedTopicsResults.Builder.class
)
public final class SharedTopicsResults {
  private final Optional<SharedTopicsResultsTopics> topics;

  private final Map<String, Object> additionalProperties;

  private SharedTopicsResults(Optional<SharedTopicsResultsTopics> topics,
      Map<String, Object> additionalProperties) {
    this.topics = topics;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("topics")
  public Optional<SharedTopicsResultsTopics> getTopics() {
    return topics;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SharedTopicsResults && equalTo((SharedTopicsResults) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SharedTopicsResults other) {
    return topics.equals(other.topics);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.topics);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<SharedTopicsResultsTopics> topics = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(SharedTopicsResults other) {
      topics(other.getTopics());
      return this;
    }

    @JsonSetter(
        value = "topics",
        nulls = Nulls.SKIP
    )
    public Builder topics(Optional<SharedTopicsResultsTopics> topics) {
      this.topics = topics;
      return this;
    }

    public Builder topics(SharedTopicsResultsTopics topics) {
      this.topics = Optional.ofNullable(topics);
      return this;
    }

    public SharedTopicsResults build() {
      return new SharedTopicsResults(topics, additionalProperties);
    }
  }
}
