/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.resources.manage.v1.projects.billing.breakdown.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BreakdownListRequestDeployment {
    public static final BreakdownListRequestDeployment SELF_HOSTED =
            new BreakdownListRequestDeployment(Value.SELF_HOSTED, "self-hosted");

    public static final BreakdownListRequestDeployment BETA = new BreakdownListRequestDeployment(Value.BETA, "beta");

    public static final BreakdownListRequestDeployment HOSTED =
            new BreakdownListRequestDeployment(Value.HOSTED, "hosted");

    private final Value value;

    private final String string;

    BreakdownListRequestDeployment(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BreakdownListRequestDeployment
                        && this.string.equals(((BreakdownListRequestDeployment) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SELF_HOSTED:
                return visitor.visitSelfHosted();
            case BETA:
                return visitor.visitBeta();
            case HOSTED:
                return visitor.visitHosted();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BreakdownListRequestDeployment valueOf(String value) {
        switch (value) {
            case "self-hosted":
                return SELF_HOSTED;
            case "beta":
                return BETA;
            case "hosted":
                return HOSTED;
            default:
                return new BreakdownListRequestDeployment(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        HOSTED,

        BETA,

        SELF_HOSTED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitHosted();

        T visitBeta();

        T visitSelfHosted();

        T visitUnknown(String unknownType);
    }
}
