/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class DeepgramApiException extends RuntimeException {
    public DeepgramApiException(String message) {
        super(message);
    }

    public DeepgramApiException(String message, Exception e) {
        super(message, e);
    }
}
