/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.resources.manage.v1.projects.members.invites.requests;

import com.deepgram.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateProjectInviteV1Request.Builder.class)
public final class CreateProjectInviteV1Request {
    private final String email;

    private final String scope;

    private final Map<String, Object> additionalProperties;

    private CreateProjectInviteV1Request(String email, String scope, Map<String, Object> additionalProperties) {
        this.email = email;
        this.scope = scope;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The email address of the invitee
     */
    @JsonProperty("email")
    public String getEmail() {
        return email;
    }

    /**
     * @return The scope of the invitee
     */
    @JsonProperty("scope")
    public String getScope() {
        return scope;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateProjectInviteV1Request && equalTo((CreateProjectInviteV1Request) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateProjectInviteV1Request other) {
        return email.equals(other.email) && scope.equals(other.scope);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.email, this.scope);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EmailStage builder() {
        return new Builder();
    }

    public interface EmailStage {
        /**
         * <p>The email address of the invitee</p>
         */
        ScopeStage email(@NotNull String email);

        Builder from(CreateProjectInviteV1Request other);
    }

    public interface ScopeStage {
        /**
         * <p>The scope of the invitee</p>
         */
        _FinalStage scope(@NotNull String scope);
    }

    public interface _FinalStage {
        CreateProjectInviteV1Request build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EmailStage, ScopeStage, _FinalStage {
        private String email;

        private String scope;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateProjectInviteV1Request other) {
            email(other.getEmail());
            scope(other.getScope());
            return this;
        }

        /**
         * <p>The email address of the invitee</p>
         * <p>The email address of the invitee</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("email")
        public ScopeStage email(@NotNull String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        /**
         * <p>The scope of the invitee</p>
         * <p>The scope of the invitee</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("scope")
        public _FinalStage scope(@NotNull String scope) {
            this.scope = Objects.requireNonNull(scope, "scope must not be null");
            return this;
        }

        @java.lang.Override
        public CreateProjectInviteV1Request build() {
            return new CreateProjectInviteV1Request(email, scope, additionalProperties);
        }
    }
}
