/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.resources.auth.v1;

import com.deepgram.api.core.ClientOptions;
import com.deepgram.api.core.Suppliers;
import com.deepgram.api.resources.auth.v1.tokens.TokensClient;
import java.util.function.Supplier;

public class V1Client {
    protected final ClientOptions clientOptions;

    protected final Supplier<TokensClient> tokensClient;

    public V1Client(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.tokensClient = Suppliers.memoize(() -> new TokensClient(clientOptions));
    }

    public TokensClient tokens() {
        return this.tokensClient.get();
    }
}
