/** This file was auto-generated by Fern from our API Definition. */
package resources.speak.v1.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SpeakV1ClearedType {
  public static final SpeakV1ClearedType CLEARED = new SpeakV1ClearedType(Value.CLEARED, "Cleared");

  public static final SpeakV1ClearedType FLUSHED = new SpeakV1ClearedType(Value.FLUSHED, "Flushed");

  private final Value value;

  private final String string;

  SpeakV1ClearedType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other)
        || (other instanceof SpeakV1ClearedType
            && this.string.equals(((SpeakV1ClearedType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CLEARED:
        return visitor.visitCleared();
      case FLUSHED:
        return visitor.visitFlushed();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
  public static SpeakV1ClearedType valueOf(String value) {
    switch (value) {
      case "Cleared":
        return CLEARED;
      case "Flushed":
        return FLUSHED;
      default:
        return new SpeakV1ClearedType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    FLUSHED,

    CLEARED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitFlushed();

    T visitCleared();

    T visitUnknown(String unknownType);
  }
}
