/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.speak.v1.audio.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class AudioGenerateRequestModel {
  public static final AudioGenerateRequestModel AURA_ANGUS_EN = new AudioGenerateRequestModel(Value.AURA_ANGUS_EN, "aura-angus-en");

  public static final AudioGenerateRequestModel AURA_2_PLUTO_EN = new AudioGenerateRequestModel(Value.AURA_2_PLUTO_EN, "aura-2-pluto-en");

  public static final AudioGenerateRequestModel AURA_2_HERA_EN = new AudioGenerateRequestModel(Value.AURA_2_HERA_EN, "aura-2-hera-en");

  public static final AudioGenerateRequestModel AURA_2_ANDROMEDA_EN = new AudioGenerateRequestModel(Value.AURA_2_ANDROMEDA_EN, "aura-2-andromeda-en");

  public static final AudioGenerateRequestModel AURA_2_NEPTUNE_EN = new AudioGenerateRequestModel(Value.AURA_2_NEPTUNE_EN, "aura-2-neptune-en");

  public static final AudioGenerateRequestModel AURA_2_JANUS_EN = new AudioGenerateRequestModel(Value.AURA_2_JANUS_EN, "aura-2-janus-en");

  public static final AudioGenerateRequestModel AURA_2_DRACO_EN = new AudioGenerateRequestModel(Value.AURA_2_DRACO_EN, "aura-2-draco-en");

  public static final AudioGenerateRequestModel AURA_2_ESTRELLA_ES = new AudioGenerateRequestModel(Value.AURA_2_ESTRELLA_ES, "aura-2-estrella-es");

  public static final AudioGenerateRequestModel AURA_STELLA_EN = new AudioGenerateRequestModel(Value.AURA_STELLA_EN, "aura-stella-en");

  public static final AudioGenerateRequestModel AURA_2_SIRIO_ES = new AudioGenerateRequestModel(Value.AURA_2_SIRIO_ES, "aura-2-sirio-es");

  public static final AudioGenerateRequestModel AURA_2_CELESTE_ES = new AudioGenerateRequestModel(Value.AURA_2_CELESTE_ES, "aura-2-celeste-es");

  public static final AudioGenerateRequestModel AURA_2_CORDELIA_EN = new AudioGenerateRequestModel(Value.AURA_2_CORDELIA_EN, "aura-2-cordelia-en");

  public static final AudioGenerateRequestModel AURA_2_PANDORA_EN = new AudioGenerateRequestModel(Value.AURA_2_PANDORA_EN, "aura-2-pandora-en");

  public static final AudioGenerateRequestModel AURA_2_THEIA_EN = new AudioGenerateRequestModel(Value.AURA_2_THEIA_EN, "aura-2-theia-en");

  public static final AudioGenerateRequestModel AURA_2_HELENA_EN = new AudioGenerateRequestModel(Value.AURA_2_HELENA_EN, "aura-2-helena-en");

  public static final AudioGenerateRequestModel AURA_2_CALLISTA_EN = new AudioGenerateRequestModel(Value.AURA_2_CALLISTA_EN, "aura-2-callista-en");

  public static final AudioGenerateRequestModel AURA_2_MARS_EN = new AudioGenerateRequestModel(Value.AURA_2_MARS_EN, "aura-2-mars-en");

  public static final AudioGenerateRequestModel AURA_2_VESTA_EN = new AudioGenerateRequestModel(Value.AURA_2_VESTA_EN, "aura-2-vesta-en");

  public static final AudioGenerateRequestModel AURA_2_HARMONIA_EN = new AudioGenerateRequestModel(Value.AURA_2_HARMONIA_EN, "aura-2-harmonia-en");

  public static final AudioGenerateRequestModel AURA_HELIOS_EN = new AudioGenerateRequestModel(Value.AURA_HELIOS_EN, "aura-helios-en");

  public static final AudioGenerateRequestModel AURA_2_LUNA_EN = new AudioGenerateRequestModel(Value.AURA_2_LUNA_EN, "aura-2-luna-en");

  public static final AudioGenerateRequestModel AURA_2_JUNO_EN = new AudioGenerateRequestModel(Value.AURA_2_JUNO_EN, "aura-2-juno-en");

  public static final AudioGenerateRequestModel AURA_ATHENA_EN = new AudioGenerateRequestModel(Value.AURA_ATHENA_EN, "aura-athena-en");

  public static final AudioGenerateRequestModel AURA_PERSEUS_EN = new AudioGenerateRequestModel(Value.AURA_PERSEUS_EN, "aura-perseus-en");

  public static final AudioGenerateRequestModel AURA_2_ATLAS_EN = new AudioGenerateRequestModel(Value.AURA_2_ATLAS_EN, "aura-2-atlas-en");

  public static final AudioGenerateRequestModel AURA_2_THALIA_EN = new AudioGenerateRequestModel(Value.AURA_2_THALIA_EN, "aura-2-thalia-en");

  public static final AudioGenerateRequestModel AURA_2_IRIS_EN = new AudioGenerateRequestModel(Value.AURA_2_IRIS_EN, "aura-2-iris-en");

  public static final AudioGenerateRequestModel AURA_2_ALVARO_ES = new AudioGenerateRequestModel(Value.AURA_2_ALVARO_ES, "aura-2-alvaro-es");

  public static final AudioGenerateRequestModel AURA_ASTERIA_EN = new AudioGenerateRequestModel(Value.AURA_ASTERIA_EN, "aura-asteria-en");

  public static final AudioGenerateRequestModel AURA_2_NESTOR_ES = new AudioGenerateRequestModel(Value.AURA_2_NESTOR_ES, "aura-2-nestor-es");

  public static final AudioGenerateRequestModel AURA_2_ARIES_EN = new AudioGenerateRequestModel(Value.AURA_2_ARIES_EN, "aura-2-aries-en");

  public static final AudioGenerateRequestModel AURA_2_SELENA_ES = new AudioGenerateRequestModel(Value.AURA_2_SELENA_ES, "aura-2-selena-es");

  public static final AudioGenerateRequestModel AURA_2_HERMES_EN = new AudioGenerateRequestModel(Value.AURA_2_HERMES_EN, "aura-2-hermes-en");

  public static final AudioGenerateRequestModel AURA_2_JAVIER_ES = new AudioGenerateRequestModel(Value.AURA_2_JAVIER_ES, "aura-2-javier-es");

  public static final AudioGenerateRequestModel AURA_2_CARINA_ES = new AudioGenerateRequestModel(Value.AURA_2_CARINA_ES, "aura-2-carina-es");

  public static final AudioGenerateRequestModel AURA_2_ARCAS_EN = new AudioGenerateRequestModel(Value.AURA_2_ARCAS_EN, "aura-2-arcas-en");

  public static final AudioGenerateRequestModel AURA_2_AURORA_EN = new AudioGenerateRequestModel(Value.AURA_2_AURORA_EN, "aura-2-aurora-en");

  public static final AudioGenerateRequestModel AURA_2_SATURN_EN = new AudioGenerateRequestModel(Value.AURA_2_SATURN_EN, "aura-2-saturn-en");

  public static final AudioGenerateRequestModel AURA_2_MINERVA_EN = new AudioGenerateRequestModel(Value.AURA_2_MINERVA_EN, "aura-2-minerva-en");

  public static final AudioGenerateRequestModel AURA_ZEUS_EN = new AudioGenerateRequestModel(Value.AURA_ZEUS_EN, "aura-zeus-en");

  public static final AudioGenerateRequestModel AURA_2_APOLLO_EN = new AudioGenerateRequestModel(Value.AURA_2_APOLLO_EN, "aura-2-apollo-en");

  public static final AudioGenerateRequestModel AURA_2_CORA_EN = new AudioGenerateRequestModel(Value.AURA_2_CORA_EN, "aura-2-cora-en");

  public static final AudioGenerateRequestModel AURA_ORPHEUS_EN = new AudioGenerateRequestModel(Value.AURA_ORPHEUS_EN, "aura-orpheus-en");

  public static final AudioGenerateRequestModel AURA_2_ORPHEUS_EN = new AudioGenerateRequestModel(Value.AURA_2_ORPHEUS_EN, "aura-2-orpheus-en");

  public static final AudioGenerateRequestModel AURA_LUNA_EN = new AudioGenerateRequestModel(Value.AURA_LUNA_EN, "aura-luna-en");

  public static final AudioGenerateRequestModel AURA_2_DIANA_ES = new AudioGenerateRequestModel(Value.AURA_2_DIANA_ES, "aura-2-diana-es");

  public static final AudioGenerateRequestModel AURA_2_ASTERIA_EN = new AudioGenerateRequestModel(Value.AURA_2_ASTERIA_EN, "aura-2-asteria-en");

  public static final AudioGenerateRequestModel AURA_2_JUPITER_EN = new AudioGenerateRequestModel(Value.AURA_2_JUPITER_EN, "aura-2-jupiter-en");

  public static final AudioGenerateRequestModel AURA_2_AQUILA_ES = new AudioGenerateRequestModel(Value.AURA_2_AQUILA_ES, "aura-2-aquila-es");

  public static final AudioGenerateRequestModel AURA_HERA_EN = new AudioGenerateRequestModel(Value.AURA_HERA_EN, "aura-hera-en");

  public static final AudioGenerateRequestModel AURA_2_PHOEBE_EN = new AudioGenerateRequestModel(Value.AURA_2_PHOEBE_EN, "aura-2-phoebe-en");

  public static final AudioGenerateRequestModel AURA_2_ELECTRA_EN = new AudioGenerateRequestModel(Value.AURA_2_ELECTRA_EN, "aura-2-electra-en");

  public static final AudioGenerateRequestModel AURA_2_ODYSSEUS_EN = new AudioGenerateRequestModel(Value.AURA_2_ODYSSEUS_EN, "aura-2-odysseus-en");

  public static final AudioGenerateRequestModel AURA_2_AMALTHEA_EN = new AudioGenerateRequestModel(Value.AURA_2_AMALTHEA_EN, "aura-2-amalthea-en");

  public static final AudioGenerateRequestModel AURA_2_ATHENA_EN = new AudioGenerateRequestModel(Value.AURA_2_ATHENA_EN, "aura-2-athena-en");

  public static final AudioGenerateRequestModel AURA_2_SELENE_EN = new AudioGenerateRequestModel(Value.AURA_2_SELENE_EN, "aura-2-selene-en");

  public static final AudioGenerateRequestModel AURA_2_DELIA_EN = new AudioGenerateRequestModel(Value.AURA_2_DELIA_EN, "aura-2-delia-en");

  public static final AudioGenerateRequestModel AURA_2_OPHELIA_EN = new AudioGenerateRequestModel(Value.AURA_2_OPHELIA_EN, "aura-2-ophelia-en");

  public static final AudioGenerateRequestModel AURA_2_ZEUS_EN = new AudioGenerateRequestModel(Value.AURA_2_ZEUS_EN, "aura-2-zeus-en");

  public static final AudioGenerateRequestModel AURA_2_HYPERION_EN = new AudioGenerateRequestModel(Value.AURA_2_HYPERION_EN, "aura-2-hyperion-en");

  public static final AudioGenerateRequestModel AURA_2_ORION_EN = new AudioGenerateRequestModel(Value.AURA_2_ORION_EN, "aura-2-orion-en");

  public static final AudioGenerateRequestModel AURA_ORION_EN = new AudioGenerateRequestModel(Value.AURA_ORION_EN, "aura-orion-en");

  public static final AudioGenerateRequestModel AURA_ARCAS_EN = new AudioGenerateRequestModel(Value.AURA_ARCAS_EN, "aura-arcas-en");

  private final Value value;

  private final String string;

  AudioGenerateRequestModel(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof AudioGenerateRequestModel && this.string.equals(((AudioGenerateRequestModel) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case AURA_ANGUS_EN:
        return visitor.visitAuraAngusEn();
      case AURA_2_PLUTO_EN:
        return visitor.visitAura2PlutoEn();
      case AURA_2_HERA_EN:
        return visitor.visitAura2HeraEn();
      case AURA_2_ANDROMEDA_EN:
        return visitor.visitAura2AndromedaEn();
      case AURA_2_NEPTUNE_EN:
        return visitor.visitAura2NeptuneEn();
      case AURA_2_JANUS_EN:
        return visitor.visitAura2JanusEn();
      case AURA_2_DRACO_EN:
        return visitor.visitAura2DracoEn();
      case AURA_2_ESTRELLA_ES:
        return visitor.visitAura2EstrellaEs();
      case AURA_STELLA_EN:
        return visitor.visitAuraStellaEn();
      case AURA_2_SIRIO_ES:
        return visitor.visitAura2SirioEs();
      case AURA_2_CELESTE_ES:
        return visitor.visitAura2CelesteEs();
      case AURA_2_CORDELIA_EN:
        return visitor.visitAura2CordeliaEn();
      case AURA_2_PANDORA_EN:
        return visitor.visitAura2PandoraEn();
      case AURA_2_THEIA_EN:
        return visitor.visitAura2TheiaEn();
      case AURA_2_HELENA_EN:
        return visitor.visitAura2HelenaEn();
      case AURA_2_CALLISTA_EN:
        return visitor.visitAura2CallistaEn();
      case AURA_2_MARS_EN:
        return visitor.visitAura2MarsEn();
      case AURA_2_VESTA_EN:
        return visitor.visitAura2VestaEn();
      case AURA_2_HARMONIA_EN:
        return visitor.visitAura2HarmoniaEn();
      case AURA_HELIOS_EN:
        return visitor.visitAuraHeliosEn();
      case AURA_2_LUNA_EN:
        return visitor.visitAura2LunaEn();
      case AURA_2_JUNO_EN:
        return visitor.visitAura2JunoEn();
      case AURA_ATHENA_EN:
        return visitor.visitAuraAthenaEn();
      case AURA_PERSEUS_EN:
        return visitor.visitAuraPerseusEn();
      case AURA_2_ATLAS_EN:
        return visitor.visitAura2AtlasEn();
      case AURA_2_THALIA_EN:
        return visitor.visitAura2ThaliaEn();
      case AURA_2_IRIS_EN:
        return visitor.visitAura2IrisEn();
      case AURA_2_ALVARO_ES:
        return visitor.visitAura2AlvaroEs();
      case AURA_ASTERIA_EN:
        return visitor.visitAuraAsteriaEn();
      case AURA_2_NESTOR_ES:
        return visitor.visitAura2NestorEs();
      case AURA_2_ARIES_EN:
        return visitor.visitAura2AriesEn();
      case AURA_2_SELENA_ES:
        return visitor.visitAura2SelenaEs();
      case AURA_2_HERMES_EN:
        return visitor.visitAura2HermesEn();
      case AURA_2_JAVIER_ES:
        return visitor.visitAura2JavierEs();
      case AURA_2_CARINA_ES:
        return visitor.visitAura2CarinaEs();
      case AURA_2_ARCAS_EN:
        return visitor.visitAura2ArcasEn();
      case AURA_2_AURORA_EN:
        return visitor.visitAura2AuroraEn();
      case AURA_2_SATURN_EN:
        return visitor.visitAura2SaturnEn();
      case AURA_2_MINERVA_EN:
        return visitor.visitAura2MinervaEn();
      case AURA_ZEUS_EN:
        return visitor.visitAuraZeusEn();
      case AURA_2_APOLLO_EN:
        return visitor.visitAura2ApolloEn();
      case AURA_2_CORA_EN:
        return visitor.visitAura2CoraEn();
      case AURA_ORPHEUS_EN:
        return visitor.visitAuraOrpheusEn();
      case AURA_2_ORPHEUS_EN:
        return visitor.visitAura2OrpheusEn();
      case AURA_LUNA_EN:
        return visitor.visitAuraLunaEn();
      case AURA_2_DIANA_ES:
        return visitor.visitAura2DianaEs();
      case AURA_2_ASTERIA_EN:
        return visitor.visitAura2AsteriaEn();
      case AURA_2_JUPITER_EN:
        return visitor.visitAura2JupiterEn();
      case AURA_2_AQUILA_ES:
        return visitor.visitAura2AquilaEs();
      case AURA_HERA_EN:
        return visitor.visitAuraHeraEn();
      case AURA_2_PHOEBE_EN:
        return visitor.visitAura2PhoebeEn();
      case AURA_2_ELECTRA_EN:
        return visitor.visitAura2ElectraEn();
      case AURA_2_ODYSSEUS_EN:
        return visitor.visitAura2OdysseusEn();
      case AURA_2_AMALTHEA_EN:
        return visitor.visitAura2AmaltheaEn();
      case AURA_2_ATHENA_EN:
        return visitor.visitAura2AthenaEn();
      case AURA_2_SELENE_EN:
        return visitor.visitAura2SeleneEn();
      case AURA_2_DELIA_EN:
        return visitor.visitAura2DeliaEn();
      case AURA_2_OPHELIA_EN:
        return visitor.visitAura2OpheliaEn();
      case AURA_2_ZEUS_EN:
        return visitor.visitAura2ZeusEn();
      case AURA_2_HYPERION_EN:
        return visitor.visitAura2HyperionEn();
      case AURA_2_ORION_EN:
        return visitor.visitAura2OrionEn();
      case AURA_ORION_EN:
        return visitor.visitAuraOrionEn();
      case AURA_ARCAS_EN:
        return visitor.visitAuraArcasEn();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static AudioGenerateRequestModel valueOf(String value) {
    switch (value) {
      case "aura-angus-en":
        return AURA_ANGUS_EN;
      case "aura-2-pluto-en":
        return AURA_2_PLUTO_EN;
      case "aura-2-hera-en":
        return AURA_2_HERA_EN;
      case "aura-2-andromeda-en":
        return AURA_2_ANDROMEDA_EN;
      case "aura-2-neptune-en":
        return AURA_2_NEPTUNE_EN;
      case "aura-2-janus-en":
        return AURA_2_JANUS_EN;
      case "aura-2-draco-en":
        return AURA_2_DRACO_EN;
      case "aura-2-estrella-es":
        return AURA_2_ESTRELLA_ES;
      case "aura-stella-en":
        return AURA_STELLA_EN;
      case "aura-2-sirio-es":
        return AURA_2_SIRIO_ES;
      case "aura-2-celeste-es":
        return AURA_2_CELESTE_ES;
      case "aura-2-cordelia-en":
        return AURA_2_CORDELIA_EN;
      case "aura-2-pandora-en":
        return AURA_2_PANDORA_EN;
      case "aura-2-theia-en":
        return AURA_2_THEIA_EN;
      case "aura-2-helena-en":
        return AURA_2_HELENA_EN;
      case "aura-2-callista-en":
        return AURA_2_CALLISTA_EN;
      case "aura-2-mars-en":
        return AURA_2_MARS_EN;
      case "aura-2-vesta-en":
        return AURA_2_VESTA_EN;
      case "aura-2-harmonia-en":
        return AURA_2_HARMONIA_EN;
      case "aura-helios-en":
        return AURA_HELIOS_EN;
      case "aura-2-luna-en":
        return AURA_2_LUNA_EN;
      case "aura-2-juno-en":
        return AURA_2_JUNO_EN;
      case "aura-athena-en":
        return AURA_ATHENA_EN;
      case "aura-perseus-en":
        return AURA_PERSEUS_EN;
      case "aura-2-atlas-en":
        return AURA_2_ATLAS_EN;
      case "aura-2-thalia-en":
        return AURA_2_THALIA_EN;
      case "aura-2-iris-en":
        return AURA_2_IRIS_EN;
      case "aura-2-alvaro-es":
        return AURA_2_ALVARO_ES;
      case "aura-asteria-en":
        return AURA_ASTERIA_EN;
      case "aura-2-nestor-es":
        return AURA_2_NESTOR_ES;
      case "aura-2-aries-en":
        return AURA_2_ARIES_EN;
      case "aura-2-selena-es":
        return AURA_2_SELENA_ES;
      case "aura-2-hermes-en":
        return AURA_2_HERMES_EN;
      case "aura-2-javier-es":
        return AURA_2_JAVIER_ES;
      case "aura-2-carina-es":
        return AURA_2_CARINA_ES;
      case "aura-2-arcas-en":
        return AURA_2_ARCAS_EN;
      case "aura-2-aurora-en":
        return AURA_2_AURORA_EN;
      case "aura-2-saturn-en":
        return AURA_2_SATURN_EN;
      case "aura-2-minerva-en":
        return AURA_2_MINERVA_EN;
      case "aura-zeus-en":
        return AURA_ZEUS_EN;
      case "aura-2-apollo-en":
        return AURA_2_APOLLO_EN;
      case "aura-2-cora-en":
        return AURA_2_CORA_EN;
      case "aura-orpheus-en":
        return AURA_ORPHEUS_EN;
      case "aura-2-orpheus-en":
        return AURA_2_ORPHEUS_EN;
      case "aura-luna-en":
        return AURA_LUNA_EN;
      case "aura-2-diana-es":
        return AURA_2_DIANA_ES;
      case "aura-2-asteria-en":
        return AURA_2_ASTERIA_EN;
      case "aura-2-jupiter-en":
        return AURA_2_JUPITER_EN;
      case "aura-2-aquila-es":
        return AURA_2_AQUILA_ES;
      case "aura-hera-en":
        return AURA_HERA_EN;
      case "aura-2-phoebe-en":
        return AURA_2_PHOEBE_EN;
      case "aura-2-electra-en":
        return AURA_2_ELECTRA_EN;
      case "aura-2-odysseus-en":
        return AURA_2_ODYSSEUS_EN;
      case "aura-2-amalthea-en":
        return AURA_2_AMALTHEA_EN;
      case "aura-2-athena-en":
        return AURA_2_ATHENA_EN;
      case "aura-2-selene-en":
        return AURA_2_SELENE_EN;
      case "aura-2-delia-en":
        return AURA_2_DELIA_EN;
      case "aura-2-ophelia-en":
        return AURA_2_OPHELIA_EN;
      case "aura-2-zeus-en":
        return AURA_2_ZEUS_EN;
      case "aura-2-hyperion-en":
        return AURA_2_HYPERION_EN;
      case "aura-2-orion-en":
        return AURA_2_ORION_EN;
      case "aura-orion-en":
        return AURA_ORION_EN;
      case "aura-arcas-en":
        return AURA_ARCAS_EN;
      default:
        return new AudioGenerateRequestModel(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    AURA_ASTERIA_EN,

    AURA_LUNA_EN,

    AURA_STELLA_EN,

    AURA_ATHENA_EN,

    AURA_HERA_EN,

    AURA_ORION_EN,

    AURA_ARCAS_EN,

    AURA_PERSEUS_EN,

    AURA_ANGUS_EN,

    AURA_ORPHEUS_EN,

    AURA_HELIOS_EN,

    AURA_ZEUS_EN,

    AURA_2_AMALTHEA_EN,

    AURA_2_ANDROMEDA_EN,

    AURA_2_APOLLO_EN,

    AURA_2_ARCAS_EN,

    AURA_2_ARIES_EN,

    AURA_2_ASTERIA_EN,

    AURA_2_ATHENA_EN,

    AURA_2_ATLAS_EN,

    AURA_2_AURORA_EN,

    AURA_2_CALLISTA_EN,

    AURA_2_CORDELIA_EN,

    AURA_2_CORA_EN,

    AURA_2_DELIA_EN,

    AURA_2_DRACO_EN,

    AURA_2_ELECTRA_EN,

    AURA_2_HARMONIA_EN,

    AURA_2_HELENA_EN,

    AURA_2_HERA_EN,

    AURA_2_HERMES_EN,

    AURA_2_HYPERION_EN,

    AURA_2_IRIS_EN,

    AURA_2_JANUS_EN,

    AURA_2_JUNO_EN,

    AURA_2_JUPITER_EN,

    AURA_2_LUNA_EN,

    AURA_2_MARS_EN,

    AURA_2_MINERVA_EN,

    AURA_2_NEPTUNE_EN,

    AURA_2_ODYSSEUS_EN,

    AURA_2_OPHELIA_EN,

    AURA_2_ORION_EN,

    AURA_2_ORPHEUS_EN,

    AURA_2_PANDORA_EN,

    AURA_2_PHOEBE_EN,

    AURA_2_PLUTO_EN,

    AURA_2_SATURN_EN,

    AURA_2_SELENE_EN,

    AURA_2_THALIA_EN,

    AURA_2_THEIA_EN,

    AURA_2_VESTA_EN,

    AURA_2_ZEUS_EN,

    AURA_2_SIRIO_ES,

    AURA_2_NESTOR_ES,

    AURA_2_CARINA_ES,

    AURA_2_CELESTE_ES,

    AURA_2_ALVARO_ES,

    AURA_2_DIANA_ES,

    AURA_2_AQUILA_ES,

    AURA_2_SELENA_ES,

    AURA_2_ESTRELLA_ES,

    AURA_2_JAVIER_ES,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitAuraAsteriaEn();

    T visitAuraLunaEn();

    T visitAuraStellaEn();

    T visitAuraAthenaEn();

    T visitAuraHeraEn();

    T visitAuraOrionEn();

    T visitAuraArcasEn();

    T visitAuraPerseusEn();

    T visitAuraAngusEn();

    T visitAuraOrpheusEn();

    T visitAuraHeliosEn();

    T visitAuraZeusEn();

    T visitAura2AmaltheaEn();

    T visitAura2AndromedaEn();

    T visitAura2ApolloEn();

    T visitAura2ArcasEn();

    T visitAura2AriesEn();

    T visitAura2AsteriaEn();

    T visitAura2AthenaEn();

    T visitAura2AtlasEn();

    T visitAura2AuroraEn();

    T visitAura2CallistaEn();

    T visitAura2CordeliaEn();

    T visitAura2CoraEn();

    T visitAura2DeliaEn();

    T visitAura2DracoEn();

    T visitAura2ElectraEn();

    T visitAura2HarmoniaEn();

    T visitAura2HelenaEn();

    T visitAura2HeraEn();

    T visitAura2HermesEn();

    T visitAura2HyperionEn();

    T visitAura2IrisEn();

    T visitAura2JanusEn();

    T visitAura2JunoEn();

    T visitAura2JupiterEn();

    T visitAura2LunaEn();

    T visitAura2MarsEn();

    T visitAura2MinervaEn();

    T visitAura2NeptuneEn();

    T visitAura2OdysseusEn();

    T visitAura2OpheliaEn();

    T visitAura2OrionEn();

    T visitAura2OrpheusEn();

    T visitAura2PandoraEn();

    T visitAura2PhoebeEn();

    T visitAura2PlutoEn();

    T visitAura2SaturnEn();

    T visitAura2SeleneEn();

    T visitAura2ThaliaEn();

    T visitAura2TheiaEn();

    T visitAura2VestaEn();

    T visitAura2ZeusEn();

    T visitAura2SirioEs();

    T visitAura2NestorEs();

    T visitAura2CarinaEs();

    T visitAura2CelesteEs();

    T visitAura2AlvaroEs();

    T visitAura2DianaEs();

    T visitAura2AquilaEs();

    T visitAura2SelenaEs();

    T visitAura2EstrellaEs();

    T visitAura2JavierEs();

    T visitUnknown(String unknownType);
  }
}
