/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.manage.v1.projects;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.DeepgramApiApiException;
import core.DeepgramApiException;
import core.DeepgramApiHttpResponse;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.BadRequestError;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.manage.v1.projects.requests.ProjectsGetRequest;
import resources.manage.v1.projects.requests.UpdateProjectV1Request;
import types.DeleteProjectV1Response;
import types.GetProjectV1Response;
import types.LeaveProjectV1Response;
import types.ListProjectsV1Response;
import types.UpdateProjectV1Response;

public class AsyncRawProjectsClient {
  protected final ClientOptions clientOptions;

  public AsyncRawProjectsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Retrieves basic information about the projects associated with the API key
   */
  public CompletableFuture<DeepgramApiHttpResponse<ListProjectsV1Response>> list() {
    return list(null);
  }

  /**
   * Retrieves basic information about the projects associated with the API key
   */
  public CompletableFuture<DeepgramApiHttpResponse<ListProjectsV1Response>> list(
      RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

      .addPathSegments("v1/projects")
      .build();
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("GET", null)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Accept", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    CompletableFuture<DeepgramApiHttpResponse<ListProjectsV1Response>> future = new CompletableFuture<>();
    client.newCall(okhttpRequest).enqueue(new Callback() {
      @Override
      public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
        try (ResponseBody responseBody = response.body()) {
          if (response.isSuccessful()) {
            future.complete(new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), ListProjectsV1Response.class), response));
            return;
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 400) {
              future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
              return;
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          future.completeExceptionally(new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
          return;
        }
        catch (IOException e) {
          future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
        }
      }

      @Override
      public void onFailure(@NotNull Call call, @NotNull IOException e) {
        future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
      }
    });
    return future;
  }

  /**
   * Retrieves information about the specified project
   */
  public CompletableFuture<DeepgramApiHttpResponse<GetProjectV1Response>> get(String projectId) {
    return get(projectId,ProjectsGetRequest.builder().build());
  }

  /**
   * Retrieves information about the specified project
   */
  public CompletableFuture<DeepgramApiHttpResponse<GetProjectV1Response>> get(String projectId,
      ProjectsGetRequest request) {
    return get(projectId,request,null);
  }

  /**
   * Retrieves information about the specified project
   */
  public CompletableFuture<DeepgramApiHttpResponse<GetProjectV1Response>> get(String projectId,
      ProjectsGetRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

      .addPathSegments("v1/projects")
      .addPathSegment(projectId);if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (request.getPage().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<DeepgramApiHttpResponse<GetProjectV1Response>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetProjectV1Response.class), response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 400) {
                future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Deletes the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<DeleteProjectV1Response>> delete(
        String projectId) {
      return delete(projectId,null);
    }

    /**
     * Deletes the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<DeleteProjectV1Response>> delete(
        String projectId, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

        .addPathSegments("v1/projects")
        .addPathSegment(projectId)
        .build();
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl)
        .method("DELETE", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<DeepgramApiHttpResponse<DeleteProjectV1Response>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), DeleteProjectV1Response.class), response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 400) {
                future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Updates the name or other properties of an existing project
     */
    public CompletableFuture<DeepgramApiHttpResponse<UpdateProjectV1Response>> update(
        String projectId) {
      return update(projectId,UpdateProjectV1Request.builder().build());
    }

    /**
     * Updates the name or other properties of an existing project
     */
    public CompletableFuture<DeepgramApiHttpResponse<UpdateProjectV1Response>> update(
        String projectId, UpdateProjectV1Request request) {
      return update(projectId,request,null);
    }

    /**
     * Updates the name or other properties of an existing project
     */
    public CompletableFuture<DeepgramApiHttpResponse<UpdateProjectV1Response>> update(
        String projectId, UpdateProjectV1Request request, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

        .addPathSegments("v1/projects")
        .addPathSegment(projectId)
        .build();
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(JsonProcessingException e) {
        throw new DeepgramApiException("Failed to serialize request", e);
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl)
        .method("PATCH", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<DeepgramApiHttpResponse<UpdateProjectV1Response>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), UpdateProjectV1Response.class), response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 400) {
                future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Removes the authenticated account from the specific project
     */
    public CompletableFuture<DeepgramApiHttpResponse<LeaveProjectV1Response>> leave(
        String projectId) {
      return leave(projectId,null);
    }

    /**
     * Removes the authenticated account from the specific project
     */
    public CompletableFuture<DeepgramApiHttpResponse<LeaveProjectV1Response>> leave(
        String projectId, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

        .addPathSegments("v1/projects")
        .addPathSegment(projectId)
        .addPathSegments("leave")
        .build();
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl)
        .method("DELETE", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<DeepgramApiHttpResponse<LeaveProjectV1Response>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), LeaveProjectV1Response.class), response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 400) {
                future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }
  }
