/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.resources.manage.v1.projects.billing;

import com.deepgram.api.core.ClientOptions;
import com.deepgram.api.core.Suppliers;
import com.deepgram.api.resources.manage.v1.projects.billing.balances.BalancesClient;
import com.deepgram.api.resources.manage.v1.projects.billing.breakdown.BreakdownClient;
import com.deepgram.api.resources.manage.v1.projects.billing.fields.FieldsClient;
import com.deepgram.api.resources.manage.v1.projects.billing.purchases.PurchasesClient;
import java.util.function.Supplier;

public class BillingClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<BalancesClient> balancesClient;

    protected final Supplier<BreakdownClient> breakdownClient;

    protected final Supplier<FieldsClient> fieldsClient;

    protected final Supplier<PurchasesClient> purchasesClient;

    public BillingClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.balancesClient = Suppliers.memoize(() -> new BalancesClient(clientOptions));
        this.breakdownClient = Suppliers.memoize(() -> new BreakdownClient(clientOptions));
        this.fieldsClient = Suppliers.memoize(() -> new FieldsClient(clientOptions));
        this.purchasesClient = Suppliers.memoize(() -> new PurchasesClient(clientOptions));
    }

    public BalancesClient balances() {
        return this.balancesClient.get();
    }

    public BreakdownClient breakdown() {
        return this.breakdownClient.get();
    }

    public FieldsClient fields() {
        return this.fieldsClient.get();
    }

    public PurchasesClient purchases() {
        return this.purchasesClient.get();
    }
}
