/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AgentV1SettingsAgentContextContextMessagesItemContentRole {
    public static final AgentV1SettingsAgentContextContextMessagesItemContentRole USER =
            new AgentV1SettingsAgentContextContextMessagesItemContentRole(Value.USER, "user");

    public static final AgentV1SettingsAgentContextContextMessagesItemContentRole ASSISTANT =
            new AgentV1SettingsAgentContextContextMessagesItemContentRole(Value.ASSISTANT, "assistant");

    private final Value value;

    private final String string;

    AgentV1SettingsAgentContextContextMessagesItemContentRole(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AgentV1SettingsAgentContextContextMessagesItemContentRole
                        && this.string.equals(
                                ((AgentV1SettingsAgentContextContextMessagesItemContentRole) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case USER:
                return visitor.visitUser();
            case ASSISTANT:
                return visitor.visitAssistant();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AgentV1SettingsAgentContextContextMessagesItemContentRole valueOf(String value) {
        switch (value) {
            case "user":
                return USER;
            case "assistant":
                return ASSISTANT;
            default:
                return new AgentV1SettingsAgentContextContextMessagesItemContentRole(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        USER,

        ASSISTANT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUser();

        T visitAssistant();

        T visitUnknown(String unknownType);
    }
}
