/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class AgentV1SettingsAgentSpeakOneItemProvider {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private AgentV1SettingsAgentSpeakOneItemProvider(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static AgentV1SettingsAgentSpeakOneItemProvider deepgram(Deepgram value) {
        return new AgentV1SettingsAgentSpeakOneItemProvider(new DeepgramValue(value));
    }

    public static AgentV1SettingsAgentSpeakOneItemProvider elevenLabs(ElevenLabs value) {
        return new AgentV1SettingsAgentSpeakOneItemProvider(new ElevenLabsValue(value));
    }

    public static AgentV1SettingsAgentSpeakOneItemProvider cartesia(Cartesia value) {
        return new AgentV1SettingsAgentSpeakOneItemProvider(new CartesiaValue(value));
    }

    public static AgentV1SettingsAgentSpeakOneItemProvider openAi(
            AgentV1SettingsAgentSpeakOneItemProviderOpenAi value) {
        return new AgentV1SettingsAgentSpeakOneItemProvider(new OpenAiValue(value));
    }

    public static AgentV1SettingsAgentSpeakOneItemProvider awsPolly(
            AgentV1SettingsAgentSpeakOneItemProviderAwsPolly value) {
        return new AgentV1SettingsAgentSpeakOneItemProvider(new AwsPollyValue(value));
    }

    public boolean isDeepgram() {
        return value instanceof DeepgramValue;
    }

    public boolean isElevenLabs() {
        return value instanceof ElevenLabsValue;
    }

    public boolean isCartesia() {
        return value instanceof CartesiaValue;
    }

    public boolean isOpenAi() {
        return value instanceof OpenAiValue;
    }

    public boolean isAwsPolly() {
        return value instanceof AwsPollyValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<Deepgram> getDeepgram() {
        if (isDeepgram()) {
            return Optional.of(((DeepgramValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<ElevenLabs> getElevenLabs() {
        if (isElevenLabs()) {
            return Optional.of(((ElevenLabsValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Cartesia> getCartesia() {
        if (isCartesia()) {
            return Optional.of(((CartesiaValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AgentV1SettingsAgentSpeakOneItemProviderOpenAi> getOpenAi() {
        if (isOpenAi()) {
            return Optional.of(((OpenAiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AgentV1SettingsAgentSpeakOneItemProviderAwsPolly> getAwsPolly() {
        if (isAwsPolly()) {
            return Optional.of(((AwsPollyValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentV1SettingsAgentSpeakOneItemProvider
                && value.equals(((AgentV1SettingsAgentSpeakOneItemProvider) other).value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public String toString() {
        return value.toString();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitDeepgram(Deepgram deepgram);

        T visitElevenLabs(ElevenLabs elevenLabs);

        T visitCartesia(Cartesia cartesia);

        T visitOpenAi(AgentV1SettingsAgentSpeakOneItemProviderOpenAi openAi);

        T visitAwsPolly(AgentV1SettingsAgentSpeakOneItemProviderAwsPolly awsPolly);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({
        @JsonSubTypes.Type(DeepgramValue.class),
        @JsonSubTypes.Type(ElevenLabsValue.class),
        @JsonSubTypes.Type(CartesiaValue.class),
        @JsonSubTypes.Type(OpenAiValue.class),
        @JsonSubTypes.Type(AwsPollyValue.class)
    })
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("deepgram")
    @JsonIgnoreProperties("type")
    private static final class DeepgramValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private Deepgram value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private DeepgramValue() {}

        private DeepgramValue(Deepgram value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitDeepgram(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof DeepgramValue && equalTo((DeepgramValue) other);
        }

        private boolean equalTo(DeepgramValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "AgentV1SettingsAgentSpeakOneItemProvider{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("eleven_labs")
    @JsonIgnoreProperties("type")
    private static final class ElevenLabsValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private ElevenLabs value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private ElevenLabsValue() {}

        private ElevenLabsValue(ElevenLabs value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitElevenLabs(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof ElevenLabsValue && equalTo((ElevenLabsValue) other);
        }

        private boolean equalTo(ElevenLabsValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "AgentV1SettingsAgentSpeakOneItemProvider{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("cartesia")
    @JsonIgnoreProperties("type")
    private static final class CartesiaValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private Cartesia value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private CartesiaValue() {}

        private CartesiaValue(Cartesia value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitCartesia(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof CartesiaValue && equalTo((CartesiaValue) other);
        }

        private boolean equalTo(CartesiaValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "AgentV1SettingsAgentSpeakOneItemProvider{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("open_ai")
    @JsonIgnoreProperties("type")
    private static final class OpenAiValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AgentV1SettingsAgentSpeakOneItemProviderOpenAi value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private OpenAiValue() {}

        private OpenAiValue(AgentV1SettingsAgentSpeakOneItemProviderOpenAi value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitOpenAi(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof OpenAiValue && equalTo((OpenAiValue) other);
        }

        private boolean equalTo(OpenAiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "AgentV1SettingsAgentSpeakOneItemProvider{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("aws_polly")
    @JsonIgnoreProperties("type")
    private static final class AwsPollyValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AgentV1SettingsAgentSpeakOneItemProviderAwsPolly value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private AwsPollyValue() {}

        private AwsPollyValue(AgentV1SettingsAgentSpeakOneItemProviderAwsPolly value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitAwsPolly(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof AwsPollyValue && equalTo((AwsPollyValue) other);
        }

        private boolean equalTo(AwsPollyValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "AgentV1SettingsAgentSpeakOneItemProvider{" + "value: " + value + "}";
        }
    }

    @JsonIgnoreProperties("type")
    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "AgentV1SettingsAgentSpeakOneItemProvider{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
