/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentV1UpdateThinkThinkOneItemProviderAwsBedrock.Builder.class)
public final class AgentV1UpdateThinkThinkOneItemProviderAwsBedrock {
    private final AgentV1UpdateThinkThinkOneItemProviderAwsBedrockModel model;

    private final Optional<Double> temperature;

    private final Optional<AgentV1UpdateThinkThinkOneItemProviderAwsBedrockCredentials> credentials;

    private final Map<String, Object> additionalProperties;

    private AgentV1UpdateThinkThinkOneItemProviderAwsBedrock(
            AgentV1UpdateThinkThinkOneItemProviderAwsBedrockModel model,
            Optional<Double> temperature,
            Optional<AgentV1UpdateThinkThinkOneItemProviderAwsBedrockCredentials> credentials,
            Map<String, Object> additionalProperties) {
        this.model = model;
        this.temperature = temperature;
        this.credentials = credentials;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return AWS Bedrock model to use
     */
    @JsonProperty("model")
    public AgentV1UpdateThinkThinkOneItemProviderAwsBedrockModel getModel() {
        return model;
    }

    /**
     * @return AWS Bedrock temperature (0-2)
     */
    @JsonProperty("temperature")
    public Optional<Double> getTemperature() {
        return temperature;
    }

    /**
     * @return AWS credentials type (STS short-lived or IAM long-lived)
     */
    @JsonProperty("credentials")
    public Optional<AgentV1UpdateThinkThinkOneItemProviderAwsBedrockCredentials> getCredentials() {
        return credentials;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentV1UpdateThinkThinkOneItemProviderAwsBedrock
                && equalTo((AgentV1UpdateThinkThinkOneItemProviderAwsBedrock) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentV1UpdateThinkThinkOneItemProviderAwsBedrock other) {
        return model.equals(other.model)
                && temperature.equals(other.temperature)
                && credentials.equals(other.credentials);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.model, this.temperature, this.credentials);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ModelStage builder() {
        return new Builder();
    }

    public interface ModelStage {
        /**
         * <p>AWS Bedrock model to use</p>
         */
        _FinalStage model(@NotNull AgentV1UpdateThinkThinkOneItemProviderAwsBedrockModel model);

        Builder from(AgentV1UpdateThinkThinkOneItemProviderAwsBedrock other);
    }

    public interface _FinalStage {
        AgentV1UpdateThinkThinkOneItemProviderAwsBedrock build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>AWS Bedrock temperature (0-2)</p>
         */
        _FinalStage temperature(Optional<Double> temperature);

        _FinalStage temperature(Double temperature);

        /**
         * <p>AWS credentials type (STS short-lived or IAM long-lived)</p>
         */
        _FinalStage credentials(Optional<AgentV1UpdateThinkThinkOneItemProviderAwsBedrockCredentials> credentials);

        _FinalStage credentials(AgentV1UpdateThinkThinkOneItemProviderAwsBedrockCredentials credentials);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ModelStage, _FinalStage {
        private AgentV1UpdateThinkThinkOneItemProviderAwsBedrockModel model;

        private Optional<AgentV1UpdateThinkThinkOneItemProviderAwsBedrockCredentials> credentials = Optional.empty();

        private Optional<Double> temperature = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AgentV1UpdateThinkThinkOneItemProviderAwsBedrock other) {
            model(other.getModel());
            temperature(other.getTemperature());
            credentials(other.getCredentials());
            return this;
        }

        /**
         * <p>AWS Bedrock model to use</p>
         * <p>AWS Bedrock model to use</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("model")
        public _FinalStage model(@NotNull AgentV1UpdateThinkThinkOneItemProviderAwsBedrockModel model) {
            this.model = Objects.requireNonNull(model, "model must not be null");
            return this;
        }

        /**
         * <p>AWS credentials type (STS short-lived or IAM long-lived)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage credentials(AgentV1UpdateThinkThinkOneItemProviderAwsBedrockCredentials credentials) {
            this.credentials = Optional.ofNullable(credentials);
            return this;
        }

        /**
         * <p>AWS credentials type (STS short-lived or IAM long-lived)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "credentials", nulls = Nulls.SKIP)
        public _FinalStage credentials(
                Optional<AgentV1UpdateThinkThinkOneItemProviderAwsBedrockCredentials> credentials) {
            this.credentials = credentials;
            return this;
        }

        /**
         * <p>AWS Bedrock temperature (0-2)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage temperature(Double temperature) {
            this.temperature = Optional.ofNullable(temperature);
            return this;
        }

        /**
         * <p>AWS Bedrock temperature (0-2)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "temperature", nulls = Nulls.SKIP)
        public _FinalStage temperature(Optional<Double> temperature) {
            this.temperature = temperature;
            return this;
        }

        @java.lang.Override
        public AgentV1UpdateThinkThinkOneItemProviderAwsBedrock build() {
            return new AgentV1UpdateThinkThinkOneItemProviderAwsBedrock(
                    model, temperature, credentials, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
