/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentV1UpdateThinkThinkContextLengthEndpoint.Builder.class)
public final class AgentV1UpdateThinkThinkContextLengthEndpoint {
    private final Optional<String> url;

    private final Optional<Map<String, String>> headers;

    private final Map<String, Object> additionalProperties;

    private AgentV1UpdateThinkThinkContextLengthEndpoint(
            Optional<String> url, Optional<Map<String, String>> headers, Map<String, Object> additionalProperties) {
        this.url = url;
        this.headers = headers;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Custom LLM endpoint URL
     */
    @JsonProperty("url")
    public Optional<String> getUrl() {
        return url;
    }

    /**
     * @return Custom headers for the endpoint
     */
    @JsonProperty("headers")
    public Optional<Map<String, String>> getHeaders() {
        return headers;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentV1UpdateThinkThinkContextLengthEndpoint
                && equalTo((AgentV1UpdateThinkThinkContextLengthEndpoint) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentV1UpdateThinkThinkContextLengthEndpoint other) {
        return url.equals(other.url) && headers.equals(other.headers);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.url, this.headers);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> url = Optional.empty();

        private Optional<Map<String, String>> headers = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AgentV1UpdateThinkThinkContextLengthEndpoint other) {
            url(other.getUrl());
            headers(other.getHeaders());
            return this;
        }

        /**
         * <p>Custom LLM endpoint URL</p>
         */
        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public Builder url(Optional<String> url) {
            this.url = url;
            return this;
        }

        public Builder url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        /**
         * <p>Custom headers for the endpoint</p>
         */
        @JsonSetter(value = "headers", nulls = Nulls.SKIP)
        public Builder headers(Optional<Map<String, String>> headers) {
            this.headers = headers;
            return this;
        }

        public Builder headers(Map<String, String> headers) {
            this.headers = Optional.ofNullable(headers);
            return this;
        }

        public AgentV1UpdateThinkThinkContextLengthEndpoint build() {
            return new AgentV1UpdateThinkThinkContextLengthEndpoint(url, headers, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
