/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentV1UpdateSpeakSpeakOneItemProviderDeepgram.Builder.class)
public final class AgentV1UpdateSpeakSpeakOneItemProviderDeepgram {
    private final Optional<String> version;

    private final AgentV1UpdateSpeakSpeakOneItemProviderDeepgramModel model;

    private final Optional<Double> speed;

    private final Map<String, Object> additionalProperties;

    private AgentV1UpdateSpeakSpeakOneItemProviderDeepgram(
            Optional<String> version,
            AgentV1UpdateSpeakSpeakOneItemProviderDeepgramModel model,
            Optional<Double> speed,
            Map<String, Object> additionalProperties) {
        this.version = version;
        this.model = model;
        this.speed = speed;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The REST API version for the Deepgram text-to-speech API
     */
    @JsonProperty("version")
    public Optional<String> getVersion() {
        return version;
    }

    /**
     * @return Deepgram TTS model
     */
    @JsonProperty("model")
    public AgentV1UpdateSpeakSpeakOneItemProviderDeepgramModel getModel() {
        return model;
    }

    /**
     * @return Speaking rate multiplier that adjusts the pace of generated speech while preserving natural prosody and voice quality. Not yet supported in all languages.
     */
    @JsonProperty("speed")
    public Optional<Double> getSpeed() {
        return speed;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentV1UpdateSpeakSpeakOneItemProviderDeepgram
                && equalTo((AgentV1UpdateSpeakSpeakOneItemProviderDeepgram) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentV1UpdateSpeakSpeakOneItemProviderDeepgram other) {
        return version.equals(other.version) && model.equals(other.model) && speed.equals(other.speed);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.version, this.model, this.speed);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ModelStage builder() {
        return new Builder();
    }

    public interface ModelStage {
        /**
         * <p>Deepgram TTS model</p>
         */
        _FinalStage model(@NotNull AgentV1UpdateSpeakSpeakOneItemProviderDeepgramModel model);

        Builder from(AgentV1UpdateSpeakSpeakOneItemProviderDeepgram other);
    }

    public interface _FinalStage {
        AgentV1UpdateSpeakSpeakOneItemProviderDeepgram build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The REST API version for the Deepgram text-to-speech API</p>
         */
        _FinalStage version(Optional<String> version);

        _FinalStage version(String version);

        /**
         * <p>Speaking rate multiplier that adjusts the pace of generated speech while preserving natural prosody and voice quality. Not yet supported in all languages.</p>
         */
        _FinalStage speed(Optional<Double> speed);

        _FinalStage speed(Double speed);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ModelStage, _FinalStage {
        private AgentV1UpdateSpeakSpeakOneItemProviderDeepgramModel model;

        private Optional<Double> speed = Optional.empty();

        private Optional<String> version = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AgentV1UpdateSpeakSpeakOneItemProviderDeepgram other) {
            version(other.getVersion());
            model(other.getModel());
            speed(other.getSpeed());
            return this;
        }

        /**
         * <p>Deepgram TTS model</p>
         * <p>Deepgram TTS model</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("model")
        public _FinalStage model(@NotNull AgentV1UpdateSpeakSpeakOneItemProviderDeepgramModel model) {
            this.model = Objects.requireNonNull(model, "model must not be null");
            return this;
        }

        /**
         * <p>Speaking rate multiplier that adjusts the pace of generated speech while preserving natural prosody and voice quality. Not yet supported in all languages.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage speed(Double speed) {
            this.speed = Optional.ofNullable(speed);
            return this;
        }

        /**
         * <p>Speaking rate multiplier that adjusts the pace of generated speech while preserving natural prosody and voice quality. Not yet supported in all languages.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "speed", nulls = Nulls.SKIP)
        public _FinalStage speed(Optional<Double> speed) {
            this.speed = speed;
            return this;
        }

        /**
         * <p>The REST API version for the Deepgram text-to-speech API</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage version(String version) {
            this.version = Optional.ofNullable(version);
            return this;
        }

        /**
         * <p>The REST API version for the Deepgram text-to-speech API</p>
         */
        @java.lang.Override
        @JsonSetter(value = "version", nulls = Nulls.SKIP)
        public _FinalStage version(Optional<String> version) {
            this.version = version;
            return this;
        }

        @java.lang.Override
        public AgentV1UpdateSpeakSpeakOneItemProviderDeepgram build() {
            return new AgentV1UpdateSpeakSpeakOneItemProviderDeepgram(version, model, speed, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
