/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType {
    public static final AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType IAM =
            new AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType(Value.IAM, "iam");

    public static final AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType STS =
            new AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType(Value.STS, "sts");

    private final Value value;

    private final String string;

    AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType
                        && this.string.equals(
                                ((AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case IAM:
                return visitor.visitIam();
            case STS:
                return visitor.visitSts();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType valueOf(String value) {
        switch (value) {
            case "iam":
                return IAM;
            case "sts":
                return STS;
            default:
                return new AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        STS,

        IAM,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSts();

        T visitIam();

        T visitUnknown(String unknownType);
    }
}
