/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentV1SettingsAudio.Builder.class)
public final class AgentV1SettingsAudio {
    private final Optional<AgentV1SettingsAudioInput> input;

    private final Optional<AgentV1SettingsAudioOutput> output;

    private final Map<String, Object> additionalProperties;

    private AgentV1SettingsAudio(
            Optional<AgentV1SettingsAudioInput> input,
            Optional<AgentV1SettingsAudioOutput> output,
            Map<String, Object> additionalProperties) {
        this.input = input;
        this.output = output;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Audio input configuration settings. If omitted, defaults to encoding=linear16 and sample_rate=24000. Higher sample rates like 44100 Hz provide better audio quality.
     */
    @JsonProperty("input")
    public Optional<AgentV1SettingsAudioInput> getInput() {
        return input;
    }

    /**
     * @return Audio output configuration settings
     */
    @JsonProperty("output")
    public Optional<AgentV1SettingsAudioOutput> getOutput() {
        return output;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentV1SettingsAudio && equalTo((AgentV1SettingsAudio) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentV1SettingsAudio other) {
        return input.equals(other.input) && output.equals(other.output);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.input, this.output);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<AgentV1SettingsAudioInput> input = Optional.empty();

        private Optional<AgentV1SettingsAudioOutput> output = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AgentV1SettingsAudio other) {
            input(other.getInput());
            output(other.getOutput());
            return this;
        }

        /**
         * <p>Audio input configuration settings. If omitted, defaults to encoding=linear16 and sample_rate=24000. Higher sample rates like 44100 Hz provide better audio quality.</p>
         */
        @JsonSetter(value = "input", nulls = Nulls.SKIP)
        public Builder input(Optional<AgentV1SettingsAudioInput> input) {
            this.input = input;
            return this;
        }

        public Builder input(AgentV1SettingsAudioInput input) {
            this.input = Optional.ofNullable(input);
            return this;
        }

        /**
         * <p>Audio output configuration settings</p>
         */
        @JsonSetter(value = "output", nulls = Nulls.SKIP)
        public Builder output(Optional<AgentV1SettingsAudioOutput> output) {
            this.output = output;
            return this;
        }

        public Builder output(AgentV1SettingsAudioOutput output) {
            this.output = Optional.ofNullable(output);
            return this;
        }

        public AgentV1SettingsAudio build() {
            return new AgentV1SettingsAudio(input, output, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
