/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice {
    public static final AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice SHIMMER =
            new AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice(Value.SHIMMER, "shimmer");

    public static final AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice FABLE =
            new AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice(Value.FABLE, "fable");

    public static final AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice ALLOY =
            new AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice(Value.ALLOY, "alloy");

    public static final AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice ONYX =
            new AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice(Value.ONYX, "onyx");

    public static final AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice NOVA =
            new AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice(Value.NOVA, "nova");

    public static final AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice ECHO =
            new AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice(Value.ECHO, "echo");

    private final Value value;

    private final String string;

    AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice
                        && this.string.equals(((AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SHIMMER:
                return visitor.visitShimmer();
            case FABLE:
                return visitor.visitFable();
            case ALLOY:
                return visitor.visitAlloy();
            case ONYX:
                return visitor.visitOnyx();
            case NOVA:
                return visitor.visitNova();
            case ECHO:
                return visitor.visitEcho();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice valueOf(String value) {
        switch (value) {
            case "shimmer":
                return SHIMMER;
            case "fable":
                return FABLE;
            case "alloy":
                return ALLOY;
            case "onyx":
                return ONYX;
            case "nova":
                return NOVA;
            case "echo":
                return ECHO;
            default:
                return new AgentV1SettingsAgentSpeakOneItemProviderOpenAiVoice(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ALLOY,

        ECHO,

        FABLE,

        ONYX,

        NOVA,

        SHIMMER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAlloy();

        T visitEcho();

        T visitFable();

        T visitOnyx();

        T visitNova();

        T visitShimmer();

        T visitUnknown(String unknownType);
    }
}
