/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.speak.v2.audio;

import com.deepgram.core.ClientOptions;
import com.deepgram.core.DeepgramApiException;
import com.deepgram.core.DeepgramApiHttpResponse;
import com.deepgram.core.DeepgramHttpException;
import com.deepgram.core.MediaTypes;
import com.deepgram.core.ObjectMappers;
import com.deepgram.core.QueryStringMapper;
import com.deepgram.core.RequestOptions;
import com.deepgram.core.ResponseBodyInputStream;
import com.deepgram.core.RetryInterceptor;
import com.deepgram.errors.BadRequestError;
import com.deepgram.resources.speak.v2.audio.requests.SpeakV2Request;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.io.InputStream;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawAudioClient {
    protected final ClientOptions clientOptions;

    public AsyncRawAudioClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Synthesize a complete block of text into a single audio response using Deepgram's Flux TTS batch (REST) API. Use this for pre-rendering fixed audio (IVR prompts, notifications, narration) where the whole text is known up front and you don't need incremental playback or interruption.
     */
    public CompletableFuture<DeepgramApiHttpResponse<InputStream>> generate(SpeakV2Request request) {
        return generate(request, null);
    }

    /**
     * Synthesize a complete block of text into a single audio response using Deepgram's Flux TTS batch (REST) API. Use this for pre-rendering fixed audio (IVR prompts, notifications, narration) where the whole text is known up front and you don't need incremental playback or interruption.
     */
    public CompletableFuture<DeepgramApiHttpResponse<InputStream>> generate(
            SpeakV2Request request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL())
                .newBuilder()
                .addPathSegments("v2/speak");
        if (request.getCallback().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "callback", request.getCallback().get(), false);
        }
        if (request.getCallbackMethod().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "callback_method", request.getCallbackMethod().get(), false);
        }
        if (request.getMipOptOut().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "mip_opt_out", request.getMipOptOut().get(), false);
        }
        if (request.getBitRate().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "bit_rate", request.getBitRate().get(), false);
        }
        if (request.getContainer().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "container", request.getContainer().get(), false);
        }
        if (request.getEncoding().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "encoding", request.getEncoding().get(), false);
        }
        if (request.getExpressivity().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "expressivity", request.getExpressivity().get(), false);
        }
        QueryStringMapper.addQueryParameter(httpUrl, "model", request.getModel(), false);
        if (request.getSampleRate().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sample_rate", request.getSampleRate().get(), false);
        }
        if (request.getSpeed().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "speed", request.getSpeed().get(), false);
        }
        if (request.getPriority().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "priority", request.getPriority().get(), false);
        }
        if (request.getTag().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "tag", request.getTag().get(), true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<DeepgramApiHttpResponse<InputStream>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try {
                    ResponseBody responseBody = response.body();
                    if (response.isSuccessful()) {
                        future.complete(new DeepgramApiHttpResponse<>(new ResponseBodyInputStream(response), response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 400) {
                            future.completeExceptionally(new BadRequestError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new DeepgramHttpException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new DeepgramApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
