/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.resources.listen.v2.types;

import com.deepgram.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListenV2FatalError.Builder.class)
public final class ListenV2FatalError {
    private final double sequenceId;

    private final String code;

    private final String description;

    private final Map<String, Object> additionalProperties;

    private ListenV2FatalError(
            double sequenceId, String code, String description, Map<String, Object> additionalProperties) {
        this.sequenceId = sequenceId;
        this.code = code;
        this.description = description;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Message type identifier
     */
    @JsonProperty("type")
    public String getType() {
        return "Error";
    }

    /**
     * @return Starts at <code>0</code> and increments for each message the server sends
     * to the client.  This includes messages of other types, like
     * <code>Connected</code> messages.
     */
    @JsonProperty("sequence_id")
    public double getSequenceId() {
        return sequenceId;
    }

    /**
     * @return A string code describing the error, e.g. <code>INTERNAL_SERVER_ERROR</code>
     */
    @JsonProperty("code")
    public String getCode() {
        return code;
    }

    /**
     * @return Prose description of the error
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListenV2FatalError && equalTo((ListenV2FatalError) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListenV2FatalError other) {
        return sequenceId == other.sequenceId && code.equals(other.code) && description.equals(other.description);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.sequenceId, this.code, this.description);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SequenceIdStage builder() {
        return new Builder();
    }

    public interface SequenceIdStage {
        /**
         * <p>Starts at <code>0</code> and increments for each message the server sends
         * to the client.  This includes messages of other types, like
         * <code>Connected</code> messages.</p>
         */
        CodeStage sequenceId(double sequenceId);

        Builder from(ListenV2FatalError other);
    }

    public interface CodeStage {
        /**
         * <p>A string code describing the error, e.g. <code>INTERNAL_SERVER_ERROR</code></p>
         */
        DescriptionStage code(@NotNull String code);
    }

    public interface DescriptionStage {
        /**
         * <p>Prose description of the error</p>
         */
        _FinalStage description(@NotNull String description);
    }

    public interface _FinalStage {
        ListenV2FatalError build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SequenceIdStage, CodeStage, DescriptionStage, _FinalStage {
        private double sequenceId;

        private String code;

        private String description;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListenV2FatalError other) {
            sequenceId(other.getSequenceId());
            code(other.getCode());
            description(other.getDescription());
            return this;
        }

        /**
         * <p>Starts at <code>0</code> and increments for each message the server sends
         * to the client.  This includes messages of other types, like
         * <code>Connected</code> messages.</p>
         * <p>Starts at <code>0</code> and increments for each message the server sends
         * to the client.  This includes messages of other types, like
         * <code>Connected</code> messages.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("sequence_id")
        public CodeStage sequenceId(double sequenceId) {
            this.sequenceId = sequenceId;
            return this;
        }

        /**
         * <p>A string code describing the error, e.g. <code>INTERNAL_SERVER_ERROR</code></p>
         * <p>A string code describing the error, e.g. <code>INTERNAL_SERVER_ERROR</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("code")
        public DescriptionStage code(@NotNull String code) {
            this.code = Objects.requireNonNull(code, "code must not be null");
            return this;
        }

        /**
         * <p>Prose description of the error</p>
         * <p>Prose description of the error</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public _FinalStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        @java.lang.Override
        public ListenV2FatalError build() {
            return new ListenV2FatalError(sequenceId, code, description, additionalProperties);
        }
    }
}
