/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.settings;

import com.deepgram.core.ClientOptions;
import com.deepgram.core.Suppliers;
import com.deepgram.resources.agent.v1.settings.think.AsyncThinkClient;
import java.util.function.Supplier;

public class AsyncSettingsClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncThinkClient> thinkClient;

    public AsyncSettingsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.thinkClient = Suppliers.memoize(() -> new AsyncThinkClient(clientOptions));
    }

    public AsyncThinkClient think() {
        return this.thinkClient.get();
    }
}
