/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.agent.v1.settings;

import com.deepgram.core.ClientOptions;
import com.deepgram.core.Suppliers;
import com.deepgram.resources.agent.v1.settings.think.ThinkClient;
import java.util.function.Supplier;

public class SettingsClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<ThinkClient> thinkClient;

    public SettingsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.thinkClient = Suppliers.memoize(() -> new ThinkClient(clientOptions));
    }

    public ThinkClient think() {
        return this.thinkClient.get();
    }
}
