/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.manage.v1.projects.members.invites;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.DeepgramApiApiException;
import core.DeepgramApiException;
import core.DeepgramApiHttpResponse;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import errors.BadRequestError;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.manage.v1.projects.members.invites.requests.CreateProjectInviteV1Request;
import types.CreateProjectInviteV1Response;
import types.DeleteProjectInviteV1Response;
import types.ListProjectInvitesV1Response;

public class RawInvitesClient {
  protected final ClientOptions clientOptions;

  public RawInvitesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Generates a list of invites for a specific project
   */
  public DeepgramApiHttpResponse<ListProjectInvitesV1Response> list(String projectId) {
    return list(projectId,null);
  }

  /**
   * Generates a list of invites for a specific project
   */
  public DeepgramApiHttpResponse<ListProjectInvitesV1Response> list(String projectId,
      RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

      .addPathSegments("v1/projects")
      .addPathSegment(projectId)
      .addPathSegments("invites")
      .build();
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("GET", null)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Accept", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      if (response.isSuccessful()) {
        return new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), ListProjectInvitesV1Response.class), response);
      }
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      try {
        if (response.code() == 400) {
          throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
        }
      }
      catch (JsonProcessingException ignored) {
        // unable to map error response, throwing generic error
      }
      throw new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
    }
    catch (IOException e) {
      throw new DeepgramApiException("Network error executing HTTP request", e);
    }
  }

  /**
   * Generates an invite for a specific project
   */
  public DeepgramApiHttpResponse<CreateProjectInviteV1Response> create(String projectId,
      CreateProjectInviteV1Request request) {
    return create(projectId,request,null);
  }

  /**
   * Generates an invite for a specific project
   */
  public DeepgramApiHttpResponse<CreateProjectInviteV1Response> create(String projectId,
      CreateProjectInviteV1Request request, RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

      .addPathSegments("v1/projects")
      .addPathSegment(projectId)
      .addPathSegments("invites")
      .build();
    RequestBody body;
    try {
      body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
    }
    catch(JsonProcessingException e) {
      throw new DeepgramApiException("Failed to serialize request", e);
    }
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("POST", body)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .addHeader("Accept", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      if (response.isSuccessful()) {
        return new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateProjectInviteV1Response.class), response);
      }
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      try {
        if (response.code() == 400) {
          throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
        }
      }
      catch (JsonProcessingException ignored) {
        // unable to map error response, throwing generic error
      }
      throw new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
    }
    catch (IOException e) {
      throw new DeepgramApiException("Network error executing HTTP request", e);
    }
  }

  /**
   * Deletes an invite for a specific project
   */
  public DeepgramApiHttpResponse<DeleteProjectInviteV1Response> delete(String projectId,
      String email) {
    return delete(projectId,email,null);
  }

  /**
   * Deletes an invite for a specific project
   */
  public DeepgramApiHttpResponse<DeleteProjectInviteV1Response> delete(String projectId,
      String email, RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL()).newBuilder()

      .addPathSegments("v1/projects")
      .addPathSegment(projectId)
      .addPathSegments("invites")
      .addPathSegment(email)
      .build();
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("DELETE", null)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Accept", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      if (response.isSuccessful()) {
        return new DeepgramApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), DeleteProjectInviteV1Response.class), response);
      }
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      try {
        if (response.code() == 400) {
          throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
        }
      }
      catch (JsonProcessingException ignored) {
        // unable to map error response, throwing generic error
      }
      throw new DeepgramApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
    }
    catch (IOException e) {
      throw new DeepgramApiException("Network error executing HTTP request", e);
    }
  }
}
