/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.listen;

import com.deepgram.core.ClientOptions;
import com.deepgram.core.Suppliers;
import com.deepgram.resources.listen.v1.V1Client;
import com.deepgram.resources.listen.v2.V2Client;
import java.util.function.Supplier;

public class ListenClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<V1Client> v1Client;

    protected final Supplier<V2Client> v2Client;

    public ListenClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.v1Client = Suppliers.memoize(() -> new V1Client(clientOptions));
        this.v2Client = Suppliers.memoize(() -> new V2Client(clientOptions));
    }

    public V1Client v1() {
        return this.v1Client.get();
    }

    public V2Client v2() {
        return this.v2Client.get();
    }
}
