/** This file was auto-generated by Fern from our API Definition. */
package resources.read.v1.text.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import resources.read.v1.text.types.TextAnalyzeRequestCallbackMethod;
import resources.read.v1.text.types.TextAnalyzeRequestCustomIntentMode;
import resources.read.v1.text.types.TextAnalyzeRequestCustomTopicMode;
import resources.read.v1.text.types.TextAnalyzeRequestSummarize;
import types.ReadV1Request;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TextAnalyzeRequest.Builder.class)
public final class TextAnalyzeRequest {
  private final Optional<List<String>> tag;

  private final Optional<List<String>> customTopic;

  private final Optional<List<String>> customIntent;

  private final Optional<String> callback;

  private final Optional<TextAnalyzeRequestCallbackMethod> callbackMethod;

  private final Optional<Boolean> sentiment;

  private final Optional<TextAnalyzeRequestSummarize> summarize;

  private final Optional<Boolean> topics;

  private final Optional<TextAnalyzeRequestCustomTopicMode> customTopicMode;

  private final Optional<Boolean> intents;

  private final Optional<TextAnalyzeRequestCustomIntentMode> customIntentMode;

  private final Optional<String> language;

  private final ReadV1Request body;

  private final Map<String, Object> additionalProperties;

  private TextAnalyzeRequest(
      Optional<List<String>> tag,
      Optional<List<String>> customTopic,
      Optional<List<String>> customIntent,
      Optional<String> callback,
      Optional<TextAnalyzeRequestCallbackMethod> callbackMethod,
      Optional<Boolean> sentiment,
      Optional<TextAnalyzeRequestSummarize> summarize,
      Optional<Boolean> topics,
      Optional<TextAnalyzeRequestCustomTopicMode> customTopicMode,
      Optional<Boolean> intents,
      Optional<TextAnalyzeRequestCustomIntentMode> customIntentMode,
      Optional<String> language,
      ReadV1Request body,
      Map<String, Object> additionalProperties) {
    this.tag = tag;
    this.customTopic = customTopic;
    this.customIntent = customIntent;
    this.callback = callback;
    this.callbackMethod = callbackMethod;
    this.sentiment = sentiment;
    this.summarize = summarize;
    this.topics = topics;
    this.customTopicMode = customTopicMode;
    this.intents = intents;
    this.customIntentMode = customIntentMode;
    this.language = language;
    this.body = body;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Label your requests for the purpose of identification during usage reporting
   */
  @JsonProperty("tag")
  public Optional<List<String>> getTag() {
    return tag;
  }

  /**
   * @return Custom topics you want the model to detect within your input audio or text if present
   *     Submit up to <code>100</code>.
   */
  @JsonProperty("custom_topic")
  public Optional<List<String>> getCustomTopic() {
    return customTopic;
  }

  /**
   * @return Custom intents you want the model to detect within your input audio if present
   */
  @JsonProperty("custom_intent")
  public Optional<List<String>> getCustomIntent() {
    return customIntent;
  }

  /**
   * @return URL to which we'll make the callback request
   */
  @JsonProperty("callback")
  public Optional<String> getCallback() {
    return callback;
  }

  /**
   * @return HTTP method by which the callback request will be made
   */
  @JsonProperty("callback_method")
  public Optional<TextAnalyzeRequestCallbackMethod> getCallbackMethod() {
    return callbackMethod;
  }

  /**
   * @return Recognizes the sentiment throughout a transcript or text
   */
  @JsonProperty("sentiment")
  public Optional<Boolean> getSentiment() {
    return sentiment;
  }

  /**
   * @return Summarize content. For Listen API, supports string version option. For Read API,
   *     accepts boolean only.
   */
  @JsonProperty("summarize")
  public Optional<TextAnalyzeRequestSummarize> getSummarize() {
    return summarize;
  }

  /**
   * @return Detect topics throughout a transcript or text
   */
  @JsonProperty("topics")
  public Optional<Boolean> getTopics() {
    return topics;
  }

  /**
   * @return Sets how the model will interpret strings submitted to the <code>custom_topic</code>
   *     param. When <code>strict</code>, the model will only return topics submitted using the
   *     <code>custom_topic</code> param. When <code>extended</code>, the model will return its own
   *     detected topics in addition to those submitted using the <code>custom_topic</code> param
   */
  @JsonProperty("custom_topic_mode")
  public Optional<TextAnalyzeRequestCustomTopicMode> getCustomTopicMode() {
    return customTopicMode;
  }

  /**
   * @return Recognizes speaker intent throughout a transcript or text
   */
  @JsonProperty("intents")
  public Optional<Boolean> getIntents() {
    return intents;
  }

  /**
   * @return Sets how the model will interpret intents submitted to the <code>custom_intent</code>
   *     param. When <code>strict</code>, the model will only return intents submitted using the
   *     <code>custom_intent</code> param. When <code>extended</code>, the model will return its own
   *     detected intents in the <code>custom_intent</code> param.
   */
  @JsonProperty("custom_intent_mode")
  public Optional<TextAnalyzeRequestCustomIntentMode> getCustomIntentMode() {
    return customIntentMode;
  }

  /**
   * @return The <a href="https://tools.ietf.org/html/bcp47">BCP-47 language tag</a> that hints at
   *     the primary spoken language. Depending on the Model and API endpoint you choose only
   *     certain languages are available
   */
  @JsonProperty("language")
  public Optional<String> getLanguage() {
    return language;
  }

  @JsonProperty("body")
  public ReadV1Request getBody() {
    return body;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TextAnalyzeRequest && equalTo((TextAnalyzeRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TextAnalyzeRequest other) {
    return tag.equals(other.tag)
        && customTopic.equals(other.customTopic)
        && customIntent.equals(other.customIntent)
        && callback.equals(other.callback)
        && callbackMethod.equals(other.callbackMethod)
        && sentiment.equals(other.sentiment)
        && summarize.equals(other.summarize)
        && topics.equals(other.topics)
        && customTopicMode.equals(other.customTopicMode)
        && intents.equals(other.intents)
        && customIntentMode.equals(other.customIntentMode)
        && language.equals(other.language)
        && body.equals(other.body);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(
        this.tag,
        this.customTopic,
        this.customIntent,
        this.callback,
        this.callbackMethod,
        this.sentiment,
        this.summarize,
        this.topics,
        this.customTopicMode,
        this.intents,
        this.customIntentMode,
        this.language,
        this.body);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static BodyStage builder() {
    return new Builder();
  }

  public interface BodyStage {
    _FinalStage body(@NotNull ReadV1Request body);

    Builder from(TextAnalyzeRequest other);
  }

  public interface _FinalStage {
    TextAnalyzeRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /** Label your requests for the purpose of identification during usage reporting */
    _FinalStage tag(Optional<List<String>> tag);

    _FinalStage tag(List<String> tag);

    _FinalStage tag(String tag);

    /**
     * Custom topics you want the model to detect within your input audio or text if present Submit
     * up to <code>100</code>.
     */
    _FinalStage customTopic(Optional<List<String>> customTopic);

    _FinalStage customTopic(List<String> customTopic);

    _FinalStage customTopic(String customTopic);

    /** Custom intents you want the model to detect within your input audio if present */
    _FinalStage customIntent(Optional<List<String>> customIntent);

    _FinalStage customIntent(List<String> customIntent);

    _FinalStage customIntent(String customIntent);

    /** URL to which we'll make the callback request */
    _FinalStage callback(Optional<String> callback);

    _FinalStage callback(String callback);

    /** HTTP method by which the callback request will be made */
    _FinalStage callbackMethod(Optional<TextAnalyzeRequestCallbackMethod> callbackMethod);

    _FinalStage callbackMethod(TextAnalyzeRequestCallbackMethod callbackMethod);

    /** Recognizes the sentiment throughout a transcript or text */
    _FinalStage sentiment(Optional<Boolean> sentiment);

    _FinalStage sentiment(Boolean sentiment);

    /**
     * Summarize content. For Listen API, supports string version option. For Read API, accepts
     * boolean only.
     */
    _FinalStage summarize(Optional<TextAnalyzeRequestSummarize> summarize);

    _FinalStage summarize(TextAnalyzeRequestSummarize summarize);

    /** Detect topics throughout a transcript or text */
    _FinalStage topics(Optional<Boolean> topics);

    _FinalStage topics(Boolean topics);

    /**
     * Sets how the model will interpret strings submitted to the <code>custom_topic</code> param.
     * When <code>strict</code>, the model will only return topics submitted using the <code>
     * custom_topic</code> param. When <code>extended</code>, the model will return its own detected
     * topics in addition to those submitted using the <code>custom_topic</code> param
     */
    _FinalStage customTopicMode(Optional<TextAnalyzeRequestCustomTopicMode> customTopicMode);

    _FinalStage customTopicMode(TextAnalyzeRequestCustomTopicMode customTopicMode);

    /** Recognizes speaker intent throughout a transcript or text */
    _FinalStage intents(Optional<Boolean> intents);

    _FinalStage intents(Boolean intents);

    /**
     * Sets how the model will interpret intents submitted to the <code>custom_intent</code> param.
     * When <code>strict</code>, the model will only return intents submitted using the <code>
     * custom_intent</code> param. When <code>extended</code>, the model will return its own
     * detected intents in the <code>custom_intent</code> param.
     */
    _FinalStage customIntentMode(Optional<TextAnalyzeRequestCustomIntentMode> customIntentMode);

    _FinalStage customIntentMode(TextAnalyzeRequestCustomIntentMode customIntentMode);

    /**
     * The <a href="https://tools.ietf.org/html/bcp47">BCP-47 language tag</a> that hints at the
     * primary spoken language. Depending on the Model and API endpoint you choose only certain
     * languages are available
     */
    _FinalStage language(Optional<String> language);

    _FinalStage language(String language);
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static final class Builder implements BodyStage, _FinalStage {
    private ReadV1Request body;

    private Optional<String> language = Optional.empty();

    private Optional<TextAnalyzeRequestCustomIntentMode> customIntentMode = Optional.empty();

    private Optional<Boolean> intents = Optional.empty();

    private Optional<TextAnalyzeRequestCustomTopicMode> customTopicMode = Optional.empty();

    private Optional<Boolean> topics = Optional.empty();

    private Optional<TextAnalyzeRequestSummarize> summarize = Optional.empty();

    private Optional<Boolean> sentiment = Optional.empty();

    private Optional<TextAnalyzeRequestCallbackMethod> callbackMethod = Optional.empty();

    private Optional<String> callback = Optional.empty();

    private Optional<List<String>> customIntent = Optional.empty();

    private Optional<List<String>> customTopic = Optional.empty();

    private Optional<List<String>> tag = Optional.empty();

    @JsonAnySetter private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {}

    @java.lang.Override
    public Builder from(TextAnalyzeRequest other) {
      tag(other.getTag());
      customTopic(other.getCustomTopic());
      customIntent(other.getCustomIntent());
      callback(other.getCallback());
      callbackMethod(other.getCallbackMethod());
      sentiment(other.getSentiment());
      summarize(other.getSummarize());
      topics(other.getTopics());
      customTopicMode(other.getCustomTopicMode());
      intents(other.getIntents());
      customIntentMode(other.getCustomIntentMode());
      language(other.getLanguage());
      body(other.getBody());
      return this;
    }

    @java.lang.Override
    @JsonSetter("body")
    public _FinalStage body(@NotNull ReadV1Request body) {
      this.body = Objects.requireNonNull(body, "body must not be null");
      return this;
    }

    /**
     * The <a href="https://tools.ietf.org/html/bcp47">BCP-47 language tag</a> that hints at the
     * primary spoken language. Depending on the Model and API endpoint you choose only certain
     * languages are available
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage language(String language) {
      this.language = Optional.ofNullable(language);
      return this;
    }

    /**
     * The <a href="https://tools.ietf.org/html/bcp47">BCP-47 language tag</a> that hints at the
     * primary spoken language. Depending on the Model and API endpoint you choose only certain
     * languages are available
     */
    @java.lang.Override
    @JsonSetter(value = "language", nulls = Nulls.SKIP)
    public _FinalStage language(Optional<String> language) {
      this.language = language;
      return this;
    }

    /**
     * Sets how the model will interpret intents submitted to the <code>custom_intent</code> param.
     * When <code>strict</code>, the model will only return intents submitted using the <code>
     * custom_intent</code> param. When <code>extended</code>, the model will return its own
     * detected intents in the <code>custom_intent</code> param.
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage customIntentMode(TextAnalyzeRequestCustomIntentMode customIntentMode) {
      this.customIntentMode = Optional.ofNullable(customIntentMode);
      return this;
    }

    /**
     * Sets how the model will interpret intents submitted to the <code>custom_intent</code> param.
     * When <code>strict</code>, the model will only return intents submitted using the <code>
     * custom_intent</code> param. When <code>extended</code>, the model will return its own
     * detected intents in the <code>custom_intent</code> param.
     */
    @java.lang.Override
    @JsonSetter(value = "custom_intent_mode", nulls = Nulls.SKIP)
    public _FinalStage customIntentMode(
        Optional<TextAnalyzeRequestCustomIntentMode> customIntentMode) {
      this.customIntentMode = customIntentMode;
      return this;
    }

    /**
     * Recognizes speaker intent throughout a transcript or text
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage intents(Boolean intents) {
      this.intents = Optional.ofNullable(intents);
      return this;
    }

    /** Recognizes speaker intent throughout a transcript or text */
    @java.lang.Override
    @JsonSetter(value = "intents", nulls = Nulls.SKIP)
    public _FinalStage intents(Optional<Boolean> intents) {
      this.intents = intents;
      return this;
    }

    /**
     * Sets how the model will interpret strings submitted to the <code>custom_topic</code> param.
     * When <code>strict</code>, the model will only return topics submitted using the <code>
     * custom_topic</code> param. When <code>extended</code>, the model will return its own detected
     * topics in addition to those submitted using the <code>custom_topic</code> param
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage customTopicMode(TextAnalyzeRequestCustomTopicMode customTopicMode) {
      this.customTopicMode = Optional.ofNullable(customTopicMode);
      return this;
    }

    /**
     * Sets how the model will interpret strings submitted to the <code>custom_topic</code> param.
     * When <code>strict</code>, the model will only return topics submitted using the <code>
     * custom_topic</code> param. When <code>extended</code>, the model will return its own detected
     * topics in addition to those submitted using the <code>custom_topic</code> param
     */
    @java.lang.Override
    @JsonSetter(value = "custom_topic_mode", nulls = Nulls.SKIP)
    public _FinalStage customTopicMode(
        Optional<TextAnalyzeRequestCustomTopicMode> customTopicMode) {
      this.customTopicMode = customTopicMode;
      return this;
    }

    /**
     * Detect topics throughout a transcript or text
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage topics(Boolean topics) {
      this.topics = Optional.ofNullable(topics);
      return this;
    }

    /** Detect topics throughout a transcript or text */
    @java.lang.Override
    @JsonSetter(value = "topics", nulls = Nulls.SKIP)
    public _FinalStage topics(Optional<Boolean> topics) {
      this.topics = topics;
      return this;
    }

    /**
     * Summarize content. For Listen API, supports string version option. For Read API, accepts
     * boolean only.
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage summarize(TextAnalyzeRequestSummarize summarize) {
      this.summarize = Optional.ofNullable(summarize);
      return this;
    }

    /**
     * Summarize content. For Listen API, supports string version option. For Read API, accepts
     * boolean only.
     */
    @java.lang.Override
    @JsonSetter(value = "summarize", nulls = Nulls.SKIP)
    public _FinalStage summarize(Optional<TextAnalyzeRequestSummarize> summarize) {
      this.summarize = summarize;
      return this;
    }

    /**
     * Recognizes the sentiment throughout a transcript or text
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage sentiment(Boolean sentiment) {
      this.sentiment = Optional.ofNullable(sentiment);
      return this;
    }

    /** Recognizes the sentiment throughout a transcript or text */
    @java.lang.Override
    @JsonSetter(value = "sentiment", nulls = Nulls.SKIP)
    public _FinalStage sentiment(Optional<Boolean> sentiment) {
      this.sentiment = sentiment;
      return this;
    }

    /**
     * HTTP method by which the callback request will be made
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage callbackMethod(TextAnalyzeRequestCallbackMethod callbackMethod) {
      this.callbackMethod = Optional.ofNullable(callbackMethod);
      return this;
    }

    /** HTTP method by which the callback request will be made */
    @java.lang.Override
    @JsonSetter(value = "callback_method", nulls = Nulls.SKIP)
    public _FinalStage callbackMethod(Optional<TextAnalyzeRequestCallbackMethod> callbackMethod) {
      this.callbackMethod = callbackMethod;
      return this;
    }

    /**
     * URL to which we'll make the callback request
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage callback(String callback) {
      this.callback = Optional.ofNullable(callback);
      return this;
    }

    /** URL to which we'll make the callback request */
    @java.lang.Override
    @JsonSetter(value = "callback", nulls = Nulls.SKIP)
    public _FinalStage callback(Optional<String> callback) {
      this.callback = callback;
      return this;
    }

    @java.lang.Override
    public _FinalStage customIntent(String customIntent) {
      this.customIntent = Optional.of(Collections.singletonList(customIntent));
      return this;
    }

    /**
     * Custom intents you want the model to detect within your input audio if present
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage customIntent(List<String> customIntent) {
      this.customIntent = Optional.ofNullable(customIntent);
      return this;
    }

    /** Custom intents you want the model to detect within your input audio if present */
    @java.lang.Override
    @JsonSetter(value = "custom_intent", nulls = Nulls.SKIP)
    public _FinalStage customIntent(Optional<List<String>> customIntent) {
      this.customIntent = customIntent;
      return this;
    }

    @java.lang.Override
    public _FinalStage customTopic(String customTopic) {
      this.customTopic = Optional.of(Collections.singletonList(customTopic));
      return this;
    }

    /**
     * Custom topics you want the model to detect within your input audio or text if present Submit
     * up to <code>100</code>.
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage customTopic(List<String> customTopic) {
      this.customTopic = Optional.ofNullable(customTopic);
      return this;
    }

    /**
     * Custom topics you want the model to detect within your input audio or text if present Submit
     * up to <code>100</code>.
     */
    @java.lang.Override
    @JsonSetter(value = "custom_topic", nulls = Nulls.SKIP)
    public _FinalStage customTopic(Optional<List<String>> customTopic) {
      this.customTopic = customTopic;
      return this;
    }

    @java.lang.Override
    public _FinalStage tag(String tag) {
      this.tag = Optional.of(Collections.singletonList(tag));
      return this;
    }

    /**
     * Label your requests for the purpose of identification during usage reporting
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage tag(List<String> tag) {
      this.tag = Optional.ofNullable(tag);
      return this;
    }

    /** Label your requests for the purpose of identification during usage reporting */
    @java.lang.Override
    @JsonSetter(value = "tag", nulls = Nulls.SKIP)
    public _FinalStage tag(Optional<List<String>> tag) {
      this.tag = tag;
      return this;
    }

    @java.lang.Override
    public TextAnalyzeRequest build() {
      return new TextAnalyzeRequest(
          tag,
          customTopic,
          customIntent,
          callback,
          callbackMethod,
          sentiment,
          summarize,
          topics,
          customTopicMode,
          intents,
          customIntentMode,
          language,
          body,
          additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
