/** This file was auto-generated by Fern from our API Definition. */
package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AwsPollySpeakProviderEngine {
  public static final AwsPollySpeakProviderEngine LONG_FORM =
      new AwsPollySpeakProviderEngine(Value.LONG_FORM, "long-form");

  public static final AwsPollySpeakProviderEngine STANDARD =
      new AwsPollySpeakProviderEngine(Value.STANDARD, "standard");

  public static final AwsPollySpeakProviderEngine GENERATIVE =
      new AwsPollySpeakProviderEngine(Value.GENERATIVE, "generative");

  public static final AwsPollySpeakProviderEngine NEURAL =
      new AwsPollySpeakProviderEngine(Value.NEURAL, "neural");

  private final Value value;

  private final String string;

  AwsPollySpeakProviderEngine(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other)
        || (other instanceof AwsPollySpeakProviderEngine
            && this.string.equals(((AwsPollySpeakProviderEngine) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case LONG_FORM:
        return visitor.visitLongForm();
      case STANDARD:
        return visitor.visitStandard();
      case GENERATIVE:
        return visitor.visitGenerative();
      case NEURAL:
        return visitor.visitNeural();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
  public static AwsPollySpeakProviderEngine valueOf(String value) {
    switch (value) {
      case "long-form":
        return LONG_FORM;
      case "standard":
        return STANDARD;
      case "generative":
        return GENERATIVE;
      case "neural":
        return NEURAL;
      default:
        return new AwsPollySpeakProviderEngine(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    GENERATIVE,

    LONG_FORM,

    STANDARD,

    NEURAL,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitGenerative();

    T visitLongForm();

    T visitStandard();

    T visitNeural();

    T visitUnknown(String unknownType);
  }
}
