/** This file was auto-generated by Fern from our API Definition. */
package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Cartesia.Builder.class)
public final class Cartesia {
  private final Optional<String> version;

  private final CartesiaSpeakProviderModelId modelId;

  private final CartesiaSpeakProviderVoice voice;

  private final Optional<String> language;

  private final Map<String, Object> additionalProperties;

  private Cartesia(
      Optional<String> version,
      CartesiaSpeakProviderModelId modelId,
      CartesiaSpeakProviderVoice voice,
      Optional<String> language,
      Map<String, Object> additionalProperties) {
    this.version = version;
    this.modelId = modelId;
    this.voice = voice;
    this.language = language;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public String getType() {
    return "cartesia";
  }

  /**
   * @return The API version header for the Cartesia text-to-speech API
   */
  @JsonProperty("version")
  public Optional<String> getVersion() {
    return version;
  }

  /**
   * @return Cartesia model ID
   */
  @JsonProperty("model_id")
  public CartesiaSpeakProviderModelId getModelId() {
    return modelId;
  }

  @JsonProperty("voice")
  public CartesiaSpeakProviderVoice getVoice() {
    return voice;
  }

  /**
   * @return Cartesia language code
   */
  @JsonProperty("language")
  public Optional<String> getLanguage() {
    return language;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Cartesia && equalTo((Cartesia) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Cartesia other) {
    return version.equals(other.version)
        && modelId.equals(other.modelId)
        && voice.equals(other.voice)
        && language.equals(other.language);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.version, this.modelId, this.voice, this.language);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ModelIdStage builder() {
    return new Builder();
  }

  public interface ModelIdStage {
    /** Cartesia model ID */
    VoiceStage modelId(@NotNull CartesiaSpeakProviderModelId modelId);

    Builder from(Cartesia other);
  }

  public interface VoiceStage {
    _FinalStage voice(@NotNull CartesiaSpeakProviderVoice voice);
  }

  public interface _FinalStage {
    Cartesia build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /** The API version header for the Cartesia text-to-speech API */
    _FinalStage version(Optional<String> version);

    _FinalStage version(String version);

    /** Cartesia language code */
    _FinalStage language(Optional<String> language);

    _FinalStage language(String language);
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static final class Builder implements ModelIdStage, VoiceStage, _FinalStage {
    private CartesiaSpeakProviderModelId modelId;

    private CartesiaSpeakProviderVoice voice;

    private Optional<String> language = Optional.empty();

    private Optional<String> version = Optional.empty();

    @JsonAnySetter private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {}

    @java.lang.Override
    public Builder from(Cartesia other) {
      version(other.getVersion());
      modelId(other.getModelId());
      voice(other.getVoice());
      language(other.getLanguage());
      return this;
    }

    /**
     * Cartesia model ID
     *
     * <p>Cartesia model ID
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("model_id")
    public VoiceStage modelId(@NotNull CartesiaSpeakProviderModelId modelId) {
      this.modelId = Objects.requireNonNull(modelId, "modelId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("voice")
    public _FinalStage voice(@NotNull CartesiaSpeakProviderVoice voice) {
      this.voice = Objects.requireNonNull(voice, "voice must not be null");
      return this;
    }

    /**
     * Cartesia language code
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage language(String language) {
      this.language = Optional.ofNullable(language);
      return this;
    }

    /** Cartesia language code */
    @java.lang.Override
    @JsonSetter(value = "language", nulls = Nulls.SKIP)
    public _FinalStage language(Optional<String> language) {
      this.language = language;
      return this;
    }

    /**
     * The API version header for the Cartesia text-to-speech API
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage version(String version) {
      this.version = Optional.ofNullable(version);
      return this;
    }

    /** The API version header for the Cartesia text-to-speech API */
    @java.lang.Override
    @JsonSetter(value = "version", nulls = Nulls.SKIP)
    public _FinalStage version(Optional<String> version) {
      this.version = version;
      return this;
    }

    @java.lang.Override
    public Cartesia build() {
      return new Cartesia(version, modelId, voice, language, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
