/** This file was auto-generated by Fern from our API Definition. */
package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetProjectRequestV1Response.Builder.class)
public final class GetProjectRequestV1Response {
  private final Optional<ProjectRequestResponse> request;

  private final Map<String, Object> additionalProperties;

  private GetProjectRequestV1Response(
      Optional<ProjectRequestResponse> request, Map<String, Object> additionalProperties) {
    this.request = request;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("request")
  public Optional<ProjectRequestResponse> getRequest() {
    return request;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetProjectRequestV1Response
        && equalTo((GetProjectRequestV1Response) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetProjectRequestV1Response other) {
    return request.equals(other.request);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.request);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static final class Builder {
    private Optional<ProjectRequestResponse> request = Optional.empty();

    @JsonAnySetter private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {}

    public Builder from(GetProjectRequestV1Response other) {
      request(other.getRequest());
      return this;
    }

    @JsonSetter(value = "request", nulls = Nulls.SKIP)
    public Builder request(Optional<ProjectRequestResponse> request) {
      this.request = request;
      return this;
    }

    public Builder request(ProjectRequestResponse request) {
      this.request = Optional.ofNullable(request);
      return this;
    }

    public GetProjectRequestV1Response build() {
      return new GetProjectRequestV1Response(request, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
