/** This file was auto-generated by Fern from our API Definition. */
package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import core.WrappedAlias;

public final class ListenV2SampleRate implements WrappedAlias {
  private final Object value;

  private ListenV2SampleRate(Object value) {
    this.value = value;
  }

  @JsonValue
  public Object get() {
    return this.value;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ListenV2SampleRate
            && this.value.equals(((ListenV2SampleRate) other).value));
  }

  @java.lang.Override
  public int hashCode() {
    return value.hashCode();
  }

  @java.lang.Override
  public String toString() {
    return value.toString();
  }

  @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
  public static ListenV2SampleRate of(Object value) {
    return new ListenV2SampleRate(value);
  }
}
