/** This file was auto-generated by Fern from our API Definition. */
package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ReadV1ResponseResults.Builder.class)
public final class ReadV1ResponseResults {
  private final Optional<ReadV1ResponseResultsSummary> summary;

  private final Optional<SharedTopics> topics;

  private final Optional<SharedIntents> intents;

  private final Optional<SharedSentiments> sentiments;

  private final Map<String, Object> additionalProperties;

  private ReadV1ResponseResults(
      Optional<ReadV1ResponseResultsSummary> summary,
      Optional<SharedTopics> topics,
      Optional<SharedIntents> intents,
      Optional<SharedSentiments> sentiments,
      Map<String, Object> additionalProperties) {
    this.summary = summary;
    this.topics = topics;
    this.intents = intents;
    this.sentiments = sentiments;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("summary")
  public Optional<ReadV1ResponseResultsSummary> getSummary() {
    return summary;
  }

  @JsonProperty("topics")
  public Optional<SharedTopics> getTopics() {
    return topics;
  }

  @JsonProperty("intents")
  public Optional<SharedIntents> getIntents() {
    return intents;
  }

  @JsonProperty("sentiments")
  public Optional<SharedSentiments> getSentiments() {
    return sentiments;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ReadV1ResponseResults && equalTo((ReadV1ResponseResults) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ReadV1ResponseResults other) {
    return summary.equals(other.summary)
        && topics.equals(other.topics)
        && intents.equals(other.intents)
        && sentiments.equals(other.sentiments);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.summary, this.topics, this.intents, this.sentiments);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static final class Builder {
    private Optional<ReadV1ResponseResultsSummary> summary = Optional.empty();

    private Optional<SharedTopics> topics = Optional.empty();

    private Optional<SharedIntents> intents = Optional.empty();

    private Optional<SharedSentiments> sentiments = Optional.empty();

    @JsonAnySetter private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {}

    public Builder from(ReadV1ResponseResults other) {
      summary(other.getSummary());
      topics(other.getTopics());
      intents(other.getIntents());
      sentiments(other.getSentiments());
      return this;
    }

    @JsonSetter(value = "summary", nulls = Nulls.SKIP)
    public Builder summary(Optional<ReadV1ResponseResultsSummary> summary) {
      this.summary = summary;
      return this;
    }

    public Builder summary(ReadV1ResponseResultsSummary summary) {
      this.summary = Optional.ofNullable(summary);
      return this;
    }

    @JsonSetter(value = "topics", nulls = Nulls.SKIP)
    public Builder topics(Optional<SharedTopics> topics) {
      this.topics = topics;
      return this;
    }

    public Builder topics(SharedTopics topics) {
      this.topics = Optional.ofNullable(topics);
      return this;
    }

    @JsonSetter(value = "intents", nulls = Nulls.SKIP)
    public Builder intents(Optional<SharedIntents> intents) {
      this.intents = intents;
      return this;
    }

    public Builder intents(SharedIntents intents) {
      this.intents = Optional.ofNullable(intents);
      return this;
    }

    @JsonSetter(value = "sentiments", nulls = Nulls.SKIP)
    public Builder sentiments(Optional<SharedSentiments> sentiments) {
      this.sentiments = sentiments;
      return this;
    }

    public Builder sentiments(SharedSentiments sentiments) {
      this.sentiments = Optional.ofNullable(sentiments);
      return this;
    }

    public ReadV1ResponseResults build() {
      return new ReadV1ResponseResults(summary, topics, intents, sentiments, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
