/** This file was auto-generated by Fern from our API Definition. */
package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SharedTopicsResultsTopicsSegmentsItem.Builder.class)
public final class SharedTopicsResultsTopicsSegmentsItem {
  private final Optional<String> text;

  private final Optional<Double> startWord;

  private final Optional<Double> endWord;

  private final Optional<List<SharedTopicsResultsTopicsSegmentsItemTopicsItem>> topics;

  private final Map<String, Object> additionalProperties;

  private SharedTopicsResultsTopicsSegmentsItem(
      Optional<String> text,
      Optional<Double> startWord,
      Optional<Double> endWord,
      Optional<List<SharedTopicsResultsTopicsSegmentsItemTopicsItem>> topics,
      Map<String, Object> additionalProperties) {
    this.text = text;
    this.startWord = startWord;
    this.endWord = endWord;
    this.topics = topics;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("text")
  public Optional<String> getText() {
    return text;
  }

  @JsonProperty("start_word")
  public Optional<Double> getStartWord() {
    return startWord;
  }

  @JsonProperty("end_word")
  public Optional<Double> getEndWord() {
    return endWord;
  }

  @JsonProperty("topics")
  public Optional<List<SharedTopicsResultsTopicsSegmentsItemTopicsItem>> getTopics() {
    return topics;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SharedTopicsResultsTopicsSegmentsItem
        && equalTo((SharedTopicsResultsTopicsSegmentsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SharedTopicsResultsTopicsSegmentsItem other) {
    return text.equals(other.text)
        && startWord.equals(other.startWord)
        && endWord.equals(other.endWord)
        && topics.equals(other.topics);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.text, this.startWord, this.endWord, this.topics);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static final class Builder {
    private Optional<String> text = Optional.empty();

    private Optional<Double> startWord = Optional.empty();

    private Optional<Double> endWord = Optional.empty();

    private Optional<List<SharedTopicsResultsTopicsSegmentsItemTopicsItem>> topics =
        Optional.empty();

    @JsonAnySetter private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {}

    public Builder from(SharedTopicsResultsTopicsSegmentsItem other) {
      text(other.getText());
      startWord(other.getStartWord());
      endWord(other.getEndWord());
      topics(other.getTopics());
      return this;
    }

    @JsonSetter(value = "text", nulls = Nulls.SKIP)
    public Builder text(Optional<String> text) {
      this.text = text;
      return this;
    }

    public Builder text(String text) {
      this.text = Optional.ofNullable(text);
      return this;
    }

    @JsonSetter(value = "start_word", nulls = Nulls.SKIP)
    public Builder startWord(Optional<Double> startWord) {
      this.startWord = startWord;
      return this;
    }

    public Builder startWord(Double startWord) {
      this.startWord = Optional.ofNullable(startWord);
      return this;
    }

    @JsonSetter(value = "end_word", nulls = Nulls.SKIP)
    public Builder endWord(Optional<Double> endWord) {
      this.endWord = endWord;
      return this;
    }

    public Builder endWord(Double endWord) {
      this.endWord = Optional.ofNullable(endWord);
      return this;
    }

    @JsonSetter(value = "topics", nulls = Nulls.SKIP)
    public Builder topics(Optional<List<SharedTopicsResultsTopicsSegmentsItemTopicsItem>> topics) {
      this.topics = topics;
      return this;
    }

    public Builder topics(List<SharedTopicsResultsTopicsSegmentsItemTopicsItem> topics) {
      this.topics = Optional.ofNullable(topics);
      return this;
    }

    public SharedTopicsResultsTopicsSegmentsItem build() {
      return new SharedTopicsResultsTopicsSegmentsItem(
          text, startWord, endWord, topics, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
