/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.read.v1.text.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TextAnalyzeRequestSummarize {
    public static final TextAnalyzeRequestSummarize V2 = new TextAnalyzeRequestSummarize(Value.V2, "v2");

    private final Value value;

    private final String string;

    TextAnalyzeRequestSummarize(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TextAnalyzeRequestSummarize
                        && this.string.equals(((TextAnalyzeRequestSummarize) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case V2:
                return visitor.visitV2();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TextAnalyzeRequestSummarize valueOf(String value) {
        switch (value) {
            case "v2":
                return V2;
            default:
                return new TextAnalyzeRequestSummarize(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        V2,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitV2();

        T visitUnknown(String unknownType);
    }
}
