/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.speak.v1;

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.speak.v1.audio.AsyncAudioClient;

public class AsyncV1Client {
  protected final ClientOptions clientOptions;

  protected final Supplier<AsyncAudioClient> audioClient;

  public AsyncV1Client(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.audioClient = Suppliers.memoize(() -> new AsyncAudioClient(clientOptions));
  }

  public AsyncAudioClient audio() {
    return this.audioClient.get();
  }
}
