/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.listen.v1.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListenV1UtteranceEnd.Builder.class)
public final class ListenV1UtteranceEnd {
    private final List<Integer> channel;

    private final double lastWordEnd;

    private final Map<String, Object> additionalProperties;

    private ListenV1UtteranceEnd(List<Integer> channel, double lastWordEnd, Map<String, Object> additionalProperties) {
        this.channel = channel;
        this.lastWordEnd = lastWordEnd;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Message type identifier
     */
    @JsonProperty("type")
    public String getType() {
        return "UtteranceEnd";
    }

    /**
     * @return The channel
     */
    @JsonProperty("channel")
    public List<Integer> getChannel() {
        return channel;
    }

    /**
     * @return The last word end
     */
    @JsonProperty("last_word_end")
    public double getLastWordEnd() {
        return lastWordEnd;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListenV1UtteranceEnd && equalTo((ListenV1UtteranceEnd) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListenV1UtteranceEnd other) {
        return channel.equals(other.channel) && lastWordEnd == other.lastWordEnd;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.channel, this.lastWordEnd);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static LastWordEndStage builder() {
        return new Builder();
    }

    public interface LastWordEndStage {
        /**
         * <p>The last word end</p>
         */
        _FinalStage lastWordEnd(double lastWordEnd);

        Builder from(ListenV1UtteranceEnd other);
    }

    public interface _FinalStage {
        ListenV1UtteranceEnd build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The channel</p>
         */
        _FinalStage channel(List<Integer> channel);

        _FinalStage addChannel(Integer channel);

        _FinalStage addAllChannel(List<Integer> channel);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements LastWordEndStage, _FinalStage {
        private double lastWordEnd;

        private List<Integer> channel = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListenV1UtteranceEnd other) {
            channel(other.getChannel());
            lastWordEnd(other.getLastWordEnd());
            return this;
        }

        /**
         * <p>The last word end</p>
         * <p>The last word end</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("last_word_end")
        public _FinalStage lastWordEnd(double lastWordEnd) {
            this.lastWordEnd = lastWordEnd;
            return this;
        }

        /**
         * <p>The channel</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllChannel(List<Integer> channel) {
            if (channel != null) {
                this.channel.addAll(channel);
            }
            return this;
        }

        /**
         * <p>The channel</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addChannel(Integer channel) {
            this.channel.add(channel);
            return this;
        }

        /**
         * <p>The channel</p>
         */
        @java.lang.Override
        @JsonSetter(value = "channel", nulls = Nulls.SKIP)
        public _FinalStage channel(List<Integer> channel) {
            this.channel.clear();
            if (channel != null) {
                this.channel.addAll(channel);
            }
            return this;
        }

        @java.lang.Override
        public ListenV1UtteranceEnd build() {
            return new ListenV1UtteranceEnd(channel, lastWordEnd, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
