/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.listen.v1.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListenV1Metadata.Builder.class)
public final class ListenV1Metadata {
    private final String transactionKey;

    private final String requestId;

    private final String sha256;

    private final String created;

    private final double duration;

    private final int channels;

    private final Map<String, Object> additionalProperties;

    private ListenV1Metadata(
            String transactionKey,
            String requestId,
            String sha256,
            String created,
            double duration,
            int channels,
            Map<String, Object> additionalProperties) {
        this.transactionKey = transactionKey;
        this.requestId = requestId;
        this.sha256 = sha256;
        this.created = created;
        this.duration = duration;
        this.channels = channels;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Message type identifier
     */
    @JsonProperty("type")
    public String getType() {
        return "Metadata";
    }

    /**
     * @return The transaction key
     */
    @JsonProperty("transaction_key")
    public String getTransactionKey() {
        return transactionKey;
    }

    /**
     * @return The request ID
     */
    @JsonProperty("request_id")
    public String getRequestId() {
        return requestId;
    }

    /**
     * @return The sha256
     */
    @JsonProperty("sha256")
    public String getSha256() {
        return sha256;
    }

    /**
     * @return The created
     */
    @JsonProperty("created")
    public String getCreated() {
        return created;
    }

    /**
     * @return The duration
     */
    @JsonProperty("duration")
    public double getDuration() {
        return duration;
    }

    /**
     * @return The channels
     */
    @JsonProperty("channels")
    public int getChannels() {
        return channels;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListenV1Metadata && equalTo((ListenV1Metadata) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListenV1Metadata other) {
        return transactionKey.equals(other.transactionKey)
                && requestId.equals(other.requestId)
                && sha256.equals(other.sha256)
                && created.equals(other.created)
                && duration == other.duration
                && channels == other.channels;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.transactionKey, this.requestId, this.sha256, this.created, this.duration, this.channels);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TransactionKeyStage builder() {
        return new Builder();
    }

    public interface TransactionKeyStage {
        /**
         * <p>The transaction key</p>
         */
        RequestIdStage transactionKey(@NotNull String transactionKey);

        Builder from(ListenV1Metadata other);
    }

    public interface RequestIdStage {
        /**
         * <p>The request ID</p>
         */
        Sha256Stage requestId(@NotNull String requestId);
    }

    public interface Sha256Stage {
        /**
         * <p>The sha256</p>
         */
        CreatedStage sha256(@NotNull String sha256);
    }

    public interface CreatedStage {
        /**
         * <p>The created</p>
         */
        DurationStage created(@NotNull String created);
    }

    public interface DurationStage {
        /**
         * <p>The duration</p>
         */
        ChannelsStage duration(double duration);
    }

    public interface ChannelsStage {
        /**
         * <p>The channels</p>
         */
        _FinalStage channels(int channels);
    }

    public interface _FinalStage {
        ListenV1Metadata build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements TransactionKeyStage,
                    RequestIdStage,
                    Sha256Stage,
                    CreatedStage,
                    DurationStage,
                    ChannelsStage,
                    _FinalStage {
        private String transactionKey;

        private String requestId;

        private String sha256;

        private String created;

        private double duration;

        private int channels;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListenV1Metadata other) {
            transactionKey(other.getTransactionKey());
            requestId(other.getRequestId());
            sha256(other.getSha256());
            created(other.getCreated());
            duration(other.getDuration());
            channels(other.getChannels());
            return this;
        }

        /**
         * <p>The transaction key</p>
         * <p>The transaction key</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("transaction_key")
        public RequestIdStage transactionKey(@NotNull String transactionKey) {
            this.transactionKey = Objects.requireNonNull(transactionKey, "transactionKey must not be null");
            return this;
        }

        /**
         * <p>The request ID</p>
         * <p>The request ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("request_id")
        public Sha256Stage requestId(@NotNull String requestId) {
            this.requestId = Objects.requireNonNull(requestId, "requestId must not be null");
            return this;
        }

        /**
         * <p>The sha256</p>
         * <p>The sha256</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("sha256")
        public CreatedStage sha256(@NotNull String sha256) {
            this.sha256 = Objects.requireNonNull(sha256, "sha256 must not be null");
            return this;
        }

        /**
         * <p>The created</p>
         * <p>The created</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created")
        public DurationStage created(@NotNull String created) {
            this.created = Objects.requireNonNull(created, "created must not be null");
            return this;
        }

        /**
         * <p>The duration</p>
         * <p>The duration</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("duration")
        public ChannelsStage duration(double duration) {
            this.duration = duration;
            return this;
        }

        /**
         * <p>The channels</p>
         * <p>The channels</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("channels")
        public _FinalStage channels(int channels) {
            this.channels = channels;
            return this;
        }

        @java.lang.Override
        public ListenV1Metadata build() {
            return new ListenV1Metadata(
                    transactionKey, requestId, sha256, created, duration, channels, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
