/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.speak.v2.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SpeakV2SpeechMetadataControlsApplied.Builder.class)
public final class SpeakV2SpeechMetadataControlsApplied {
    private final int pronunciationsApplied;

    private final int breaksApplied;

    private final int pronunciationWarnings;

    private final Map<String, Object> additionalProperties;

    private SpeakV2SpeechMetadataControlsApplied(
            int pronunciationsApplied,
            int breaksApplied,
            int pronunciationWarnings,
            Map<String, Object> additionalProperties) {
        this.pronunciationsApplied = pronunciationsApplied;
        this.breaksApplied = breaksApplied;
        this.pronunciationWarnings = pronunciationWarnings;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Pronunciation overrides successfully applied. Mirrors the Aura-2 <code>dg-pronunciations-applied</code> REST header.
     */
    @JsonProperty("pronunciations_applied")
    public int getPronunciationsApplied() {
        return pronunciationsApplied;
    }

    /**
     * @return Pause (break) controls successfully applied. Mirrors the Aura-2 <code>dg-breaks-applied</code> REST header. A pause whose duration was out of range or off the supported increment is stripped rather than applied, so it is excluded from this count.
     */
    @JsonProperty("breaks_applied")
    public int getBreaksApplied() {
        return breaksApplied;
    }

    /**
     * @return Pronunciation entries that triggered a warning (invalid IPA, word too long). Mirrors the Aura-2 <code>dg-pronunciation-warnings</code> REST header.
     */
    @JsonProperty("pronunciation_warnings")
    public int getPronunciationWarnings() {
        return pronunciationWarnings;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SpeakV2SpeechMetadataControlsApplied
                && equalTo((SpeakV2SpeechMetadataControlsApplied) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SpeakV2SpeechMetadataControlsApplied other) {
        return pronunciationsApplied == other.pronunciationsApplied
                && breaksApplied == other.breaksApplied
                && pronunciationWarnings == other.pronunciationWarnings;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.pronunciationsApplied, this.breaksApplied, this.pronunciationWarnings);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PronunciationsAppliedStage builder() {
        return new Builder();
    }

    public interface PronunciationsAppliedStage {
        /**
         * <p>Pronunciation overrides successfully applied. Mirrors the Aura-2 <code>dg-pronunciations-applied</code> REST header.</p>
         */
        BreaksAppliedStage pronunciationsApplied(int pronunciationsApplied);

        Builder from(SpeakV2SpeechMetadataControlsApplied other);
    }

    public interface BreaksAppliedStage {
        /**
         * <p>Pause (break) controls successfully applied. Mirrors the Aura-2 <code>dg-breaks-applied</code> REST header. A pause whose duration was out of range or off the supported increment is stripped rather than applied, so it is excluded from this count.</p>
         */
        PronunciationWarningsStage breaksApplied(int breaksApplied);
    }

    public interface PronunciationWarningsStage {
        /**
         * <p>Pronunciation entries that triggered a warning (invalid IPA, word too long). Mirrors the Aura-2 <code>dg-pronunciation-warnings</code> REST header.</p>
         */
        _FinalStage pronunciationWarnings(int pronunciationWarnings);
    }

    public interface _FinalStage {
        SpeakV2SpeechMetadataControlsApplied build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements PronunciationsAppliedStage, BreaksAppliedStage, PronunciationWarningsStage, _FinalStage {
        private int pronunciationsApplied;

        private int breaksApplied;

        private int pronunciationWarnings;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SpeakV2SpeechMetadataControlsApplied other) {
            pronunciationsApplied(other.getPronunciationsApplied());
            breaksApplied(other.getBreaksApplied());
            pronunciationWarnings(other.getPronunciationWarnings());
            return this;
        }

        /**
         * <p>Pronunciation overrides successfully applied. Mirrors the Aura-2 <code>dg-pronunciations-applied</code> REST header.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("pronunciations_applied")
        public BreaksAppliedStage pronunciationsApplied(int pronunciationsApplied) {
            this.pronunciationsApplied = pronunciationsApplied;
            return this;
        }

        /**
         * <p>Pause (break) controls successfully applied. Mirrors the Aura-2 <code>dg-breaks-applied</code> REST header. A pause whose duration was out of range or off the supported increment is stripped rather than applied, so it is excluded from this count.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("breaks_applied")
        public PronunciationWarningsStage breaksApplied(int breaksApplied) {
            this.breaksApplied = breaksApplied;
            return this;
        }

        /**
         * <p>Pronunciation entries that triggered a warning (invalid IPA, word too long). Mirrors the Aura-2 <code>dg-pronunciation-warnings</code> REST header.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("pronunciation_warnings")
        public _FinalStage pronunciationWarnings(int pronunciationWarnings) {
            this.pronunciationWarnings = pronunciationWarnings;
            return this;
        }

        @java.lang.Override
        public SpeakV2SpeechMetadataControlsApplied build() {
            return new SpeakV2SpeechMetadataControlsApplied(
                    pronunciationsApplied, breaksApplied, pronunciationWarnings, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
