/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.speak.v2.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SpeakV2Warning.Builder.class)
public final class SpeakV2Warning {
    private final String code;

    private final String description;

    private final Map<String, Object> additionalProperties;

    private SpeakV2Warning(String code, String description, Map<String, Object> additionalProperties) {
        this.code = code;
        this.description = description;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Message type identifier
     */
    @JsonProperty("type")
    public String getType() {
        return "Warning";
    }

    /**
     * @return Warning code identifying the condition, in <code>SCREAMING_SNAKE_CASE</code>.
     * <p>Turn-scoped codes: <code>NO_ACTIVE_SPEECH</code> (a speech-scoped message arrived with no active turn), <code>NO_SYNTHESIZABLE_TEXT</code> (the turn's text was entirely whitespace or punctuation, so it produced no audio and is completed with a zero-duration <code>SpeechMetadata</code>), and <code>SYNTHESIS_RETRYING</code> (a synthesis request failed and is being retried).</p>
     * <p>Inline-control codes are reserved and not currently emitted, because inline pause and pronunciation controls are not yet applied: <code>BREAKS_LIMIT_EXCEEDED</code> (too many pause controls, or two pauses with no intervening text), <code>BREAK_TOKENS_OUT_OF_RANGE</code> (pause durations outside the range the model supports), <code>BREAK_TOKENS_WITH_INVALID_INCREMENTS</code> (pause durations off the model's supported increment), <code>PRONUNCIATION_WARNINGS</code> (a pronunciation override contained invalid IPA), <code>PRONUNCIATION_TOO_LONG</code> (an IPA string exceeded the length limit), <code>PRONUNCIATIONS_LIMIT_EXCEEDED</code> (too many pronunciation controls in one turn).</p>
     * <p>Interrupt-scoped codes, each meaning the <code>Interrupt</code> was ignored: <code>NO_AUDIO_GENERATED</code> (the session has produced no audio yet, so there is nothing to interrupt), <code>INTERRUPT_IN_PROGRESS</code> (an earlier <code>Interrupt</code> is still being processed — at most one is handled at a time), <code>INVALID_INTERRUPT_OFFSET</code> (the <code>playback_offset</code> did not advance past the position a prior interrupt established).</p>
     */
    @JsonProperty("code")
    public String getCode() {
        return code;
    }

    /**
     * @return A human-readable description of the warning
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SpeakV2Warning && equalTo((SpeakV2Warning) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SpeakV2Warning other) {
        return code.equals(other.code) && description.equals(other.description);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.code, this.description);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CodeStage builder() {
        return new Builder();
    }

    public interface CodeStage {
        /**
         * <p>Warning code identifying the condition, in <code>SCREAMING_SNAKE_CASE</code>.</p>
         * <p>Turn-scoped codes: <code>NO_ACTIVE_SPEECH</code> (a speech-scoped message arrived with no active turn), <code>NO_SYNTHESIZABLE_TEXT</code> (the turn's text was entirely whitespace or punctuation, so it produced no audio and is completed with a zero-duration <code>SpeechMetadata</code>), and <code>SYNTHESIS_RETRYING</code> (a synthesis request failed and is being retried).</p>
         * <p>Inline-control codes are reserved and not currently emitted, because inline pause and pronunciation controls are not yet applied: <code>BREAKS_LIMIT_EXCEEDED</code> (too many pause controls, or two pauses with no intervening text), <code>BREAK_TOKENS_OUT_OF_RANGE</code> (pause durations outside the range the model supports), <code>BREAK_TOKENS_WITH_INVALID_INCREMENTS</code> (pause durations off the model's supported increment), <code>PRONUNCIATION_WARNINGS</code> (a pronunciation override contained invalid IPA), <code>PRONUNCIATION_TOO_LONG</code> (an IPA string exceeded the length limit), <code>PRONUNCIATIONS_LIMIT_EXCEEDED</code> (too many pronunciation controls in one turn).</p>
         * <p>Interrupt-scoped codes, each meaning the <code>Interrupt</code> was ignored: <code>NO_AUDIO_GENERATED</code> (the session has produced no audio yet, so there is nothing to interrupt), <code>INTERRUPT_IN_PROGRESS</code> (an earlier <code>Interrupt</code> is still being processed — at most one is handled at a time), <code>INVALID_INTERRUPT_OFFSET</code> (the <code>playback_offset</code> did not advance past the position a prior interrupt established).</p>
         */
        DescriptionStage code(@NotNull String code);

        Builder from(SpeakV2Warning other);
    }

    public interface DescriptionStage {
        /**
         * <p>A human-readable description of the warning</p>
         */
        _FinalStage description(@NotNull String description);
    }

    public interface _FinalStage {
        SpeakV2Warning build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CodeStage, DescriptionStage, _FinalStage {
        private String code;

        private String description;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SpeakV2Warning other) {
            code(other.getCode());
            description(other.getDescription());
            return this;
        }

        /**
         * <p>Warning code identifying the condition, in <code>SCREAMING_SNAKE_CASE</code>.</p>
         * <p>Turn-scoped codes: <code>NO_ACTIVE_SPEECH</code> (a speech-scoped message arrived with no active turn), <code>NO_SYNTHESIZABLE_TEXT</code> (the turn's text was entirely whitespace or punctuation, so it produced no audio and is completed with a zero-duration <code>SpeechMetadata</code>), and <code>SYNTHESIS_RETRYING</code> (a synthesis request failed and is being retried).</p>
         * <p>Inline-control codes are reserved and not currently emitted, because inline pause and pronunciation controls are not yet applied: <code>BREAKS_LIMIT_EXCEEDED</code> (too many pause controls, or two pauses with no intervening text), <code>BREAK_TOKENS_OUT_OF_RANGE</code> (pause durations outside the range the model supports), <code>BREAK_TOKENS_WITH_INVALID_INCREMENTS</code> (pause durations off the model's supported increment), <code>PRONUNCIATION_WARNINGS</code> (a pronunciation override contained invalid IPA), <code>PRONUNCIATION_TOO_LONG</code> (an IPA string exceeded the length limit), <code>PRONUNCIATIONS_LIMIT_EXCEEDED</code> (too many pronunciation controls in one turn).</p>
         * <p>Interrupt-scoped codes, each meaning the <code>Interrupt</code> was ignored: <code>NO_AUDIO_GENERATED</code> (the session has produced no audio yet, so there is nothing to interrupt), <code>INTERRUPT_IN_PROGRESS</code> (an earlier <code>Interrupt</code> is still being processed — at most one is handled at a time), <code>INVALID_INTERRUPT_OFFSET</code> (the <code>playback_offset</code> did not advance past the position a prior interrupt established).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("code")
        public DescriptionStage code(@NotNull String code) {
            this.code = Objects.requireNonNull(code, "code must not be null");
            return this;
        }

        /**
         * <p>A human-readable description of the warning</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public _FinalStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        @java.lang.Override
        public SpeakV2Warning build() {
            return new SpeakV2Warning(code, description, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
