/** This file was auto-generated by Fern from our API Definition. */
package resources.manage.v1.projects.billing.balances;

import core.ClientOptions;
import core.RequestOptions;
import java.util.concurrent.CompletableFuture;
import types.GetProjectBalanceV1Response;
import types.ListProjectBalancesV1Response;

public class AsyncBalancesClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawBalancesClient rawClient;

  public AsyncBalancesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawBalancesClient(clientOptions);
  }

  /** Get responses with HTTP metadata like headers */
  public AsyncRawBalancesClient withRawResponse() {
    return this.rawClient;
  }

  /** Generates a list of outstanding balances for the specified project */
  public CompletableFuture<ListProjectBalancesV1Response> list(String projectId) {
    return this.rawClient.list(projectId).thenApply(response -> response.body());
  }

  /** Generates a list of outstanding balances for the specified project */
  public CompletableFuture<ListProjectBalancesV1Response> list(
      String projectId, RequestOptions requestOptions) {
    return this.rawClient.list(projectId, requestOptions).thenApply(response -> response.body());
  }

  /** Retrieves details about the specified balance */
  public CompletableFuture<GetProjectBalanceV1Response> get(String projectId, String balanceId) {
    return this.rawClient.get(projectId, balanceId).thenApply(response -> response.body());
  }

  /** Retrieves details about the specified balance */
  public CompletableFuture<GetProjectBalanceV1Response> get(
      String projectId, String balanceId, RequestOptions requestOptions) {
    return this.rawClient
        .get(projectId, balanceId, requestOptions)
        .thenApply(response -> response.body());
  }
}
