/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.selfhosted;

import com.deepgram.core.ClientOptions;
import com.deepgram.core.Suppliers;
import com.deepgram.resources.selfhosted.v1.AsyncV1Client;
import java.util.function.Supplier;

public class AsyncSelfHostedClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncV1Client> v1Client;

    public AsyncSelfHostedClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.v1Client = Suppliers.memoize(() -> new AsyncV1Client(clientOptions));
    }

    public AsyncV1Client v1() {
        return this.v1Client.get();
    }
}
