/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.resources.selfhosted.v1.distributioncredentials;

import com.deepgram.api.core.ClientOptions;
import com.deepgram.api.core.DeepgramApiApiException;
import com.deepgram.api.core.DeepgramApiException;
import com.deepgram.api.core.DeepgramApiHttpResponse;
import com.deepgram.api.core.MediaTypes;
import com.deepgram.api.core.ObjectMappers;
import com.deepgram.api.core.QueryStringMapper;
import com.deepgram.api.core.RequestOptions;
import com.deepgram.api.errors.BadRequestError;
import com.deepgram.api.resources.selfhosted.v1.distributioncredentials.requests.CreateProjectDistributionCredentialsV1Request;
import com.deepgram.api.types.CreateProjectDistributionCredentialsV1Response;
import com.deepgram.api.types.GetProjectDistributionCredentialsV1Response;
import com.deepgram.api.types.ListProjectDistributionCredentialsV1Response;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawDistributionCredentialsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawDistributionCredentialsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Lists sets of distribution credentials for the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<ListProjectDistributionCredentialsV1Response>> list(
            String projectId) {
        return list(projectId, null);
    }

    /**
     * Lists sets of distribution credentials for the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<ListProjectDistributionCredentialsV1Response>> list(
            String projectId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL())
                .newBuilder()
                .addPathSegments("v1/projects")
                .addPathSegment(projectId)
                .addPathSegments("self-hosted/distribution")
                .addPathSegments("credentials")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<DeepgramApiHttpResponse<ListProjectDistributionCredentialsV1Response>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new DeepgramApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, ListProjectDistributionCredentialsV1Response.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 400) {
                            future.completeExceptionally(new BadRequestError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new DeepgramApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Creates a set of distribution credentials for the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<CreateProjectDistributionCredentialsV1Response>> create(
            String projectId) {
        return create(
                projectId,
                CreateProjectDistributionCredentialsV1Request.builder().build());
    }

    /**
     * Creates a set of distribution credentials for the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<CreateProjectDistributionCredentialsV1Response>> create(
            String projectId, CreateProjectDistributionCredentialsV1Request request) {
        return create(projectId, request, null);
    }

    /**
     * Creates a set of distribution credentials for the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<CreateProjectDistributionCredentialsV1Response>> create(
            String projectId, CreateProjectDistributionCredentialsV1Request request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL())
                .newBuilder()
                .addPathSegments("v1/projects")
                .addPathSegment(projectId)
                .addPathSegments("self-hosted/distribution")
                .addPathSegments("credentials");
        if (request.getProvider().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "provider", request.getProvider().get(), false);
        }
        if (request.getScopes().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "scopes", request.getScopes().get(), true);
        }
        Map<String, Object> properties = new HashMap<>();
        properties.put("comment", request.getComment());
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<DeepgramApiHttpResponse<CreateProjectDistributionCredentialsV1Response>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new DeepgramApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, CreateProjectDistributionCredentialsV1Response.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 400) {
                            future.completeExceptionally(new BadRequestError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new DeepgramApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Returns a set of distribution credentials for the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response>> get(
            String projectId, String distributionCredentialsId) {
        return get(projectId, distributionCredentialsId, null);
    }

    /**
     * Returns a set of distribution credentials for the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response>> get(
            String projectId, String distributionCredentialsId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL())
                .newBuilder()
                .addPathSegments("v1/projects")
                .addPathSegment(projectId)
                .addPathSegments("self-hosted/distribution/credentials")
                .addPathSegment(distributionCredentialsId)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new DeepgramApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, GetProjectDistributionCredentialsV1Response.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 400) {
                            future.completeExceptionally(new BadRequestError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new DeepgramApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Deletes a set of distribution credentials for the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response>> delete(
            String projectId, String distributionCredentialsId) {
        return delete(projectId, distributionCredentialsId, null);
    }

    /**
     * Deletes a set of distribution credentials for the specified project
     */
    public CompletableFuture<DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response>> delete(
            String projectId, String distributionCredentialsId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL())
                .newBuilder()
                .addPathSegments("v1/projects")
                .addPathSegment(projectId)
                .addPathSegments("self-hosted/distribution/credentials")
                .addPathSegment(distributionCredentialsId)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<DeepgramApiHttpResponse<GetProjectDistributionCredentialsV1Response>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new DeepgramApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, GetProjectDistributionCredentialsV1Response.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 400) {
                            future.completeExceptionally(new BadRequestError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new DeepgramApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DeepgramApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
