/** This file was auto-generated by Fern from our API Definition. */
package resources.speak.v1.audio;

import core.ClientOptions;
import core.RequestOptions;
import java.io.InputStream;
import java.util.concurrent.CompletableFuture;
import resources.speak.v1.audio.requests.SpeakV1Request;

public class AsyncAudioClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawAudioClient rawClient;

  public AsyncAudioClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawAudioClient(clientOptions);
  }

  /** Get responses with HTTP metadata like headers */
  public AsyncRawAudioClient withRawResponse() {
    return this.rawClient;
  }

  /** Convert text into natural-sounding speech using Deepgram's TTS REST API */
  public CompletableFuture<InputStream> generate(SpeakV1Request request) {
    return this.rawClient.generate(request).thenApply(response -> response.body());
  }

  /** Convert text into natural-sounding speech using Deepgram's TTS REST API */
  public CompletableFuture<InputStream> generate(
      SpeakV1Request request, RequestOptions requestOptions) {
    return this.rawClient.generate(request, requestOptions).thenApply(response -> response.body());
  }
}
