/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AgentV1UpdateSpeakSpeakProviderAwsPollyVoice {
    public static final AgentV1UpdateSpeakSpeakProviderAwsPollyVoice ARTHUR =
            new AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value.ARTHUR, "Arthur");

    public static final AgentV1UpdateSpeakSpeakProviderAwsPollyVoice JOANNA =
            new AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value.JOANNA, "Joanna");

    public static final AgentV1UpdateSpeakSpeakProviderAwsPollyVoice BRIAN =
            new AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value.BRIAN, "Brian");

    public static final AgentV1UpdateSpeakSpeakProviderAwsPollyVoice AMY =
            new AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value.AMY, "Amy");

    public static final AgentV1UpdateSpeakSpeakProviderAwsPollyVoice EMMA =
            new AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value.EMMA, "Emma");

    public static final AgentV1UpdateSpeakSpeakProviderAwsPollyVoice MATTHEW =
            new AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value.MATTHEW, "Matthew");

    public static final AgentV1UpdateSpeakSpeakProviderAwsPollyVoice ARIA =
            new AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value.ARIA, "Aria");

    public static final AgentV1UpdateSpeakSpeakProviderAwsPollyVoice AYANDA =
            new AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value.AYANDA, "Ayanda");

    private final Value value;

    private final String string;

    AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AgentV1UpdateSpeakSpeakProviderAwsPollyVoice
                        && this.string.equals(((AgentV1UpdateSpeakSpeakProviderAwsPollyVoice) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ARTHUR:
                return visitor.visitArthur();
            case JOANNA:
                return visitor.visitJoanna();
            case BRIAN:
                return visitor.visitBrian();
            case AMY:
                return visitor.visitAmy();
            case EMMA:
                return visitor.visitEmma();
            case MATTHEW:
                return visitor.visitMatthew();
            case ARIA:
                return visitor.visitAria();
            case AYANDA:
                return visitor.visitAyanda();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AgentV1UpdateSpeakSpeakProviderAwsPollyVoice valueOf(String value) {
        switch (value) {
            case "Arthur":
                return ARTHUR;
            case "Joanna":
                return JOANNA;
            case "Brian":
                return BRIAN;
            case "Amy":
                return AMY;
            case "Emma":
                return EMMA;
            case "Matthew":
                return MATTHEW;
            case "Aria":
                return ARIA;
            case "Ayanda":
                return AYANDA;
            default:
                return new AgentV1UpdateSpeakSpeakProviderAwsPollyVoice(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        MATTHEW,

        JOANNA,

        AMY,

        EMMA,

        BRIAN,

        ARTHUR,

        ARIA,

        AYANDA,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitMatthew();

        T visitJoanna();

        T visitAmy();

        T visitEmma();

        T visitBrian();

        T visitArthur();

        T visitAria();

        T visitAyanda();

        T visitUnknown(String unknownType);
    }
}
