/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.api.resources.agent.v1.types;

import com.deepgram.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentV1SettingsAgentSpeakEndpointProviderDeepgram.Builder.class)
public final class AgentV1SettingsAgentSpeakEndpointProviderDeepgram {
    private final AgentV1SettingsAgentSpeakEndpointProviderDeepgramModel model;

    private final Map<String, Object> additionalProperties;

    private AgentV1SettingsAgentSpeakEndpointProviderDeepgram(
            AgentV1SettingsAgentSpeakEndpointProviderDeepgramModel model, Map<String, Object> additionalProperties) {
        this.model = model;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Deepgram TTS model
     */
    @JsonProperty("model")
    public AgentV1SettingsAgentSpeakEndpointProviderDeepgramModel getModel() {
        return model;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentV1SettingsAgentSpeakEndpointProviderDeepgram
                && equalTo((AgentV1SettingsAgentSpeakEndpointProviderDeepgram) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentV1SettingsAgentSpeakEndpointProviderDeepgram other) {
        return model.equals(other.model);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.model);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ModelStage builder() {
        return new Builder();
    }

    public interface ModelStage {
        /**
         * <p>Deepgram TTS model</p>
         */
        _FinalStage model(@NotNull AgentV1SettingsAgentSpeakEndpointProviderDeepgramModel model);

        Builder from(AgentV1SettingsAgentSpeakEndpointProviderDeepgram other);
    }

    public interface _FinalStage {
        AgentV1SettingsAgentSpeakEndpointProviderDeepgram build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ModelStage, _FinalStage {
        private AgentV1SettingsAgentSpeakEndpointProviderDeepgramModel model;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AgentV1SettingsAgentSpeakEndpointProviderDeepgram other) {
            model(other.getModel());
            return this;
        }

        /**
         * <p>Deepgram TTS model</p>
         * <p>Deepgram TTS model</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("model")
        public _FinalStage model(@NotNull AgentV1SettingsAgentSpeakEndpointProviderDeepgramModel model) {
            this.model = Objects.requireNonNull(model, "model must not be null");
            return this;
        }

        @java.lang.Override
        public AgentV1SettingsAgentSpeakEndpointProviderDeepgram build() {
            return new AgentV1SettingsAgentSpeakEndpointProviderDeepgram(model, additionalProperties);
        }
    }
}
