/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.manage.v1.projects.usage.breakdown.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BreakdownGetRequestEndpoint {
    public static final BreakdownGetRequestEndpoint AGENT = new BreakdownGetRequestEndpoint(Value.AGENT, "agent");

    public static final BreakdownGetRequestEndpoint READ = new BreakdownGetRequestEndpoint(Value.READ, "read");

    public static final BreakdownGetRequestEndpoint LISTEN = new BreakdownGetRequestEndpoint(Value.LISTEN, "listen");

    public static final BreakdownGetRequestEndpoint SPEAK = new BreakdownGetRequestEndpoint(Value.SPEAK, "speak");

    private final Value value;

    private final String string;

    BreakdownGetRequestEndpoint(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BreakdownGetRequestEndpoint
                        && this.string.equals(((BreakdownGetRequestEndpoint) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case AGENT:
                return visitor.visitAgent();
            case READ:
                return visitor.visitRead();
            case LISTEN:
                return visitor.visitListen();
            case SPEAK:
                return visitor.visitSpeak();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BreakdownGetRequestEndpoint valueOf(String value) {
        switch (value) {
            case "agent":
                return AGENT;
            case "read":
                return READ;
            case "listen":
                return LISTEN;
            case "speak":
                return SPEAK;
            default:
                return new BreakdownGetRequestEndpoint(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        LISTEN,

        READ,

        SPEAK,

        AGENT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitListen();

        T visitRead();

        T visitSpeak();

        T visitAgent();

        T visitUnknown(String unknownType);
    }
}
