/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.speak.v1;

import com.deepgram.core.ClientOptions;
import com.deepgram.core.Suppliers;
import com.deepgram.resources.speak.v1.audio.AsyncAudioClient;
import com.deepgram.resources.speak.v1.websocket.V1WebSocketClient;
import java.util.function.Supplier;

public class AsyncV1Client {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncAudioClient> audioClient;

    public AsyncV1Client(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.audioClient = Suppliers.memoize(() -> new AsyncAudioClient(clientOptions));
    }

    /**
     * Creates a new WebSocket client for the v1 channel.
     */
    public V1WebSocketClient v1WebSocket() {
        return new V1WebSocketClient(clientOptions);
    }

    public AsyncAudioClient audio() {
        return this.audioClient.get();
    }
}
