/** This file was auto-generated by Fern from our API Definition. */
package resources.speak.v1.audio.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AudioGenerateRequestEncoding {
  public static final AudioGenerateRequestEncoding MULAW =
      new AudioGenerateRequestEncoding(Value.MULAW, "mulaw");

  public static final AudioGenerateRequestEncoding AAC =
      new AudioGenerateRequestEncoding(Value.AAC, "aac");

  public static final AudioGenerateRequestEncoding FLAC =
      new AudioGenerateRequestEncoding(Value.FLAC, "flac");

  public static final AudioGenerateRequestEncoding MP3 =
      new AudioGenerateRequestEncoding(Value.MP3, "mp3");

  public static final AudioGenerateRequestEncoding LINEAR16 =
      new AudioGenerateRequestEncoding(Value.LINEAR16, "linear16");

  public static final AudioGenerateRequestEncoding OPUS =
      new AudioGenerateRequestEncoding(Value.OPUS, "opus");

  public static final AudioGenerateRequestEncoding ALAW =
      new AudioGenerateRequestEncoding(Value.ALAW, "alaw");

  private final Value value;

  private final String string;

  AudioGenerateRequestEncoding(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other)
        || (other instanceof AudioGenerateRequestEncoding
            && this.string.equals(((AudioGenerateRequestEncoding) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case MULAW:
        return visitor.visitMulaw();
      case AAC:
        return visitor.visitAac();
      case FLAC:
        return visitor.visitFlac();
      case MP3:
        return visitor.visitMp3();
      case LINEAR16:
        return visitor.visitLinear16();
      case OPUS:
        return visitor.visitOpus();
      case ALAW:
        return visitor.visitAlaw();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
  public static AudioGenerateRequestEncoding valueOf(String value) {
    switch (value) {
      case "mulaw":
        return MULAW;
      case "aac":
        return AAC;
      case "flac":
        return FLAC;
      case "mp3":
        return MP3;
      case "linear16":
        return LINEAR16;
      case "opus":
        return OPUS;
      case "alaw":
        return ALAW;
      default:
        return new AudioGenerateRequestEncoding(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    LINEAR16,

    FLAC,

    MULAW,

    ALAW,

    MP3,

    OPUS,

    AAC,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitLinear16();

    T visitFlac();

    T visitMulaw();

    T visitAlaw();

    T visitMp3();

    T visitOpus();

    T visitAac();

    T visitUnknown(String unknownType);
  }
}
