/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentV1SettingsAgentContextMessagesItemFunctionCalls.Builder.class
)
public final class AgentV1SettingsAgentContextMessagesItemFunctionCalls {
  private final List<AgentV1SettingsAgentContextMessagesItemFunctionCallsFunctionCallsItem> functionCalls;

  private final Map<String, Object> additionalProperties;

  private AgentV1SettingsAgentContextMessagesItemFunctionCalls(
      List<AgentV1SettingsAgentContextMessagesItemFunctionCallsFunctionCallsItem> functionCalls,
      Map<String, Object> additionalProperties) {
    this.functionCalls = functionCalls;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public String getType() {
    return "History";
  }

  /**
   * @return List of function call objects
   */
  @JsonProperty("function_calls")
  public List<AgentV1SettingsAgentContextMessagesItemFunctionCallsFunctionCallsItem> getFunctionCalls(
      ) {
    return functionCalls;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentV1SettingsAgentContextMessagesItemFunctionCalls && equalTo((AgentV1SettingsAgentContextMessagesItemFunctionCalls) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentV1SettingsAgentContextMessagesItemFunctionCalls other) {
    return functionCalls.equals(other.functionCalls);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.functionCalls);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<AgentV1SettingsAgentContextMessagesItemFunctionCallsFunctionCallsItem> functionCalls = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(AgentV1SettingsAgentContextMessagesItemFunctionCalls other) {
      functionCalls(other.getFunctionCalls());
      return this;
    }

    /**
     * <p>List of function call objects</p>
     */
    @JsonSetter(
        value = "function_calls",
        nulls = Nulls.SKIP
    )
    public Builder functionCalls(
        List<AgentV1SettingsAgentContextMessagesItemFunctionCallsFunctionCallsItem> functionCalls) {
      this.functionCalls.clear();
      if (functionCalls != null) {
        this.functionCalls.addAll(functionCalls);
      }
      return this;
    }

    public Builder addFunctionCalls(
        AgentV1SettingsAgentContextMessagesItemFunctionCallsFunctionCallsItem functionCalls) {
      this.functionCalls.add(functionCalls);
      return this;
    }

    public Builder addAllFunctionCalls(
        List<AgentV1SettingsAgentContextMessagesItemFunctionCallsFunctionCallsItem> functionCalls) {
      if (functionCalls != null) {
        this.functionCalls.addAll(functionCalls);
      }
      return this;
    }

    public AgentV1SettingsAgentContextMessagesItemFunctionCalls build() {
      return new AgentV1SettingsAgentContextMessagesItemFunctionCalls(functionCalls, additionalProperties);
    }
  }
}
