/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.agent.v1.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentV1SettingsAudioInput.Builder.class
)
public final class AgentV1SettingsAudioInput {
  private final AgentV1SettingsAudioInputEncoding encoding;

  private final double sampleRate;

  private final Map<String, Object> additionalProperties;

  private AgentV1SettingsAudioInput(AgentV1SettingsAudioInputEncoding encoding, double sampleRate,
      Map<String, Object> additionalProperties) {
    this.encoding = encoding;
    this.sampleRate = sampleRate;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Audio encoding format
   */
  @JsonProperty("encoding")
  public AgentV1SettingsAudioInputEncoding getEncoding() {
    return encoding;
  }

  /**
   * @return Sample rate in Hz. Common values are 16000, 24000, 44100, 48000
   */
  @JsonProperty("sample_rate")
  public double getSampleRate() {
    return sampleRate;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentV1SettingsAudioInput && equalTo((AgentV1SettingsAudioInput) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentV1SettingsAudioInput other) {
    return encoding.equals(other.encoding) && sampleRate == other.sampleRate;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.encoding, this.sampleRate);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EncodingStage builder() {
    return new Builder();
  }

  public interface EncodingStage {
    /**
     * <p>Audio encoding format</p>
     */
    SampleRateStage encoding(@NotNull AgentV1SettingsAudioInputEncoding encoding);

    Builder from(AgentV1SettingsAudioInput other);
  }

  public interface SampleRateStage {
    /**
     * <p>Sample rate in Hz. Common values are 16000, 24000, 44100, 48000</p>
     */
    _FinalStage sampleRate(double sampleRate);
  }

  public interface _FinalStage {
    AgentV1SettingsAudioInput build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EncodingStage, SampleRateStage, _FinalStage {
    private AgentV1SettingsAudioInputEncoding encoding;

    private double sampleRate;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AgentV1SettingsAudioInput other) {
      encoding(other.getEncoding());
      sampleRate(other.getSampleRate());
      return this;
    }

    /**
     * <p>Audio encoding format</p>
     * <p>Audio encoding format</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("encoding")
    public SampleRateStage encoding(@NotNull AgentV1SettingsAudioInputEncoding encoding) {
      this.encoding = Objects.requireNonNull(encoding, "encoding must not be null");
      return this;
    }

    /**
     * <p>Sample rate in Hz. Common values are 16000, 24000, 44100, 48000</p>
     * <p>Sample rate in Hz. Common values are 16000, 24000, 44100, 48000</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("sample_rate")
    public _FinalStage sampleRate(double sampleRate) {
      this.sampleRate = sampleRate;
      return this;
    }

    @java.lang.Override
    public AgentV1SettingsAudioInput build() {
      return new AgentV1SettingsAudioInput(encoding, sampleRate, additionalProperties);
    }
  }
}
