/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.speak.v1.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SpeakV1Cleared.Builder.class)
public final class SpeakV1Cleared {
    private final SpeakV1ClearedType type;

    private final double sequenceId;

    private final Map<String, Object> additionalProperties;

    private SpeakV1Cleared(SpeakV1ClearedType type, double sequenceId, Map<String, Object> additionalProperties) {
        this.type = type;
        this.sequenceId = sequenceId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Message type identifier
     */
    @JsonProperty("type")
    public SpeakV1ClearedType getType() {
        return type;
    }

    /**
     * @return The sequence ID of the response
     */
    @JsonProperty("sequence_id")
    public double getSequenceId() {
        return sequenceId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SpeakV1Cleared && equalTo((SpeakV1Cleared) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SpeakV1Cleared other) {
        return type.equals(other.type) && sequenceId == other.sequenceId;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.sequenceId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>Message type identifier</p>
         */
        SequenceIdStage type(@NotNull SpeakV1ClearedType type);

        Builder from(SpeakV1Cleared other);
    }

    public interface SequenceIdStage {
        /**
         * <p>The sequence ID of the response</p>
         */
        _FinalStage sequenceId(double sequenceId);
    }

    public interface _FinalStage {
        SpeakV1Cleared build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, SequenceIdStage, _FinalStage {
        private SpeakV1ClearedType type;

        private double sequenceId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SpeakV1Cleared other) {
            type(other.getType());
            sequenceId(other.getSequenceId());
            return this;
        }

        /**
         * <p>Message type identifier</p>
         * <p>Message type identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public SequenceIdStage type(@NotNull SpeakV1ClearedType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>The sequence ID of the response</p>
         * <p>The sequence ID of the response</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("sequence_id")
        public _FinalStage sequenceId(double sequenceId) {
            this.sequenceId = sequenceId;
            return this;
        }

        @java.lang.Override
        public SpeakV1Cleared build() {
            return new SpeakV1Cleared(type, sequenceId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
