/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.manage.v1.projects.members;

import com.deepgram.core.ClientOptions;
import com.deepgram.core.DeepgramApiException;
import com.deepgram.core.DeepgramApiHttpResponse;
import com.deepgram.core.ObjectMappers;
import com.deepgram.core.RequestOptions;
import com.deepgram.errors.BadRequestError;
import com.deepgram.types.DeleteProjectMemberV1Response;
import com.deepgram.types.ListProjectMembersV1Response;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawMembersClient {
    protected final ClientOptions clientOptions;

    public RawMembersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieves a list of members for a given project
     */
    public DeepgramApiHttpResponse<ListProjectMembersV1Response> list(String projectId) {
        return list(projectId, null);
    }

    /**
     * Retrieves a list of members for a given project
     */
    public DeepgramApiHttpResponse<ListProjectMembersV1Response> list(String projectId, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL())
                .newBuilder()
                .addPathSegments("v1/projects")
                .addPathSegment(projectId)
                .addPathSegments("members");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new DeepgramApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListProjectMembersV1Response.class),
                        response);
            }
            try {
                if (response.code() == 400) {
                    throw new BadRequestError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new DeepgramApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new DeepgramApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Removes a member from the project using their unique member ID
     */
    public DeepgramApiHttpResponse<DeleteProjectMemberV1Response> delete(String projectId, String memberId) {
        return delete(projectId, memberId, null);
    }

    /**
     * Removes a member from the project using their unique member ID
     */
    public DeepgramApiHttpResponse<DeleteProjectMemberV1Response> delete(
            String projectId, String memberId, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getBaseURL())
                .newBuilder()
                .addPathSegments("v1/projects")
                .addPathSegment(projectId)
                .addPathSegments("members")
                .addPathSegment(memberId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new DeepgramApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, DeleteProjectMemberV1Response.class),
                        response);
            }
            try {
                if (response.code() == 400) {
                    throw new BadRequestError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new DeepgramApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new DeepgramApiException("Network error executing HTTP request", e);
        }
    }
}
