/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = AgentThinkModelsV1ResponseModelsItem.Deserializer.class)
public final class AgentThinkModelsV1ResponseModelsItem {
    private final Object value;

    private final int type;

    private AgentThinkModelsV1ResponseModelsItem(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((AgentThinkModelsV1ResponseModelsItemZero) this.value);
        } else if (this.type == 1) {
            return visitor.visit((AgentThinkModelsV1ResponseModelsItemOne) this.value);
        } else if (this.type == 2) {
            return visitor.visit((AgentThinkModelsV1ResponseModelsItemTwo) this.value);
        } else if (this.type == 3) {
            return visitor.visit((AgentThinkModelsV1ResponseModelsItemThree) this.value);
        } else if (this.type == 4) {
            return visitor.visit((AgentThinkModelsV1ResponseModelsItemId) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentThinkModelsV1ResponseModelsItem
                && equalTo((AgentThinkModelsV1ResponseModelsItem) other);
    }

    private boolean equalTo(AgentThinkModelsV1ResponseModelsItem other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static AgentThinkModelsV1ResponseModelsItem of(AgentThinkModelsV1ResponseModelsItemZero value) {
        return new AgentThinkModelsV1ResponseModelsItem(value, 0);
    }

    public static AgentThinkModelsV1ResponseModelsItem of(AgentThinkModelsV1ResponseModelsItemOne value) {
        return new AgentThinkModelsV1ResponseModelsItem(value, 1);
    }

    public static AgentThinkModelsV1ResponseModelsItem of(AgentThinkModelsV1ResponseModelsItemTwo value) {
        return new AgentThinkModelsV1ResponseModelsItem(value, 2);
    }

    public static AgentThinkModelsV1ResponseModelsItem of(AgentThinkModelsV1ResponseModelsItemThree value) {
        return new AgentThinkModelsV1ResponseModelsItem(value, 3);
    }

    public static AgentThinkModelsV1ResponseModelsItem of(AgentThinkModelsV1ResponseModelsItemId value) {
        return new AgentThinkModelsV1ResponseModelsItem(value, 4);
    }

    public interface Visitor<T> {
        T visit(AgentThinkModelsV1ResponseModelsItemZero value);

        T visit(AgentThinkModelsV1ResponseModelsItemOne value);

        T visit(AgentThinkModelsV1ResponseModelsItemTwo value);

        T visit(AgentThinkModelsV1ResponseModelsItemThree value);

        T visit(AgentThinkModelsV1ResponseModelsItemId value);
    }

    static final class Deserializer extends StdDeserializer<AgentThinkModelsV1ResponseModelsItem> {
        Deserializer() {
            super(AgentThinkModelsV1ResponseModelsItem.class);
        }

        @java.lang.Override
        public AgentThinkModelsV1ResponseModelsItem deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, AgentThinkModelsV1ResponseModelsItemZero.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, AgentThinkModelsV1ResponseModelsItemOne.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, AgentThinkModelsV1ResponseModelsItemTwo.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("name")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, AgentThinkModelsV1ResponseModelsItemThree.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, AgentThinkModelsV1ResponseModelsItemId.class));
                } catch (RuntimeException e) {
                }
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
