/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CartesiaModelId {
    public static final CartesiaModelId SONIC2 = new CartesiaModelId(Value.SONIC2, "sonic-2");

    public static final CartesiaModelId SONIC_MULTILINGUAL =
            new CartesiaModelId(Value.SONIC_MULTILINGUAL, "sonic-multilingual");

    private final Value value;

    private final String string;

    CartesiaModelId(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CartesiaModelId && this.string.equals(((CartesiaModelId) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SONIC2:
                return visitor.visitSonic2();
            case SONIC_MULTILINGUAL:
                return visitor.visitSonicMultilingual();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CartesiaModelId valueOf(String value) {
        switch (value) {
            case "sonic-2":
                return SONIC2;
            case "sonic-multilingual":
                return SONIC_MULTILINGUAL;
            default:
                return new CartesiaModelId(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SONIC2,

        SONIC_MULTILINGUAL,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSonic2();

        T visitSonicMultilingual();

        T visitUnknown(String unknownType);
    }
}
