/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeepgramListenProviderV2.Builder.class)
public final class DeepgramListenProviderV2 {
    private final Optional<String> version;

    private final String model;

    private final Optional<DeepgramListenProviderV2LanguageHint> languageHint;

    private final Optional<List<String>> keyterms;

    private final Map<String, Object> additionalProperties;

    private DeepgramListenProviderV2(
            Optional<String> version,
            String model,
            Optional<DeepgramListenProviderV2LanguageHint> languageHint,
            Optional<List<String>> keyterms,
            Map<String, Object> additionalProperties) {
        this.version = version;
        this.model = model;
        this.languageHint = languageHint;
        this.keyterms = keyterms;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Provider type for speech-to-text
     */
    @JsonProperty("type")
    public String getType() {
        return "deepgram";
    }

    /**
     * @return Specifies usage of the V2 Deepgram speech-to-text API (e.g. Flux)
     */
    @JsonProperty("version")
    public Optional<String> getVersion() {
        return version;
    }

    /**
     * @return Model to use for speech to text using the V2 API (e.g. flux-general-en, flux-general-multi)
     */
    @JsonProperty("model")
    public String getModel() {
        return model;
    }

    /**
     * @return One or more BCP-47 language codes to bias the model toward specific languages. Only supported when model is flux-general-multi. Without hints, the model auto-detects the spoken language. See the Language Prompting guide for details.
     */
    @JsonProperty("language_hint")
    public Optional<DeepgramListenProviderV2LanguageHint> getLanguageHint() {
        return languageHint;
    }

    /**
     * @return Prompt keyterm recognition to improve Keyword Recall Rate
     */
    @JsonProperty("keyterms")
    public Optional<List<String>> getKeyterms() {
        return keyterms;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeepgramListenProviderV2 && equalTo((DeepgramListenProviderV2) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeepgramListenProviderV2 other) {
        return version.equals(other.version)
                && model.equals(other.model)
                && languageHint.equals(other.languageHint)
                && keyterms.equals(other.keyterms);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.version, this.model, this.languageHint, this.keyterms);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ModelStage builder() {
        return new Builder();
    }

    public interface ModelStage {
        /**
         * <p>Model to use for speech to text using the V2 API (e.g. flux-general-en, flux-general-multi)</p>
         */
        _FinalStage model(@NotNull String model);

        Builder from(DeepgramListenProviderV2 other);
    }

    public interface _FinalStage {
        DeepgramListenProviderV2 build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Specifies usage of the V2 Deepgram speech-to-text API (e.g. Flux)</p>
         */
        _FinalStage version(Optional<String> version);

        _FinalStage version(String version);

        /**
         * <p>One or more BCP-47 language codes to bias the model toward specific languages. Only supported when model is flux-general-multi. Without hints, the model auto-detects the spoken language. See the Language Prompting guide for details.</p>
         */
        _FinalStage languageHint(Optional<DeepgramListenProviderV2LanguageHint> languageHint);

        _FinalStage languageHint(DeepgramListenProviderV2LanguageHint languageHint);

        /**
         * <p>Prompt keyterm recognition to improve Keyword Recall Rate</p>
         */
        _FinalStage keyterms(Optional<List<String>> keyterms);

        _FinalStage keyterms(List<String> keyterms);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ModelStage, _FinalStage {
        private String model;

        private Optional<List<String>> keyterms = Optional.empty();

        private Optional<DeepgramListenProviderV2LanguageHint> languageHint = Optional.empty();

        private Optional<String> version = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DeepgramListenProviderV2 other) {
            version(other.getVersion());
            model(other.getModel());
            languageHint(other.getLanguageHint());
            keyterms(other.getKeyterms());
            return this;
        }

        /**
         * <p>Model to use for speech to text using the V2 API (e.g. flux-general-en, flux-general-multi)</p>
         * <p>Model to use for speech to text using the V2 API (e.g. flux-general-en, flux-general-multi)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("model")
        public _FinalStage model(@NotNull String model) {
            this.model = Objects.requireNonNull(model, "model must not be null");
            return this;
        }

        /**
         * <p>Prompt keyterm recognition to improve Keyword Recall Rate</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage keyterms(List<String> keyterms) {
            this.keyterms = Optional.ofNullable(keyterms);
            return this;
        }

        /**
         * <p>Prompt keyterm recognition to improve Keyword Recall Rate</p>
         */
        @java.lang.Override
        @JsonSetter(value = "keyterms", nulls = Nulls.SKIP)
        public _FinalStage keyterms(Optional<List<String>> keyterms) {
            this.keyterms = keyterms;
            return this;
        }

        /**
         * <p>One or more BCP-47 language codes to bias the model toward specific languages. Only supported when model is flux-general-multi. Without hints, the model auto-detects the spoken language. See the Language Prompting guide for details.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage languageHint(DeepgramListenProviderV2LanguageHint languageHint) {
            this.languageHint = Optional.ofNullable(languageHint);
            return this;
        }

        /**
         * <p>One or more BCP-47 language codes to bias the model toward specific languages. Only supported when model is flux-general-multi. Without hints, the model auto-detects the spoken language. See the Language Prompting guide for details.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "language_hint", nulls = Nulls.SKIP)
        public _FinalStage languageHint(Optional<DeepgramListenProviderV2LanguageHint> languageHint) {
            this.languageHint = languageHint;
            return this;
        }

        /**
         * <p>Specifies usage of the V2 Deepgram speech-to-text API (e.g. Flux)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage version(String version) {
            this.version = Optional.ofNullable(version);
            return this;
        }

        /**
         * <p>Specifies usage of the V2 Deepgram speech-to-text API (e.g. Flux)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "version", nulls = Nulls.SKIP)
        public _FinalStage version(Optional<String> version) {
            this.version = version;
            return this;
        }

        @java.lang.Override
        public DeepgramListenProviderV2 build() {
            return new DeepgramListenProviderV2(version, model, languageHint, keyterms, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
