/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ErrorResponseLegacyError.Builder.class)
public final class ErrorResponseLegacyError {
    private final Optional<String> errCode;

    private final Optional<String> errMsg;

    private final Optional<String> requestId;

    private final Map<String, Object> additionalProperties;

    private ErrorResponseLegacyError(
            Optional<String> errCode,
            Optional<String> errMsg,
            Optional<String> requestId,
            Map<String, Object> additionalProperties) {
        this.errCode = errCode;
        this.errMsg = errMsg;
        this.requestId = requestId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The error code
     */
    @JsonProperty("err_code")
    public Optional<String> getErrCode() {
        return errCode;
    }

    /**
     * @return The error message
     */
    @JsonProperty("err_msg")
    public Optional<String> getErrMsg() {
        return errMsg;
    }

    /**
     * @return The request ID
     */
    @JsonProperty("request_id")
    public Optional<String> getRequestId() {
        return requestId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ErrorResponseLegacyError && equalTo((ErrorResponseLegacyError) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ErrorResponseLegacyError other) {
        return errCode.equals(other.errCode) && errMsg.equals(other.errMsg) && requestId.equals(other.requestId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.errCode, this.errMsg, this.requestId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> errCode = Optional.empty();

        private Optional<String> errMsg = Optional.empty();

        private Optional<String> requestId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ErrorResponseLegacyError other) {
            errCode(other.getErrCode());
            errMsg(other.getErrMsg());
            requestId(other.getRequestId());
            return this;
        }

        /**
         * <p>The error code</p>
         */
        @JsonSetter(value = "err_code", nulls = Nulls.SKIP)
        public Builder errCode(Optional<String> errCode) {
            this.errCode = errCode;
            return this;
        }

        public Builder errCode(String errCode) {
            this.errCode = Optional.ofNullable(errCode);
            return this;
        }

        /**
         * <p>The error message</p>
         */
        @JsonSetter(value = "err_msg", nulls = Nulls.SKIP)
        public Builder errMsg(Optional<String> errMsg) {
            this.errMsg = errMsg;
            return this;
        }

        public Builder errMsg(String errMsg) {
            this.errMsg = Optional.ofNullable(errMsg);
            return this;
        }

        /**
         * <p>The request ID</p>
         */
        @JsonSetter(value = "request_id", nulls = Nulls.SKIP)
        public Builder requestId(Optional<String> requestId) {
            this.requestId = requestId;
            return this;
        }

        public Builder requestId(String requestId) {
            this.requestId = Optional.ofNullable(requestId);
            return this;
        }

        public ErrorResponseLegacyError build() {
            return new ErrorResponseLegacyError(errCode, errMsg, requestId, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
