/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Groq.Builder.class)
public final class Groq {
    private final Optional<String> version;

    private final Optional<Double> temperature;

    private final Optional<GroqThinkProviderReasoningMode> reasoningMode;

    private final Map<String, Object> additionalProperties;

    private Groq(
            Optional<String> version,
            Optional<Double> temperature,
            Optional<GroqThinkProviderReasoningMode> reasoningMode,
            Map<String, Object> additionalProperties) {
        this.version = version;
        this.temperature = temperature;
        this.reasoningMode = reasoningMode;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public String getType() {
        return "groq";
    }

    /**
     * @return The REST API version for the Groq's chat completions API (mostly OpenAI-compatible)
     */
    @JsonProperty("version")
    public Optional<String> getVersion() {
        return version;
    }

    /**
     * @return Groq model to use
     */
    @JsonProperty("model")
    public String getModel() {
        return "openai/gpt-oss-20b";
    }

    /**
     * @return Groq temperature (0-2)
     */
    @JsonProperty("temperature")
    public Optional<Double> getTemperature() {
        return temperature;
    }

    /**
     * @return OpenAI reasoning_effort
     */
    @JsonProperty("reasoning_mode")
    public Optional<GroqThinkProviderReasoningMode> getReasoningMode() {
        return reasoningMode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Groq && equalTo((Groq) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Groq other) {
        return version.equals(other.version)
                && temperature.equals(other.temperature)
                && reasoningMode.equals(other.reasoningMode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.version, this.temperature, this.reasoningMode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> version = Optional.empty();

        private Optional<Double> temperature = Optional.empty();

        private Optional<GroqThinkProviderReasoningMode> reasoningMode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(Groq other) {
            version(other.getVersion());
            temperature(other.getTemperature());
            reasoningMode(other.getReasoningMode());
            return this;
        }

        /**
         * <p>The REST API version for the Groq's chat completions API (mostly OpenAI-compatible)</p>
         */
        @JsonSetter(value = "version", nulls = Nulls.SKIP)
        public Builder version(Optional<String> version) {
            this.version = version;
            return this;
        }

        public Builder version(String version) {
            this.version = Optional.ofNullable(version);
            return this;
        }

        /**
         * <p>Groq temperature (0-2)</p>
         */
        @JsonSetter(value = "temperature", nulls = Nulls.SKIP)
        public Builder temperature(Optional<Double> temperature) {
            this.temperature = temperature;
            return this;
        }

        public Builder temperature(Double temperature) {
            this.temperature = Optional.ofNullable(temperature);
            return this;
        }

        /**
         * <p>OpenAI reasoning_effort</p>
         */
        @JsonSetter(value = "reasoning_mode", nulls = Nulls.SKIP)
        public Builder reasoningMode(Optional<GroqThinkProviderReasoningMode> reasoningMode) {
            this.reasoningMode = reasoningMode;
            return this;
        }

        public Builder reasoningMode(GroqThinkProviderReasoningMode reasoningMode) {
            this.reasoningMode = Optional.ofNullable(reasoningMode);
            return this;
        }

        public Groq build() {
            return new Groq(version, temperature, reasoningMode, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
