/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListProjectKeysV1ResponseApiKeysItem.Builder.class)
public final class ListProjectKeysV1ResponseApiKeysItem {
    private final Optional<ListProjectKeysV1ResponseApiKeysItemMember> member;

    private final Optional<ListProjectKeysV1ResponseApiKeysItemApiKey> apiKey;

    private final Map<String, Object> additionalProperties;

    private ListProjectKeysV1ResponseApiKeysItem(
            Optional<ListProjectKeysV1ResponseApiKeysItemMember> member,
            Optional<ListProjectKeysV1ResponseApiKeysItemApiKey> apiKey,
            Map<String, Object> additionalProperties) {
        this.member = member;
        this.apiKey = apiKey;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("member")
    public Optional<ListProjectKeysV1ResponseApiKeysItemMember> getMember() {
        return member;
    }

    @JsonProperty("api_key")
    public Optional<ListProjectKeysV1ResponseApiKeysItemApiKey> getApiKey() {
        return apiKey;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListProjectKeysV1ResponseApiKeysItem
                && equalTo((ListProjectKeysV1ResponseApiKeysItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListProjectKeysV1ResponseApiKeysItem other) {
        return member.equals(other.member) && apiKey.equals(other.apiKey);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.member, this.apiKey);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ListProjectKeysV1ResponseApiKeysItemMember> member = Optional.empty();

        private Optional<ListProjectKeysV1ResponseApiKeysItemApiKey> apiKey = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListProjectKeysV1ResponseApiKeysItem other) {
            member(other.getMember());
            apiKey(other.getApiKey());
            return this;
        }

        @JsonSetter(value = "member", nulls = Nulls.SKIP)
        public Builder member(Optional<ListProjectKeysV1ResponseApiKeysItemMember> member) {
            this.member = member;
            return this;
        }

        public Builder member(ListProjectKeysV1ResponseApiKeysItemMember member) {
            this.member = Optional.ofNullable(member);
            return this;
        }

        @JsonSetter(value = "api_key", nulls = Nulls.SKIP)
        public Builder apiKey(Optional<ListProjectKeysV1ResponseApiKeysItemApiKey> apiKey) {
            this.apiKey = apiKey;
            return this;
        }

        public Builder apiKey(ListProjectKeysV1ResponseApiKeysItemApiKey apiKey) {
            this.apiKey = Optional.ofNullable(apiKey);
            return this;
        }

        public ListProjectKeysV1ResponseApiKeysItem build() {
            return new ListProjectKeysV1ResponseApiKeysItem(member, apiKey, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
