/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListenV1ResponseMetadataDiarizeInfoArch {
    public static final ListenV1ResponseMetadataDiarizeInfoArch V2 =
            new ListenV1ResponseMetadataDiarizeInfoArch(Value.V2, "v2");

    public static final ListenV1ResponseMetadataDiarizeInfoArch V1 =
            new ListenV1ResponseMetadataDiarizeInfoArch(Value.V1, "v1");

    private final Value value;

    private final String string;

    ListenV1ResponseMetadataDiarizeInfoArch(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListenV1ResponseMetadataDiarizeInfoArch
                        && this.string.equals(((ListenV1ResponseMetadataDiarizeInfoArch) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case V2:
                return visitor.visitV2();
            case V1:
                return visitor.visitV1();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListenV1ResponseMetadataDiarizeInfoArch valueOf(String value) {
        switch (value) {
            case "v2":
                return V2;
            case "v1":
                return V1;
            default:
                return new ListenV1ResponseMetadataDiarizeInfoArch(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        V1,

        V2,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitV1();

        T visitV2();

        T visitUnknown(String unknownType);
    }
}
