/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListenV1ResponseResultsChannelsItemAlternativesItemEntitiesItem.Builder.class)
public final class ListenV1ResponseResultsChannelsItemAlternativesItemEntitiesItem {
    private final Optional<String> label;

    private final Optional<String> value;

    private final Optional<String> rawValue;

    private final Optional<Float> confidence;

    private final Optional<Float> startWord;

    private final Optional<Float> endWord;

    private final Map<String, Object> additionalProperties;

    private ListenV1ResponseResultsChannelsItemAlternativesItemEntitiesItem(
            Optional<String> label,
            Optional<String> value,
            Optional<String> rawValue,
            Optional<Float> confidence,
            Optional<Float> startWord,
            Optional<Float> endWord,
            Map<String, Object> additionalProperties) {
        this.label = label;
        this.value = value;
        this.rawValue = rawValue;
        this.confidence = confidence;
        this.startWord = startWord;
        this.endWord = endWord;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("label")
    public Optional<String> getLabel() {
        return label;
    }

    @JsonProperty("value")
    public Optional<String> getValue() {
        return value;
    }

    @JsonProperty("raw_value")
    public Optional<String> getRawValue() {
        return rawValue;
    }

    @JsonProperty("confidence")
    public Optional<Float> getConfidence() {
        return confidence;
    }

    @JsonProperty("start_word")
    public Optional<Float> getStartWord() {
        return startWord;
    }

    @JsonProperty("end_word")
    public Optional<Float> getEndWord() {
        return endWord;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListenV1ResponseResultsChannelsItemAlternativesItemEntitiesItem
                && equalTo((ListenV1ResponseResultsChannelsItemAlternativesItemEntitiesItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListenV1ResponseResultsChannelsItemAlternativesItemEntitiesItem other) {
        return label.equals(other.label)
                && value.equals(other.value)
                && rawValue.equals(other.rawValue)
                && confidence.equals(other.confidence)
                && startWord.equals(other.startWord)
                && endWord.equals(other.endWord);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.label, this.value, this.rawValue, this.confidence, this.startWord, this.endWord);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> label = Optional.empty();

        private Optional<String> value = Optional.empty();

        private Optional<String> rawValue = Optional.empty();

        private Optional<Float> confidence = Optional.empty();

        private Optional<Float> startWord = Optional.empty();

        private Optional<Float> endWord = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListenV1ResponseResultsChannelsItemAlternativesItemEntitiesItem other) {
            label(other.getLabel());
            value(other.getValue());
            rawValue(other.getRawValue());
            confidence(other.getConfidence());
            startWord(other.getStartWord());
            endWord(other.getEndWord());
            return this;
        }

        @JsonSetter(value = "label", nulls = Nulls.SKIP)
        public Builder label(Optional<String> label) {
            this.label = label;
            return this;
        }

        public Builder label(String label) {
            this.label = Optional.ofNullable(label);
            return this;
        }

        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public Builder value(Optional<String> value) {
            this.value = value;
            return this;
        }

        public Builder value(String value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        @JsonSetter(value = "raw_value", nulls = Nulls.SKIP)
        public Builder rawValue(Optional<String> rawValue) {
            this.rawValue = rawValue;
            return this;
        }

        public Builder rawValue(String rawValue) {
            this.rawValue = Optional.ofNullable(rawValue);
            return this;
        }

        @JsonSetter(value = "confidence", nulls = Nulls.SKIP)
        public Builder confidence(Optional<Float> confidence) {
            this.confidence = confidence;
            return this;
        }

        public Builder confidence(Float confidence) {
            this.confidence = Optional.ofNullable(confidence);
            return this;
        }

        @JsonSetter(value = "start_word", nulls = Nulls.SKIP)
        public Builder startWord(Optional<Float> startWord) {
            this.startWord = startWord;
            return this;
        }

        public Builder startWord(Float startWord) {
            this.startWord = Optional.ofNullable(startWord);
            return this;
        }

        @JsonSetter(value = "end_word", nulls = Nulls.SKIP)
        public Builder endWord(Optional<Float> endWord) {
            this.endWord = endWord;
            return this;
        }

        public Builder endWord(Float endWord) {
            this.endWord = Optional.ofNullable(endWord);
            return this;
        }

        public ListenV1ResponseResultsChannelsItemAlternativesItemEntitiesItem build() {
            return new ListenV1ResponseResultsChannelsItemAlternativesItemEntitiesItem(
                    label, value, rawValue, confidence, startWord, endWord, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
