/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.deepgram.core.WrappedAlias;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OpenAiThinkProvider implements WrappedAlias {
    private final Object value;

    private OpenAiThinkProvider(Object value) {
        this.value = value;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return this == other
                || (other instanceof OpenAiThinkProvider && this.value.equals(((OpenAiThinkProvider) other).value));
    }

    @java.lang.Override
    public int hashCode() {
        return value.hashCode();
    }

    @java.lang.Override
    public String toString() {
        return value.toString();
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OpenAiThinkProvider of(Object value) {
        return new OpenAiThinkProvider(value);
    }
}
