/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ThinkSettingsV1.Builder.class)
public final class ThinkSettingsV1 {
    private final Optional<Object> contextLength;

    private final Map<String, Object> additionalProperties;

    private ThinkSettingsV1(Optional<Object> contextLength, Map<String, Object> additionalProperties) {
        this.contextLength = contextLength;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("context_length")
    public Optional<Object> getContextLength() {
        return contextLength;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ThinkSettingsV1 && equalTo((ThinkSettingsV1) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ThinkSettingsV1 other) {
        return contextLength.equals(other.contextLength);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.contextLength);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Object> contextLength = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ThinkSettingsV1 other) {
            contextLength(other.getContextLength());
            return this;
        }

        @JsonSetter(value = "context_length", nulls = Nulls.SKIP)
        public Builder contextLength(Optional<Object> contextLength) {
            this.contextLength = contextLength;
            return this;
        }

        public Builder contextLength(Object contextLength) {
            this.contextLength = Optional.ofNullable(contextLength);
            return this;
        }

        public ThinkSettingsV1 build() {
            return new ThinkSettingsV1(contextLength, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
