/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.types;

import com.deepgram.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UsageFieldsV1ResponseModelsItem.Builder.class)
public final class UsageFieldsV1ResponseModelsItem {
    private final Optional<String> name;

    private final Optional<String> language;

    private final Optional<String> version;

    private final Optional<String> modelId;

    private final Map<String, Object> additionalProperties;

    private UsageFieldsV1ResponseModelsItem(
            Optional<String> name,
            Optional<String> language,
            Optional<String> version,
            Optional<String> modelId,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.language = language;
        this.version = version;
        this.modelId = modelId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the model.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return The language supported by the model (IETF language tag).
     */
    @JsonProperty("language")
    public Optional<String> getLanguage() {
        return language;
    }

    /**
     * @return Version identifier of the model, typically with a date and a revision number.
     */
    @JsonProperty("version")
    public Optional<String> getVersion() {
        return version;
    }

    /**
     * @return Unique identifier for the model.
     */
    @JsonProperty("model_id")
    public Optional<String> getModelId() {
        return modelId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UsageFieldsV1ResponseModelsItem && equalTo((UsageFieldsV1ResponseModelsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UsageFieldsV1ResponseModelsItem other) {
        return name.equals(other.name)
                && language.equals(other.language)
                && version.equals(other.version)
                && modelId.equals(other.modelId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.language, this.version, this.modelId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<String> language = Optional.empty();

        private Optional<String> version = Optional.empty();

        private Optional<String> modelId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UsageFieldsV1ResponseModelsItem other) {
            name(other.getName());
            language(other.getLanguage());
            version(other.getVersion());
            modelId(other.getModelId());
            return this;
        }

        /**
         * <p>Name of the model.</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>The language supported by the model (IETF language tag).</p>
         */
        @JsonSetter(value = "language", nulls = Nulls.SKIP)
        public Builder language(Optional<String> language) {
            this.language = language;
            return this;
        }

        public Builder language(String language) {
            this.language = Optional.ofNullable(language);
            return this;
        }

        /**
         * <p>Version identifier of the model, typically with a date and a revision number.</p>
         */
        @JsonSetter(value = "version", nulls = Nulls.SKIP)
        public Builder version(Optional<String> version) {
            this.version = version;
            return this;
        }

        public Builder version(String version) {
            this.version = Optional.ofNullable(version);
            return this;
        }

        /**
         * <p>Unique identifier for the model.</p>
         */
        @JsonSetter(value = "model_id", nulls = Nulls.SKIP)
        public Builder modelId(Optional<String> modelId) {
            this.modelId = modelId;
            return this;
        }

        public Builder modelId(String modelId) {
            this.modelId = Optional.ofNullable(modelId);
            return this;
        }

        public UsageFieldsV1ResponseModelsItem build() {
            return new UsageFieldsV1ResponseModelsItem(name, language, version, modelId, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
