/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.deepgram.resources.speak.v2;

import com.deepgram.core.ClientOptions;
import com.deepgram.core.Suppliers;
import com.deepgram.resources.speak.v2.audio.AsyncAudioClient;
import com.deepgram.resources.speak.v2.websocket.V2WebSocketClient;
import java.util.function.Supplier;

public class AsyncV2Client {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncAudioClient> audioClient;

    public AsyncV2Client(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.audioClient = Suppliers.memoize(() -> new AsyncAudioClient(clientOptions));
    }

    /**
     * Creates a new WebSocket client for the v2 channel.
     */
    public V2WebSocketClient v2WebSocket() {
        return new V2WebSocketClient(clientOptions);
    }

    public AsyncAudioClient audio() {
        return this.audioClient.get();
    }
}
