/** This file was auto-generated by Fern from our API Definition. */
package resources.speak.v1.audio.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import resources.speak.v1.audio.types.AudioGenerateRequestCallbackMethod;
import resources.speak.v1.audio.types.AudioGenerateRequestContainer;
import resources.speak.v1.audio.types.AudioGenerateRequestEncoding;
import resources.speak.v1.audio.types.AudioGenerateRequestModel;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SpeakV1Request.Builder.class)
public final class SpeakV1Request {
  private final Optional<List<String>> tag;

  private final Optional<String> callback;

  private final Optional<AudioGenerateRequestCallbackMethod> callbackMethod;

  private final Optional<Boolean> mipOptOut;

  private final Optional<Double> bitRate;

  private final Optional<AudioGenerateRequestContainer> container;

  private final Optional<AudioGenerateRequestEncoding> encoding;

  private final Optional<AudioGenerateRequestModel> model;

  private final Optional<Double> sampleRate;

  private final String text;

  private final Map<String, Object> additionalProperties;

  private SpeakV1Request(
      Optional<List<String>> tag,
      Optional<String> callback,
      Optional<AudioGenerateRequestCallbackMethod> callbackMethod,
      Optional<Boolean> mipOptOut,
      Optional<Double> bitRate,
      Optional<AudioGenerateRequestContainer> container,
      Optional<AudioGenerateRequestEncoding> encoding,
      Optional<AudioGenerateRequestModel> model,
      Optional<Double> sampleRate,
      String text,
      Map<String, Object> additionalProperties) {
    this.tag = tag;
    this.callback = callback;
    this.callbackMethod = callbackMethod;
    this.mipOptOut = mipOptOut;
    this.bitRate = bitRate;
    this.container = container;
    this.encoding = encoding;
    this.model = model;
    this.sampleRate = sampleRate;
    this.text = text;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Label your requests for the purpose of identification during usage reporting
   */
  @JsonIgnore
  public Optional<List<String>> getTag() {
    return tag;
  }

  /**
   * @return URL to which we'll make the callback request
   */
  @JsonIgnore
  public Optional<String> getCallback() {
    return callback;
  }

  /**
   * @return HTTP method by which the callback request will be made
   */
  @JsonIgnore
  public Optional<AudioGenerateRequestCallbackMethod> getCallbackMethod() {
    return callbackMethod;
  }

  /**
   * @return Opts out requests from the Deepgram Model Improvement Program. Refer to our Docs for
   *     pricing impacts before setting this to true. https://dpgr.am/deepgram-mip
   */
  @JsonIgnore
  public Optional<Boolean> getMipOptOut() {
    return mipOptOut;
  }

  /**
   * @return The bitrate of the audio in bits per second. Choose from predefined ranges or specific
   *     values based on the encoding type.
   */
  @JsonIgnore
  public Optional<Double> getBitRate() {
    return bitRate;
  }

  /**
   * @return Container specifies the file format wrapper for the output audio. The available options
   *     depend on the encoding type.
   */
  @JsonIgnore
  public Optional<AudioGenerateRequestContainer> getContainer() {
    return container;
  }

  /**
   * @return Encoding allows you to specify the expected encoding of your audio output
   */
  @JsonIgnore
  public Optional<AudioGenerateRequestEncoding> getEncoding() {
    return encoding;
  }

  /**
   * @return AI model used to process submitted text
   */
  @JsonIgnore
  public Optional<AudioGenerateRequestModel> getModel() {
    return model;
  }

  /**
   * @return Sample Rate specifies the sample rate for the output audio. Based on the encoding,
   *     different sample rates are supported. For some encodings, the sample rate is not
   *     configurable
   */
  @JsonIgnore
  public Optional<Double> getSampleRate() {
    return sampleRate;
  }

  /**
   * @return The text content to be converted to speech
   */
  @JsonProperty("text")
  public String getText() {
    return text;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SpeakV1Request && equalTo((SpeakV1Request) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SpeakV1Request other) {
    return tag.equals(other.tag)
        && callback.equals(other.callback)
        && callbackMethod.equals(other.callbackMethod)
        && mipOptOut.equals(other.mipOptOut)
        && bitRate.equals(other.bitRate)
        && container.equals(other.container)
        && encoding.equals(other.encoding)
        && model.equals(other.model)
        && sampleRate.equals(other.sampleRate)
        && text.equals(other.text);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(
        this.tag,
        this.callback,
        this.callbackMethod,
        this.mipOptOut,
        this.bitRate,
        this.container,
        this.encoding,
        this.model,
        this.sampleRate,
        this.text);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TextStage builder() {
    return new Builder();
  }

  public interface TextStage {
    /** The text content to be converted to speech */
    _FinalStage text(@NotNull String text);

    Builder from(SpeakV1Request other);
  }

  public interface _FinalStage {
    SpeakV1Request build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /** Label your requests for the purpose of identification during usage reporting */
    _FinalStage tag(Optional<List<String>> tag);

    _FinalStage tag(List<String> tag);

    _FinalStage tag(String tag);

    /** URL to which we'll make the callback request */
    _FinalStage callback(Optional<String> callback);

    _FinalStage callback(String callback);

    /** HTTP method by which the callback request will be made */
    _FinalStage callbackMethod(Optional<AudioGenerateRequestCallbackMethod> callbackMethod);

    _FinalStage callbackMethod(AudioGenerateRequestCallbackMethod callbackMethod);

    /**
     * Opts out requests from the Deepgram Model Improvement Program. Refer to our Docs for pricing
     * impacts before setting this to true. https://dpgr.am/deepgram-mip
     */
    _FinalStage mipOptOut(Optional<Boolean> mipOptOut);

    _FinalStage mipOptOut(Boolean mipOptOut);

    /**
     * The bitrate of the audio in bits per second. Choose from predefined ranges or specific values
     * based on the encoding type.
     */
    _FinalStage bitRate(Optional<Double> bitRate);

    _FinalStage bitRate(Double bitRate);

    /**
     * Container specifies the file format wrapper for the output audio. The available options
     * depend on the encoding type.
     */
    _FinalStage container(Optional<AudioGenerateRequestContainer> container);

    _FinalStage container(AudioGenerateRequestContainer container);

    /** Encoding allows you to specify the expected encoding of your audio output */
    _FinalStage encoding(Optional<AudioGenerateRequestEncoding> encoding);

    _FinalStage encoding(AudioGenerateRequestEncoding encoding);

    /** AI model used to process submitted text */
    _FinalStage model(Optional<AudioGenerateRequestModel> model);

    _FinalStage model(AudioGenerateRequestModel model);

    /**
     * Sample Rate specifies the sample rate for the output audio. Based on the encoding, different
     * sample rates are supported. For some encodings, the sample rate is not configurable
     */
    _FinalStage sampleRate(Optional<Double> sampleRate);

    _FinalStage sampleRate(Double sampleRate);
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static final class Builder implements TextStage, _FinalStage {
    private String text;

    private Optional<Double> sampleRate = Optional.empty();

    private Optional<AudioGenerateRequestModel> model = Optional.empty();

    private Optional<AudioGenerateRequestEncoding> encoding = Optional.empty();

    private Optional<AudioGenerateRequestContainer> container = Optional.empty();

    private Optional<Double> bitRate = Optional.empty();

    private Optional<Boolean> mipOptOut = Optional.empty();

    private Optional<AudioGenerateRequestCallbackMethod> callbackMethod = Optional.empty();

    private Optional<String> callback = Optional.empty();

    private Optional<List<String>> tag = Optional.empty();

    @JsonAnySetter private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {}

    @java.lang.Override
    public Builder from(SpeakV1Request other) {
      tag(other.getTag());
      callback(other.getCallback());
      callbackMethod(other.getCallbackMethod());
      mipOptOut(other.getMipOptOut());
      bitRate(other.getBitRate());
      container(other.getContainer());
      encoding(other.getEncoding());
      model(other.getModel());
      sampleRate(other.getSampleRate());
      text(other.getText());
      return this;
    }

    /**
     * The text content to be converted to speech
     *
     * <p>The text content to be converted to speech
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("text")
    public _FinalStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    /**
     * Sample Rate specifies the sample rate for the output audio. Based on the encoding, different
     * sample rates are supported. For some encodings, the sample rate is not configurable
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage sampleRate(Double sampleRate) {
      this.sampleRate = Optional.ofNullable(sampleRate);
      return this;
    }

    /**
     * Sample Rate specifies the sample rate for the output audio. Based on the encoding, different
     * sample rates are supported. For some encodings, the sample rate is not configurable
     */
    @java.lang.Override
    @JsonSetter(value = "sample_rate", nulls = Nulls.SKIP)
    public _FinalStage sampleRate(Optional<Double> sampleRate) {
      this.sampleRate = sampleRate;
      return this;
    }

    /**
     * AI model used to process submitted text
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage model(AudioGenerateRequestModel model) {
      this.model = Optional.ofNullable(model);
      return this;
    }

    /** AI model used to process submitted text */
    @java.lang.Override
    @JsonSetter(value = "model", nulls = Nulls.SKIP)
    public _FinalStage model(Optional<AudioGenerateRequestModel> model) {
      this.model = model;
      return this;
    }

    /**
     * Encoding allows you to specify the expected encoding of your audio output
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage encoding(AudioGenerateRequestEncoding encoding) {
      this.encoding = Optional.ofNullable(encoding);
      return this;
    }

    /** Encoding allows you to specify the expected encoding of your audio output */
    @java.lang.Override
    @JsonSetter(value = "encoding", nulls = Nulls.SKIP)
    public _FinalStage encoding(Optional<AudioGenerateRequestEncoding> encoding) {
      this.encoding = encoding;
      return this;
    }

    /**
     * Container specifies the file format wrapper for the output audio. The available options
     * depend on the encoding type.
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage container(AudioGenerateRequestContainer container) {
      this.container = Optional.ofNullable(container);
      return this;
    }

    /**
     * Container specifies the file format wrapper for the output audio. The available options
     * depend on the encoding type.
     */
    @java.lang.Override
    @JsonSetter(value = "container", nulls = Nulls.SKIP)
    public _FinalStage container(Optional<AudioGenerateRequestContainer> container) {
      this.container = container;
      return this;
    }

    /**
     * The bitrate of the audio in bits per second. Choose from predefined ranges or specific values
     * based on the encoding type.
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage bitRate(Double bitRate) {
      this.bitRate = Optional.ofNullable(bitRate);
      return this;
    }

    /**
     * The bitrate of the audio in bits per second. Choose from predefined ranges or specific values
     * based on the encoding type.
     */
    @java.lang.Override
    @JsonSetter(value = "bit_rate", nulls = Nulls.SKIP)
    public _FinalStage bitRate(Optional<Double> bitRate) {
      this.bitRate = bitRate;
      return this;
    }

    /**
     * Opts out requests from the Deepgram Model Improvement Program. Refer to our Docs for pricing
     * impacts before setting this to true. https://dpgr.am/deepgram-mip
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage mipOptOut(Boolean mipOptOut) {
      this.mipOptOut = Optional.ofNullable(mipOptOut);
      return this;
    }

    /**
     * Opts out requests from the Deepgram Model Improvement Program. Refer to our Docs for pricing
     * impacts before setting this to true. https://dpgr.am/deepgram-mip
     */
    @java.lang.Override
    @JsonSetter(value = "mip_opt_out", nulls = Nulls.SKIP)
    public _FinalStage mipOptOut(Optional<Boolean> mipOptOut) {
      this.mipOptOut = mipOptOut;
      return this;
    }

    /**
     * HTTP method by which the callback request will be made
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage callbackMethod(AudioGenerateRequestCallbackMethod callbackMethod) {
      this.callbackMethod = Optional.ofNullable(callbackMethod);
      return this;
    }

    /** HTTP method by which the callback request will be made */
    @java.lang.Override
    @JsonSetter(value = "callback_method", nulls = Nulls.SKIP)
    public _FinalStage callbackMethod(Optional<AudioGenerateRequestCallbackMethod> callbackMethod) {
      this.callbackMethod = callbackMethod;
      return this;
    }

    /**
     * URL to which we'll make the callback request
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage callback(String callback) {
      this.callback = Optional.ofNullable(callback);
      return this;
    }

    /** URL to which we'll make the callback request */
    @java.lang.Override
    @JsonSetter(value = "callback", nulls = Nulls.SKIP)
    public _FinalStage callback(Optional<String> callback) {
      this.callback = callback;
      return this;
    }

    @java.lang.Override
    public _FinalStage tag(String tag) {
      this.tag = Optional.of(Collections.singletonList(tag));
      return this;
    }

    /**
     * Label your requests for the purpose of identification during usage reporting
     *
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage tag(List<String> tag) {
      this.tag = Optional.ofNullable(tag);
      return this;
    }

    /** Label your requests for the purpose of identification during usage reporting */
    @java.lang.Override
    @JsonSetter(value = "tag", nulls = Nulls.SKIP)
    public _FinalStage tag(Optional<List<String>> tag) {
      this.tag = tag;
      return this;
    }

    @java.lang.Override
    public SpeakV1Request build() {
      return new SpeakV1Request(
          tag,
          callback,
          callbackMethod,
          mipOptOut,
          bitRate,
          container,
          encoding,
          model,
          sampleRate,
          text,
          additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
